# -------------------------------------------------------------------------------------------------
# <copyright file="constants.pyx" company="Nautech Systems Pty Ltd">
#  Copyright (C) 2015-2019 Nautech Systems Pty Ltd. All rights reserved.
#  The use of this source code is governed by the license as found in the LICENSE.md file.
#  http://www.nautechsystems.io
# </copyright>
# -------------------------------------------------------------------------------------------------

ENCODING = 'Encoding'
UTF8 = 'utf-8'

NONE = 'NONE'
TYPE = 'Type'
ID = 'Id'
CANCEL_REASON = 'CancelReason'
ORDER = 'Order'
TIMESTAMP = 'Timestamp'
VENUE = 'Venue'
SYMBOL = 'Symbol'
ORDER_ID_BROKER = 'OrderIdBroker'
TRADER_ID = 'TraderId'
STRATEGY_ID = 'StrategyId'
POSITION_ID = 'PositionId'
ORDER_ID = 'OrderId'
INIT_ID = 'InitId'
LABEL = 'Label'
SUBMITTED_TIME = 'SubmittedTime'
ACCEPTED_TIME = 'AcceptedTime'
REJECTED_TIME = 'RejectedTime'
REJECTED_RESPONSE_TO = 'RejectedResponseTo'
REJECTED_REASON = 'RejectedReason'
WORKING_TIME = 'WorkingTime'
CANCELLED_TIME = 'CancelledTime'
MODIFIED_TIME = 'ModifiedTime'
MODIFIED_PRICE = 'ModifiedPrice'
EXPIRE_TIME = 'ExpireTime'
EXPIRED_TIME = 'ExpiredTime'
EXECUTION_TIME = 'ExecutionTime'
EXECUTION_ID = 'ExecutionId'
EXECUTION_TICKET = 'ExecutionTicket'
ORDER_SIDE = 'OrderSide'
ORDER_TYPE = 'OrderType'
ENTRY = 'Entry'
STOP_LOSS = 'StopLoss'
TAKE_PROFIT = 'TakeProfit'
FILLED_QUANTITY = 'FilledQuantity'
LEAVES_QUANTITY = 'LeavesQuantity'
QUANTITY = 'Quantity'
AVERAGE_PRICE = 'AveragePrice'
PRICE = 'Price'
TIME_IN_FORCE = 'TimeInForce'
ACCOUNT_ID = 'AccountId'
ACCOUNT_NUMBER = 'AccountNumber'
BROKER = 'Broker'
CURRENCY = 'Currency'
CASH_BALANCE = 'CashBalance'
CASH_START_DAY = 'CashStartDay'
CASH_ACTIVITY_DAY = 'CashActivityDay'
MARGIN_USED_LIQUIDATION = 'MarginUsedLiquidation'
MARGIN_USED_MAINTENANCE = 'MarginUsedMaintenance'
MARGIN_RATIO = 'MarginRatio'
MARGIN_CALL_STATUS = 'MarginCallStatus'

BROKER_SYMBOL = 'BrokerSymbol'
QUOTE_CURRENCY = 'QuoteCurrency'
SECURITY_TYPE = 'SecurityType'
TICK_PRECISION = 'TickPrecision'
TICK_SIZE = 'TickSize'
ROUND_LOT_SIZE = 'RoundLotSize'
MIN_STOP_DISTANCE_ENTRY = 'MinStopDistanceEntry'
MIN_STOP_DISTANCE = 'MinStopDistance'
MIN_LIMIT_DISTANCE_ENTRY = 'MinLimitDistanceEntry'
MIN_LIMIT_DISTANCE = 'MinLimitDistance'
MIN_TRADE_SIZE = 'MinTradeSize'
MAX_TRADE_SIZE = 'MaxTradeSize'
ROLL_OVER_INTEREST_BUY = 'RolloverInterestBuy'
ROLL_OVER_INTEREST_SELL = 'RolloverInterestSell'

CORRELATION_ID = 'CorrelationId'
DATA = 'Data'
VALUES = 'Values'
BARS = 'Bars'
TICKS = 'Ticks'
INSTRUMENTS = 'Instruments'
BAR_SPECIFICATION = 'BarSpecification'
FROM_DATETIME = 'FromDateTime'
TO_DATETIME = 'ToDateTime'
