#ifndef add_h
#define add_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

typedef struct OrderBookEntry {
  double price;
  double qty;
  uint64_t update_id;
} OrderBookEntry;

/**
 * Represents a limit order book
 */
typedef struct OrderBook {
  uint64_t timestamp;
  uint64_t last_update_id;
  double best_bid_price;
  double best_ask_price;
  double best_bid_qty;
  double best_ask_qty;
  struct OrderBookEntry _bid_book[25];
  struct OrderBookEntry _ask_book[25];
} OrderBook;

/**
 * Updates the entry with the given quantity and update identifier.
 */
struct OrderBookEntry new_entry(double price, double qty, uint64_t update_id);

/**
 * Updates the entry with the given quantity and update identifier.
 */
void update(struct OrderBookEntry *self, double qty, uint64_t update_id);

/**
 * Initialize a new instance of the `OrderBook` struct.
 */
struct OrderBook new(uint64_t timestamp);

/**
 * Clear stateful values from the order book.
 */
void reset(struct OrderBook *self);

/**
 * Apply the order book entry to the bid side.
 */
void apply_bid_diff(struct OrderBook *self, struct OrderBookEntry entry, uint64_t timestamp);

/**
 * Apply the order book entry to the ask side.
 */
void apply_ask_diff(struct OrderBook *self, struct OrderBookEntry entry, uint64_t timestamp);

/**
 * Returns the current spread from the top of the order book.
 */
double spread(const struct OrderBook *self);

#endif /* add_h */
