# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2021 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------

UTF8 = "utf-8"
NONE = str(None)

TYPE = "Type"
ID = "Id"
ORDER = "Order"
INFO = "Info"
OPTIONS = "Options"
TIMESTAMP = "Timestamp"
VENUE = "Venue"
SYMBOL = "Symbol"
ORDER_ID = "OrderId"
TRADER_ID = "TraderId"
STRATEGY_ID = "StrategyId"
ACCOUNT_ID = "AccountId"
CLIENT_ORDER_ID = "ClientOrderId"
INIT_ID = "InitId"
SUBMITTED_TIME = "SubmittedTime"
ACCEPTED_TIME = "AcceptedTime"
REJECTED_TIME = "RejectedTime"
RESPONSE_TO = "ResponseTo"
REASON = "Reason"
WORKING_TIME = "WorkingTime"
CANCELLED_TIME = "CancelledTime"
AMENDED_TIME = "AmendedTime"
EXPIRE_TIME = "ExpireTime"
EXPIRED_TIME = "ExpiredTime"
EXECUTION_TIME = "ExecutionTime"
EXECUTION_ID = "ExecutionId"
POSITION_ID = "PositionId"
ORDER_SIDE = "OrderSide"
ORDER_TYPE = "OrderType"
POST_ONLY = "PostOnly"
REDUCE_ONLY = "ReduceOnly"
HIDDEN = "Hidden"
ENTRY = "Entry"
STOP_LOSS = "StopLoss"
TAKE_PROFIT = "TakeProfit"
FILL_QTY = "FillQty"
FILL_PRICE = "FillPrice"
CUM_QTY = "CumQty"
LEAVES_QTY = "LeavesQty"
QUANTITY = "Quantity"
COMMISSION = "Commission"
PRICE = "Price"
CURRENCY = "Currency"
TIME_IN_FORCE = "TimeInForce"
LIQUIDITY_SIDE = "LiquiditySide"
ACCOUNT_ID = "AccountId"
ACCOUNT_NUMBER = "AccountNumber"
BROKERAGE = "Brokerage"
BALANCE = "Balance"
MARGIN_BALANCE = "MarginBalance"
MARGIN_AVAILABLE = "MarginAvailable"
BAR = "Bar"
BAR_TYPE = "BarType"
INTERVAL = "Interval"
DELAY = "Delay"

BALANCES = "Balances"
BALANCES_FREE = "BalancesFree"
BALANCES_LOCKED = "BalancesLocked"

INSTRUMENT = "Instrument"
BASE_CURRENCY = "BaseCurrency"
QUOTE_CURRENCY = "QuoteCurrency"
SETTLEMENT_CURRENCY = "SettlementCurrency"
IS_INVERSE = "IsInverse"
COMMISSION_CURRENCY = "CommissionCurrency"
ASSET_TYPE = "AssetType"
PRICE_PRECISION = "PricePrecision"
SIZE_PRECISION = "SizePrecision"
TICK_SIZE = "TickSize"
LOT_SIZE = "LotSize"
MULTIPLIER = "Multiplier"
MIN_QUANTITY = "MinQuantity"
MAX_QUANTITY = "MaxQuantity"
MIN_NOTIONAL = "MinNotional"
MAX_NOTIONAL = "MaxNotional"
MARGIN_INIT = "MarginInit"
MARGIN_MAINT = "MarginMaint"
MAKER_FEE = "MakerFee"
TAKER_FEE = "TakerFee"
SETTLEMENT_FEE = "SettlementFee"
FUNDING_LONG = "FundingLong"
FUNDING_SHORT = "FundingShort"

FROM_DATETIME = "FromDateTime"
TO_DATETIME = "ToDateTime"
LIMIT = "Limit"
