# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2021 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------

UTF8 = "utf-8"
NONE = str(None)

TYPE = "Type"
ID = "Id"
ORDER = "Order"
INFO = "Info"
OPTIONS = "Options"

VENUE = "Venue"
INSTRUMENT_ID = "InstrumentId"
TRADER_ID = "TraderId"
STRATEGY_ID = "StrategyId"
ACCOUNT_ID = "AccountId"
CLIENT_ORDER_ID = "ClientOrderId"
VENUE_ORDER_ID = "VenueOrderId"
INIT_ID = "InitId"
IS_REPORTED = "IsReported"
TIMESTAMP = "Timestamp"
TS_EVENT = "TimestampEvent"
TS_RECV = "TimestampReceived"
TS_SUBMITTED = "TimestampSubmitted"
TS_ACCEPTED = "TimestampAccepted"
TS_REJECTED = "TimestampRejected"
TS_PENDING = "TimestampPending"
TS_CANCELED = "TimestampCanceled"
TS_EXPIRED = "TimestampExpired"
TS_TRIGGERED = "TimestampTriggered"
TS_UPDATED = "TimestampUpdated"
TS_FILLED = "TimestampFilled"
EXPIRE_TIME = "ExpireTime"
RESPONSE_TO = "ResponseTo"
REASON = "Reason"
EXECUTION_ID = "ExecutionId"
POSITION_ID = "PositionId"
ORDER_SIDE = "OrderSide"
ORDER_TYPE = "OrderType"
POST_ONLY = "PostOnly"
REDUCE_ONLY = "ReduceOnly"
HIDDEN = "Hidden"
ENTRY = "Entry"
STOP_LOSS = "StopLoss"
TAKE_PROFIT = "TakeProfit"
LAST_QTY = "LastQty"
LAST_PX = "LastPx"
QUANTITY = "Quantity"
COMMISSION = "Commission"
PRICE = "Price"
TRIGGER = "Trigger"
CURRENCY = "Currency"
TIME_IN_FORCE = "TimeInForce"
LIQUIDITY_SIDE = "LiquiditySide"
ACCOUNT_TYPE = "AccountType"
BALANCES = "Balances"
MARGIN_BALANCE = "MarginBalance"
MARGIN_AVAILABLE = "MarginAvailable"
BAR = "Bar"
BAR_TYPE = "BarType"
INTERVAL = "Interval"
LEVEL = "Level"
DEPTH = "Depth"
KWARGS = "Kwargs"

INSTRUMENT = "Instrument"
ASSET_CLASS = "AssetClass"
ASSET_TYPE = "AssetType"
BASE_CURRENCY = "BaseCurrency"
QUOTE_CURRENCY = "QuoteCurrency"
SETTLEMENT_CURRENCY = "SettlementCurrency"
IS_INVERSE = "IsInverse"
ASSET_TYPE = "AssetType"
PRICE_PRECISION = "PricePrecision"
SIZE_PRECISION = "SizePrecision"
PRICE_INCREMENT = "PriceIncrement"
SIZE_INCREMENT = "SizeIncrement"
MULTIPLIER = "Multiplier"
LOT_SIZE = "LotSize"
MIN_QUANTITY = "MinQuantity"
MAX_QUANTITY = "MaxQuantity"
MIN_NOTIONAL = "MinNotional"
MAX_NOTIONAL = "MaxNotional"
MIN_PRICE = "MinPrice"
MAX_PRICE = "MaxPrice"
MARGIN_INIT = "MarginInit"
MARGIN_MAINT = "MarginMaint"
MAKER_FEE = "MakerFee"
TAKER_FEE = "TakerFee"
SETTLEMENT_FEE = "SettlementFee"
FUNDING_LONG = "FundingLong"
FUNDING_SHORT = "FundingShort"

FROM_DATETIME = "FromDateTime"
TO_DATETIME = "ToDateTime"
LIMIT = "Limit"
