# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2021 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------

UTF8 = "utf-8"
NONE = str(None)

TYPE = "Type"
ID = "Id"
ORDER = "Order"
INFO = "Info"
OPTIONS = "Options"
TIMESTAMP = "Timestamp"
VENUE = "Venue"
INSTRUMENT_ID = "InstrumentId"
CLIENT_ID = "ClientId"
TRADER_ID = "TraderId"
STRATEGY_ID = "StrategyId"
ACCOUNT_ID = "AccountId"
CLIENT_ORDER_ID = "ClientOrderId"
VENUE_ORDER_ID = "VenueOrderId"
INIT_ID = "InitId"
SUBMITTED_TIMESTAMP = "SubmittedTimestamp"
ACCEPTED_TIMESTAMP = "AcceptedTimestamp"
REJECTED_TIMESTAMP = "RejectedTimestamp"
RESPONSE_TO = "ResponseTo"
REASON = "Reason"
PENDING_TIMESTAMP = "PendingTimestamp"
CANCELED_TIMESTAMP = "CanceledTimestamp"
EXPIRE_TIME = "ExpireTime"
EXPIRED_TIMESTAMP = "ExpiredTimestamp"
TRIGGERED_TIMESTAMP = "TriggeredTimestamp"
UPDATED_TIMESTAMP = "UpdatedTime"
EXECUTION_TIMESTAMP = "ExecutionTimestamp"
EXECUTION_ID = "ExecutionId"
POSITION_ID = "PositionId"
ORDER_SIDE = "OrderSide"
ORDER_TYPE = "OrderType"
POST_ONLY = "PostOnly"
REDUCE_ONLY = "ReduceOnly"
HIDDEN = "Hidden"
ENTRY = "Entry"
STOP_LOSS = "StopLoss"
TAKE_PROFIT = "TakeProfit"
LAST_QTY = "LastQty"
LAST_PX = "LastPx"
QUANTITY = "Quantity"
COMMISSION = "Commission"
PRICE = "Price"
TRIGGER = "Trigger"
CURRENCY = "Currency"
TIME_IN_FORCE = "TimeInForce"
LIQUIDITY_SIDE = "LiquiditySide"
ACCOUNT_ID = "AccountId"
ACCOUNT_NUMBER = "AccountNumber"
BALANCE = "Balance"
MARGIN_BALANCE = "MarginBalance"
MARGIN_AVAILABLE = "MarginAvailable"
BAR = "Bar"
BAR_TYPE = "BarType"
INTERVAL = "Interval"
LEVEL = "Level"
DEPTH = "Depth"
KWARGS = "Kwargs"

BALANCES = "Balances"
BALANCES_FREE = "BalancesFree"
BALANCES_LOCKED = "BalancesLocked"

INSTRUMENT = "Instrument"
ASSET_CLASS = "AssetClass"
ASSET_TYPE = "AssetType"
BASE_CURRENCY = "BaseCurrency"
QUOTE_CURRENCY = "QuoteCurrency"
SETTLEMENT_CURRENCY = "SettlementCurrency"
IS_INVERSE = "IsInverse"
ASSET_TYPE = "AssetType"
PRICE_PRECISION = "PricePrecision"
SIZE_PRECISION = "SizePrecision"
TICK_SIZE = "TickSize"
LOT_SIZE = "LotSize"
MULTIPLIER = "Multiplier"
MIN_QUANTITY = "MinQuantity"
MAX_QUANTITY = "MaxQuantity"
MIN_NOTIONAL = "MinNotional"
MAX_NOTIONAL = "MaxNotional"
MIN_PRICE = "MinPrice"
MAX_PRICE = "MaxPrice"
MARGIN_INIT = "MarginInit"
MARGIN_MAINT = "MarginMaint"
MAKER_FEE = "MakerFee"
TAKER_FEE = "TakerFee"
SETTLEMENT_FEE = "SettlementFee"
FUNDING_LONG = "FundingLong"
FUNDING_SHORT = "FundingShort"

FROM_DATETIME = "FromDateTime"
TO_DATETIME = "ToDateTime"
LIMIT = "Limit"
