from typing import Any

from stubs.accounting.accounts.base import Account
from stubs.model.identifiers import InstrumentId
from stubs.model.identifiers import Venue
from stubs.model.objects import Money
from stubs.model.objects import Price

class PortfolioFacade:

    def account(self, venue: Venue) -> Account: ...
    def balances_locked(self, venue: Venue) -> dict[Any, Any]: ...
    def margins_init(self, venue: Venue) -> dict[Any, Any]: ...
    def margins_maint(self, venue: Venue) -> dict[Any, Any]: ...
    def realized_pnls(self, venue: Venue) -> dict[Any, Any]: ...
    def unrealized_pnls(self, venue: Venue) -> dict[Any, Any]: ...
    def total_pnls(self, venue: Venue) -> dict[Any, Any]: ...
    def net_exposures(self, venue: Venue) -> dict[Any, Any]: ...
    def realized_pnl(self, instrument_id: InstrumentId) -> Money: ...
    def unrealized_pnl(self, instrument_id: InstrumentId, price: Price | None = None) -> Money: ...
    def total_pnl(self, instrument_id: InstrumentId, price: Price | None = None) -> Money: ...
    def net_exposure(self, instrument_id: InstrumentId, price: Price | None = None) -> Money: ...
    def net_position(self, instrument_id: InstrumentId) -> object: ...
    def is_net_long(self, instrument_id: InstrumentId) -> bool: ...
    def is_net_short(self, instrument_id: InstrumentId) -> bool: ...
    def is_flat(self, instrument_id: InstrumentId) -> bool: ...
    def is_completely_flat(self) -> bool: ...
