from __future__ import annotations

EQUITIES_TAKER_STRATEGY_ID = "equities_taker"
EQUITIES_TAKER_STRATEGY_FAMILY = "equities_taker"
EQUITIES_TAKER_STRATEGY_VERSION = "v1"
EQUITIES_TAKER_PARAM_SET = "equities_taker"
EQUITIES_TAKER_PROFILE_KEY = "equities_taker"


__all__ = [
    "EQUITIES_TAKER_PARAM_SET",
    "EQUITIES_TAKER_PROFILE_KEY",
    "EQUITIES_TAKER_STRATEGY_FAMILY",
    "EQUITIES_TAKER_STRATEGY_ID",
    "EQUITIES_TAKER_STRATEGY_VERSION",
]
