# This file is automatically generated by pyo3_stub_gen

import typing

from nautilus_trader import core
from nautilus_trader import model

__all__ = [
    "PostgresCacheConfig",
    "PostgresConnectOptions",
    "RedisCacheConfig",
    "RedisMessageBusBacking",
    "RedisMessageBusConfig",
]

@typing.final
class PostgresCacheConfig: ...

@typing.final
class PostgresConnectOptions:
    def __init__(self, host: str, port: int, user: str, password: str, database: str) -> None: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def username(self) -> str: ...
    @property
    def password(self) -> str: ...
    @property
    def database(self) -> str: ...

@typing.final
class RedisMessageBusBacking:
    def __init__(
        self, trader_id: model.TraderId, instance_id: core.UUID4, config_json: bytes
    ) -> None: ...
    def is_closed(self) -> bool: ...
    def publish(self, topic: str, payload: bytes) -> None: ...
    def stream(self, callback: typing.Any) -> typing.Any: ...
    def close(self) -> None: ...

@typing.final
class RedisCacheConfig: ...

@typing.final
class RedisMessageBusConfig: ...
