[grid_mm]
exchange = "bybit"
trader_id = "TESTER-001"
instrument_id = "OPUSDT-LINEAR.BYBIT"
max_position = "20"
trade_size = "20"
num_levels = 3
grid_step_bps = 10
skew_factor = 0.0
requote_threshold_bps = 5
expire_time_secs = 1
on_cancel_resubmit = false

[recorder]
exchange = "bybit"
trader_id = "TESTER-001"
instrument_id = ["OPUSDT-LINEAR.BYBIT", "BTCUSDT-LINEAR.BYBIT", "ETHUSDT-LINEAR.BYBIT", "XAUTUSDT-LINEAR.BYBIT"]
catalog_path = "/var/lib/nautilus-trader/"
book_depth = 50
interval_parquet_dump_seconds = 60

[mmm]
execution_environment = "backtest" # backtest, live, sandbox
exchange = "bybit"
trader_id = "TESTER-001"
instrument_id = "OPUSDT-LINEAR.BYBIT"
path = "/home/mattia/dev/nautilus_trader/data/"
