/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GwApiV1FeeTemplatesPostRequest {
    #[serde(rename = "instructionType")]
    pub instruction_type: InstructionType,
    #[serde(rename = "instruction")]
    pub instruction: Box<models::ApplyFeeTemplateInstruction>,
}

impl GwApiV1FeeTemplatesPostRequest {
    pub fn new(
        instruction_type: InstructionType,
        instruction: models::ApplyFeeTemplateInstruction,
    ) -> GwApiV1FeeTemplatesPostRequest {
        GwApiV1FeeTemplatesPostRequest {
            instruction_type,
            instruction: Box::new(instruction),
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InstructionType {
    #[serde(rename = "APPLY_FEE_TEMPLATE")]
    ApplyFeeTemplate,
}

impl Default for InstructionType {
    fn default() -> InstructionType {
        Self::ApplyFeeTemplate
    }
}
