/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GwApiV1AccountsAccountIdTasksGet200Response {
    RegistrationTasksResponse(Box<models::RegistrationTasksResponse>),
    PendingTasksResponse(Box<models::PendingTasksResponse>),
}

impl Default for GwApiV1AccountsAccountIdTasksGet200Response {
    fn default() -> Self {
        Self::RegistrationTasksResponse(Default::default())
    }
}
