/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountStatusResponse {
    #[serde(rename = "dateOpened", skip_serializing_if = "Option::is_none")]
    pub date_opened: Option<String>,
    #[serde(rename = "dateStarted", skip_serializing_if = "Option::is_none")]
    pub date_started: Option<String>,
    #[serde(rename = "dateClosed", skip_serializing_if = "Option::is_none")]
    pub date_closed: Option<String>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "masterAccountId", skip_serializing_if = "Option::is_none")]
    pub master_account_id: Option<String>,
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
}

impl AccountStatusResponse {
    pub fn new() -> AccountStatusResponse {
        AccountStatusResponse {
            date_opened: None,
            date_started: None,
            date_closed: None,
            account_id: None,
            status: None,
            description: None,
            master_account_id: None,
            state: None,
        }
    }
}
