/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AchInstructionClientAccountInfo {
    #[serde(rename = "bankRoutingNumber")]
    pub bank_routing_number: String,
    #[serde(rename = "bankAccountNumber")]
    pub bank_account_number: String,
    #[serde(rename = "bankName")]
    pub bank_name: String,
    #[serde(rename = "bankAccountTypeCode")]
    pub bank_account_type_code: BankAccountTypeCode,
}

impl AchInstructionClientAccountInfo {
    pub fn new(
        bank_routing_number: String,
        bank_account_number: String,
        bank_name: String,
        bank_account_type_code: BankAccountTypeCode,
    ) -> AchInstructionClientAccountInfo {
        AchInstructionClientAccountInfo {
            bank_routing_number,
            bank_account_number,
            bank_name,
            bank_account_type_code,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BankAccountTypeCode {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
}

impl Default for BankAccountTypeCode {
    fn default() -> BankAccountTypeCode {
        Self::Variant0
    }
}
