/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddRelationship {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<Name>,
    #[serde(
        rename = "ownershipPercentage",
        skip_serializing_if = "Option::is_none"
    )]
    pub ownership_percentage: Option<i32>,
}

impl AddRelationship {
    pub fn new() -> AddRelationship {
        AddRelationship {
            name: None,
            ownership_percentage: None,
        }
    }
}
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Name {
    #[serde(rename = "Account_Holder")]
    AccountHolder,
    #[serde(rename = "Spouse")]
    Spouse,
    #[serde(rename = "Firstholder")]
    Firstholder,
    #[serde(rename = "Secondholder")]
    Secondholder,
    #[serde(rename = "Trader")]
    Trader,
    #[serde(rename = "Secretary")]
    Secretary,
    #[serde(rename = "Treasurer")]
    Treasurer,
    #[serde(rename = "Ceo")]
    Ceo,
    #[serde(rename = "Owner")]
    Owner,
    #[serde(rename = "Trustee")]
    Trustee,
    #[serde(rename = "Beneficiary")]
    Beneficiary,
    #[serde(rename = "Grantor")]
    Grantor,
    #[serde(rename = "Director")]
    Director,
    #[serde(rename = "Principal")]
    Principal,
    #[serde(rename = "Shareholder")]
    Shareholder,
    #[serde(rename = "Partner")]
    Partner,
    #[serde(rename = "Controlling_Officer")]
    ControllingOfficer,
    #[serde(rename = "Beneficialowner")]
    Beneficialowner,
    #[serde(rename = "Signatory")]
    Signatory,
    #[serde(rename = "Comp_Officer")]
    CompOfficer,
    #[serde(rename = "Superv_Broker")]
    SupervBroker,
    #[serde(rename = "Pooled_User")]
    PooledUser,
    #[serde(rename = "Financial_User")]
    FinancialUser,
    #[serde(rename = "Contingent")]
    Contingent,
    #[serde(rename = "Ira_Beneficiary")]
    IraBeneficiary,
    #[serde(rename = "Employee")]
    Employee,
    #[serde(rename = "Non_Employee")]
    NonEmployee,
    #[serde(rename = "Fund_Admin")]
    FundAdmin,
    #[serde(rename = "Fund_Contact")]
    FundContact,
    #[serde(rename = "Firm_Admin")]
    FirmAdmin,
    #[serde(rename = "Firm_Billing")]
    FirmBilling,
    #[serde(rename = "Firm_Clearing")]
    FirmClearing,
    #[serde(rename = "Firm_Sales")]
    FirmSales,
    #[serde(rename = "Firm_Trading")]
    FirmTrading,
    #[serde(rename = "Firm_User")]
    FirmUser,
    #[serde(rename = "Account_Admin")]
    AccountAdmin,
    #[serde(rename = "Account_Billing")]
    AccountBilling,
    #[serde(rename = "Account_Clearing")]
    AccountClearing,
    #[serde(rename = "Account_Sales")]
    AccountSales,
    #[serde(rename = "Account_Trading")]
    AccountTrading,
    #[serde(rename = "User_Individual")]
    UserIndividual,
    #[serde(rename = "Fund_Manager")]
    FundManager,
    #[serde(rename = "Investment_Advisor")]
    InvestmentAdvisor,
    #[serde(rename = "Shf_Investmanager")]
    ShfInvestmanager,
    #[serde(rename = "Advisory_Principal")]
    AdvisoryPrincipal,
    #[serde(rename = "Advisory_Signatory")]
    AdvisorySignatory,
    #[serde(rename = "Associated_Fund")]
    AssociatedFund,
    #[serde(rename = "Primary_Contributor")]
    PrimaryContributor,
    #[serde(rename = "Administrator")]
    Administrator,
    #[serde(rename = "Contact")]
    Contact,
    #[serde(rename = "Lead_Compliance_Officer")]
    LeadComplianceOfficer,
    #[serde(rename = "Compliance_Officer")]
    ComplianceOfficer,
    #[serde(rename = "Other_Officer")]
    OtherOfficer,
    #[serde(rename = "Apply_User")]
    ApplyUser,
    #[serde(rename = "Transfer_On_Death_Legator")]
    TransferOnDeathLegator,
    #[serde(rename = "Tod_Primary_Beneficiary")]
    TodPrimaryBeneficiary,
    #[serde(rename = "Tod_Contingent_Beneficiary")]
    TodContingentBeneficiary,
    #[serde(rename = "Nominee")]
    Nominee,
    #[serde(rename = "Nominee_Guardian")]
    NomineeGuardian,
    #[serde(rename = "Ira_Decedent")]
    IraDecedent,
    #[serde(rename = "Authorized_Person")]
    AuthorizedPerson,
    #[serde(rename = "Promoter")]
    Promoter,
    #[serde(rename = "Wholetime_Director")]
    WholetimeDirector,
    #[serde(rename = "Nominee_Owner")]
    NomineeOwner,
    #[serde(rename = "Third_Party_Admin")]
    ThirdPartyAdmin,
    #[serde(rename = "Compliance_Contact")]
    ComplianceContact,
    #[serde(rename = "Trust_Controller")]
    TrustController,
    #[serde(rename = "Trust_Applicant")]
    TrustApplicant,
    #[serde(rename = "Organization_Applicant")]
    OrganizationApplicant,
    #[serde(rename = "Mm_Contact")]
    MmContact,
    #[serde(rename = "Reg_Rep")]
    RegRep,
    #[serde(rename = "Plan_Sponsor")]
    PlanSponsor,
    #[serde(rename = "Plan_Sponsor_Officer")]
    PlanSponsorOfficer,
    #[serde(rename = "Pension_Admin")]
    PensionAdmin,
    #[serde(rename = "Pension_Admin_Contact")]
    PensionAdminContact,
    #[serde(rename = "Accountant")]
    Accountant,
    #[serde(rename = "Joint_Applicant")]
    JointApplicant,
    #[serde(rename = "Custodian_Employee")]
    CustodianEmployee,
    #[serde(rename = "Successor_Custodian")]
    SuccessorCustodian,
    #[serde(rename = "Custodian")]
    Custodian,
    #[serde(rename = "Successor_Custodian_Employee")]
    SuccessorCustodianEmployee,
    #[serde(rename = "Chief_Compliance_Officer")]
    ChiefComplianceOfficer,
    #[serde(rename = "Chief_Financial_Officer")]
    ChiefFinancialOfficer,
    #[serde(rename = "Trading_Officer")]
    TradingOfficer,
    #[serde(rename = "Child")]
    Child,
    #[serde(rename = "Parent")]
    Parent,
    #[serde(rename = "Sibling")]
    Sibling,
    #[serde(rename = "Estate")]
    Estate,
    #[serde(rename = "As_Interest_May_Appear")]
    AsInterestMayAppear,
    #[serde(rename = "Ira_Present_Trust")]
    IraPresentTrust,
    #[serde(rename = "Other")]
    Other,
    #[serde(rename = "Life_Partner")]
    LifePartner,
    #[serde(rename = "Common_Law_Partner")]
    CommonLawPartner,
    #[serde(rename = "Grandchild")]
    Grandchild,
    #[serde(rename = "Charity")]
    Charity,
    #[serde(rename = "Trust_Ira")]
    TrustIra,
    #[serde(rename = "Successor_Holder")]
    SuccessorHolder,
    #[serde(rename = "Head_Of_Desk")]
    HeadOfDesk,
    #[serde(rename = "Cftc_Non_Applicant_Ocr_Contact")]
    CftcNonApplicantOcrContact,
    #[serde(rename = "Ocr_Account_Controller")]
    OcrAccountController,
    #[serde(rename = "Cftc_Applicant_Ocr_Contact")]
    CftcApplicantOcrContact,
}

impl Default for Name {
    fn default() -> Name {
        Self::AccountHolder
    }
}
