/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteLoginMessage {
    #[serde(rename = "loginMessageIds", skip_serializing_if = "Option::is_none")]
    pub login_message_ids: Option<Vec<i32>>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
}

impl CompleteLoginMessage {
    pub fn new() -> CompleteLoginMessage {
        CompleteLoginMessage {
            login_message_ids: None,
            account_id: None,
        }
    }
}
