/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateBrowserSessionRequest {
    #[serde(rename = "credential")]
    pub credential: String,
    #[serde(rename = "ip")]
    pub ip: String,
}

impl CreateBrowserSessionRequest {
    pub fn new(credential: String, ip: String) -> CreateBrowserSessionRequest {
        CreateBrowserSessionRequest {
            credential,
            ip,
        }
    }
}
