/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateSessionRequest {
    #[serde(rename = "credential")]
    pub credential: String,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<String>,
    #[serde(rename = "alternativeIps", skip_serializing_if = "Option::is_none")]
    pub alternative_ips: Option<Vec<String>>,
}

impl CreateSessionRequest {
    pub fn new(credential: String, ip: String) -> CreateSessionRequest {
        CreateSessionRequest {
            credential,
            ip,
            service: None,
            alternative_ips: None,
        }
    }
}
