/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeliveryOptions {
    /// Email option is enabled or not.
    #[serde(rename = "M", skip_serializing_if = "Option::is_none")]
    pub m: Option<i32>,
    /// Returns an array of device information.
    #[serde(rename = "E", skip_serializing_if = "Option::is_none")]
    pub e: Option<Vec<String>>,
}

impl DeliveryOptions {
    pub fn new() -> DeliveryOptions {
        DeliveryOptions { m: None, e: None }
    }
}
