/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedContractInformation {
    /// Confirms if the currency type. If trading exclusively in your base currency, “base” will be returned.
    #[serde(rename = "currencyType", skip_serializing_if = "Option::is_none")]
    pub currency_type: Option<String>,
    /// Returns the data identifier (Internal Use Only).
    #[serde(rename = "rc", skip_serializing_if = "Option::is_none")]
    pub rc: Option<i32>,
    /// Returns the accountIds being viewed and returned.
    #[serde(rename = "view", skip_serializing_if = "Option::is_none")]
    pub view: Option<Vec<String>>,
    /// Returns the total data points.
    #[serde(rename = "nd", skip_serializing_if = "Option::is_none")]
    pub nd: Option<i32>,
    /// Returns the request identifier, getPerformanceAllPeriods.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Returns an array containing accounts reviewed.
    #[serde(rename = "included", skip_serializing_if = "Option::is_none")]
    pub included: Option<Vec<String>>,
    /// Portfolio Measure. Used to indicate TWR or MWR values returned.
    #[serde(rename = "pm", skip_serializing_if = "Option::is_none")]
    pub pm: Option<String>,
}

impl DetailedContractInformation {
    pub fn new() -> DetailedContractInformation {
        DetailedContractInformation {
            currency_type: None,
            rc: None,
            view: None,
            nd: None,
            id: None,
            included: None,
            pm: None,
        }
    }
}
