/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DetailedContractInformationValue : Contains the relevant performance data for the specified accountId.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedContractInformationValue {
    /// Returns the datetime in EST of the last successful call to the /pa endpoint.
    #[serde(rename = "lastSuccessfulUpdate", skip_serializing_if = "Option::is_none")]
    pub last_successful_update: Option<String>,
    /// Returns the start date of the request range.
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    /// Returns the valid period values returned by the /pa/allperiods endpoint.
    #[serde(rename = "periods", skip_serializing_if = "Option::is_none")]
    pub periods: Option<Vec<String>>,
    /// Returns the end date of the request range.
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    /// Clarifies the base currency of the primary accountId.
    #[serde(rename = "baseCurrency", skip_serializing_if = "Option::is_none")]
    pub base_currency: Option<String>,
}

impl DetailedContractInformationValue {
    /// Contains the relevant performance data for the specified accountId.
    pub fn new() -> DetailedContractInformationValue {
        DetailedContractInformationValue {
            last_successful_update: None,
            start: None,
            periods: None,
            end: None,
            base_currency: None,
        }
    }
}
