/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisclaimerInfo {
    /// Returns the Typecode for the given disclaimer.
    #[serde(rename = "FC", skip_serializing_if = "Option::is_none")]
    pub fc: Option<String>,
    /// Returns the Disclaimer message.
    #[serde(rename = "DT", skip_serializing_if = "Option::is_none")]
    pub dt: Option<String>,
}

impl DisclaimerInfo {
    pub fn new() -> DisclaimerInfo {
        DisclaimerInfo {
            fc: None,
            dt: None,
        }
    }
}
