/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EchoResponse {
    #[serde(rename = "requestMethod")]
    pub request_method: RequestMethod,
    #[serde(rename = "securityPolicy")]
    pub security_policy: SecurityPolicy,
    #[serde(rename = "queryParameters", skip_serializing_if = "Option::is_none")]
    pub query_parameters: Option<serde_json::Value>,
}

impl EchoResponse {
    pub fn new(request_method: RequestMethod, security_policy: SecurityPolicy) -> EchoResponse {
        EchoResponse {
            request_method,
            security_policy,
            query_parameters: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RequestMethod {
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PATCH")]
    Patch,
    #[serde(rename = "PUT")]
    Put,
}

impl Default for RequestMethod {
    fn default() -> RequestMethod {
        Self::Get
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecurityPolicy {
    #[serde(rename = "HTTPS")]
    Https,
    #[serde(rename = "SIGNED_JWT")]
    SignedJwt,
    #[serde(rename = "ENCRYPTED_JWE")]
    EncryptedJwe,
}

impl Default for SecurityPolicy {
    fn default() -> SecurityPolicy {
        Self::Https
    }
}
