/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HighWaterMarkType {
    #[serde(rename = "hwm", skip_serializing_if = "Option::is_none")]
    pub hwm: Option<Box<models::HighWaterMarkConfigurationType>>,
    #[serde(rename = "previousLosses", skip_serializing_if = "Option::is_none")]
    pub previous_losses: Option<Vec<models::PreviousLossesType>>,
}

impl HighWaterMarkType {
    pub fn new() -> HighWaterMarkType {
        HighWaterMarkType {
            hwm: None,
            previous_losses: None,
        }
    }
}
