/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IserverScannerParamsScanTypeListInner {
    /// Human readable name for the scanner “type”
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    /// Value used for the market scanner request.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Returns all instruments the scanner type can be used with.
    #[serde(rename = "instruments", skip_serializing_if = "Option::is_none")]
    pub instruments: Option<Vec<String>>,
}

impl IserverScannerParamsScanTypeListInner {
    pub fn new() -> IserverScannerParamsScanTypeListInner {
        IserverScannerParamsScanTypeListInner {
            display_name: None,
            code: None,
            instruments: None,
        }
    }
}
