/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderPreviewAmount : Describes the projected costs associated with the order ticket.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderPreviewAmount {
    /// Projected cost of the order, current reference price times total quantity.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// Projected commissions and fees associated with the order.
    #[serde(rename = "commission", skip_serializing_if = "Option::is_none")]
    pub commission: Option<String>,
    /// Sum of projected cost and commission values for the order.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<String>,
}

impl OrderPreviewAmount {
    /// Describes the projected costs associated with the order ticket.
    pub fn new() -> OrderPreviewAmount {
        OrderPreviewAmount {
            amount: None,
            commission: None,
            total: None,
        }
    }
}
