/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderPreviewPosition : Describes the projected change to the account's position in the instrument.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderPreviewPosition {
    /// Current position in the instrument.
    #[serde(rename = "current", skip_serializing_if = "Option::is_none")]
    pub current: Option<String>,
    /// Difference between current and projected position sizes.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<String>,
    /// Projected position size after execution of the order.
    #[serde(rename = "after", skip_serializing_if = "Option::is_none")]
    pub after: Option<String>,
}

impl OrderPreviewPosition {
    /// Describes the projected change to the account's position in the instrument.
    pub fn new() -> OrderPreviewPosition {
        OrderPreviewPosition {
            current: None,
            change: None,
            after: None,
        }
    }
}
