/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartialCashPosition {
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f32>,
    #[serde(rename = "marginLoan", skip_serializing_if = "Option::is_none")]
    pub margin_loan: Option<bool>,
    #[serde(rename = "fullCash", skip_serializing_if = "Option::is_none")]
    pub full_cash: Option<bool>,
}

impl PartialCashPosition {
    pub fn new() -> PartialCashPosition {
        PartialCashPosition {
            amount: None,
            margin_loan: None,
            full_cash: None,
        }
    }
}
