/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryWithdrawableAmountsResponse {
    #[serde(rename = "status")]
    pub status: f64,
    #[serde(rename = "instructionSetId")]
    pub instruction_set_id: f64,
    #[serde(rename = "instructionResult", skip_serializing_if = "Option::is_none")]
    pub instruction_result: Option<Box<models::QueryWithdrawableAmountsInstructionResult>>,
}

impl QueryWithdrawableAmountsResponse {
    pub fn new(status: f64, instruction_set_id: f64) -> QueryWithdrawableAmountsResponse {
        QueryWithdrawableAmountsResponse {
            status,
            instruction_set_id,
            instruction_result: None,
        }
    }
}
