/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SourceOfIncomeType {
    #[serde(rename = "sourceType", skip_serializing_if = "Option::is_none")]
    pub source_type: Option<SourceType>,
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<i32>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl SourceOfIncomeType {
    pub fn new() -> SourceOfIncomeType {
        SourceOfIncomeType {
            source_type: None,
            percentage: None,
            description: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SourceType {
    #[serde(rename = "CONSULTING")]
    Consulting,
    #[serde(rename = "DISABILITY")]
    Disability,
    #[serde(rename = "INHERITANCE")]
    Inheritance,
    #[serde(rename = "INTEREST")]
    Interest,
    #[serde(rename = "REALESTATE")]
    Realestate,
    #[serde(rename = "RENTAL")]
    Rental,
    #[serde(rename = "SEVERANCE")]
    Severance,
    #[serde(rename = "SPOUSE")]
    Spouse,
    #[serde(rename = "TRADINGANDINVESTMENTS")]
    Tradingandinvestments,
    #[serde(rename = "PENSIONANDSOCIALSECURITY")]
    Pensionandsocialsecurity,
    #[serde(rename = "UNEMPLOYMENT")]
    Unemployment,
    #[serde(rename = "OTHER")]
    Other,
}

impl Default for SourceType {
    fn default() -> SourceType {
        Self::Consulting
    }
}
