/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SummaryOfAccountBalancesResponseCommodities : Contains Commodity-specific balance details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryOfAccountBalancesResponseCommodities {
    /// The basis for determining the price of the assets in your account.
    #[serde(rename = "net_liquidation", skip_serializing_if = "Option::is_none")]
    pub net_liquidation: Option<String>,
    /// * `Cash Accounts` Settled cash  * `Margin Accounts` Total cash value + stock value + bond value + fund value + European & Asian options value.
    #[serde(rename = "equity_with_loan", skip_serializing_if = "Option::is_none")]
    pub equity_with_loan: Option<String>,
    /// Total cash balance in the account
    #[serde(rename = "cash", skip_serializing_if = "Option::is_none")]
    pub cash: Option<String>,
    /// Total Month-to-date interest.
    #[serde(rename = "MTD Interest", skip_serializing_if = "Option::is_none")]
    pub mtd_interest: Option<String>,
    /// Any pending charges for the IBKR debit account.
    #[serde(rename = "Pndng Dbt Crd Chrgs", skip_serializing_if = "Option::is_none")]
    pub pndng_dbt_crd_chrgs: Option<String>,
}

impl SummaryOfAccountBalancesResponseCommodities {
    /// Contains Commodity-specific balance details.
    pub fn new() -> SummaryOfAccountBalancesResponseCommodities {
        SummaryOfAccountBalancesResponseCommodities {
            net_liquidation: None,
            equity_with_loan: None,
            cash: None,
            mtd_interest: None,
            pndng_dbt_crd_chrgs: None,
        }
    }
}
