/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SummaryOfAccountMarginResponse {
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<Box<models::SummaryOfAccountMarginResponseTotal>>,
    #[serde(rename = "commodities", skip_serializing_if = "Option::is_none")]
    pub commodities: Option<Box<models::SummaryOfAccountMarginResponseTotal>>,
    #[serde(rename = "securities", skip_serializing_if = "Option::is_none")]
    pub securities: Option<Box<models::SummaryOfAccountMarginResponseSecurities>>,
}

impl SummaryOfAccountMarginResponse {
    pub fn new() -> SummaryOfAccountMarginResponse {
        SummaryOfAccountMarginResponse {
            total: None,
            commodities: None,
            securities: None,
        }
    }
}
