/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TaxFormType {
    #[serde(rename = "isForm", skip_serializing_if = "Option::is_none")]
    pub is_form: Option<bool>,
    #[serde(rename = "taxFormName", skip_serializing_if = "Option::is_none")]
    pub tax_form_name: Option<String>,
    /// available tax form formats
    #[serde(rename = "formats", skip_serializing_if = "Option::is_none")]
    pub formats: Option<Vec<String>>,
}

impl TaxFormType {
    pub fn new() -> TaxFormType {
        TaxFormType {
            is_form: None,
            tax_form_name: None,
            formats: None,
        }
    }
}
