/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TradingInstrument {
    TradingInstrumentOneOf(Box<models::TradingInstrumentOneOf>),
    TradingInstrumentOneOf1(Box<models::TradingInstrumentOneOf1>),
}

impl Default for TradingInstrument {
    fn default() -> Self {
        Self::TradingInstrumentOneOf(Default::default())
    }
}
