/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrusteesType {
    #[serde(rename = "individuals", skip_serializing_if = "Option::is_none")]
    pub individuals: Option<Vec<models::TrusteeIndividual>>,
    #[serde(rename = "entities", skip_serializing_if = "Option::is_none")]
    pub entities: Option<Vec<models::TrusteeEntityType>>,
}

impl TrusteesType {
    pub fn new() -> TrusteesType {
        TrusteesType {
            individuals: None,
            entities: None,
        }
    }
}
