/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateTaxForm {
    #[serde(rename = "localTaxForms", skip_serializing_if = "Option::is_none")]
    pub local_tax_forms: Option<Vec<models::LocalTaxForm>>,
    #[serde(rename = "w8Ben", skip_serializing_if = "Option::is_none")]
    pub w8_ben: Option<Box<models::FormW8Ben>>,
    #[serde(rename = "w8BenE", skip_serializing_if = "Option::is_none")]
    pub w8_ben_e: Option<Box<models::FormW8Bene>>,
    #[serde(rename = "w9", skip_serializing_if = "Option::is_none")]
    pub w9: Option<Box<models::FormW9>>,
    #[serde(rename = "translation", skip_serializing_if = "Option::is_none")]
    pub translation: Option<bool>,
    #[serde(rename = "inputLanguage", skip_serializing_if = "Option::is_none")]
    pub input_language: Option<InputLanguage>,
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "documents", skip_serializing_if = "Option::is_none")]
    pub documents: Option<Vec<models::Document>>,
    #[serde(rename = "entityId", skip_serializing_if = "Option::is_none")]
    pub entity_id: Option<String>,
    #[serde(rename = "externalId", skip_serializing_if = "Option::is_none")]
    pub external_id: Option<String>,
}

impl UpdateTaxForm {
    pub fn new() -> UpdateTaxForm {
        UpdateTaxForm {
            local_tax_forms: None,
            w8_ben: None,
            w8_ben_e: None,
            w9: None,
            translation: None,
            input_language: None,
            account_id: None,
            documents: None,
            entity_id: None,
            external_id: None,
        }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum InputLanguage {
    #[serde(rename = "en")]
    En,
    #[serde(rename = "zh-Hans")]
    ZhHans,
    #[serde(rename = "ja")]
    Ja,
    #[serde(rename = "ru")]
    Ru,
    #[serde(rename = "fr")]
    Fr,
    #[serde(rename = "pt")]
    Pt,
    #[serde(rename = "es")]
    Es,
    #[serde(rename = "it")]
    It,
    #[serde(rename = "ar-AE")]
    ArAe,
    #[serde(rename = "de")]
    De,
    #[serde(rename = "he-IL")]
    HeIl,
    #[serde(rename = "hu")]
    Hu,
}

impl Default for InputLanguage {
    fn default() -> InputLanguage {
        Self::En
    }
}
