/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateExternalId {
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    #[serde(rename = "newExternalId", skip_serializing_if = "Option::is_none")]
    pub new_external_id: Option<String>,
}

impl UpdateExternalId {
    pub fn new() -> UpdateExternalId {
        UpdateExternalId {
            account_id: None,
            new_external_id: None,
        }
    }
}
