/*
 * IB REST API
 *
 * The IB REST API reference documentation
 *
 * The version of the OpenAPI document: 2.15.0
 * Contact: api@interactivebrokers.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WatchlistDeleteSuccessData {
    /// Watchlist ID of the deleted watchlist.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<String>,
}

impl WatchlistDeleteSuccessData {
    pub fn new() -> WatchlistDeleteSuccessData {
        WatchlistDeleteSuccessData {
            deleted: None,
        }
    }
}
