# -------------------------------------------------------------------------------------------------
#  VWAP Wave Trading System - Base Setup
# -------------------------------------------------------------------------------------------------
"""
Abstract base class for all trading setups.

Defines the common interface and signal structure for setups.
"""

from __future__ import annotations

from abc import ABC
from abc import abstractmethod
from dataclasses import dataclass
from dataclasses import field
from enum import Enum
from typing import Any
from typing import Dict

from nautilus_trader.model.data import Bar

from vwap_wave.analysis.regime_classifier import RegimeState


class TradeDirection(Enum):
    """Direction of the trade."""

    LONG = "long"
    SHORT = "short"


@dataclass
class SetupSignal:
    """Trading signal generated by a setup."""

    valid: bool
    setup_type: str
    direction: TradeDirection
    entry_price: float
    stop_price: float
    target_price: float
    confidence: float
    metadata: Dict[str, Any] = field(default_factory=dict)

    @classmethod
    def no_signal(cls) -> SetupSignal:
        """Create a null signal indicating no trade opportunity."""
        return cls(
            valid=False,
            setup_type="",
            direction=TradeDirection.LONG,
            entry_price=0.0,
            stop_price=0.0,
            target_price=0.0,
            confidence=0.0,
            metadata={},
        )

    @property
    def risk_reward_ratio(self) -> float:
        """Calculate the risk-reward ratio for this signal."""
        if not self.valid:
            return 0.0

        risk = abs(self.entry_price - self.stop_price)
        if risk == 0:
            return 0.0

        reward = abs(self.target_price - self.entry_price)
        return reward / risk

    @property
    def risk_amount(self) -> float:
        """Calculate the risk amount (distance to stop)."""
        return abs(self.entry_price - self.stop_price)


class BaseSetup(ABC):
    """
    Abstract base class for trading setups.

    All setups must implement the evaluate() and is_eligible() methods.
    """

    def __init__(self, name: str, config):
        """
        Initialize the base setup.

        Parameters
        ----------
        name : str
            The setup name identifier.
        config : VWAPWaveConfig
            The master configuration.

        """
        self.name = name
        self.config = config

    @abstractmethod
    def evaluate(self, regime_state: RegimeState, bar: Bar, atr: float) -> SetupSignal:
        """
        Evaluate if setup conditions are met.

        Parameters
        ----------
        regime_state : RegimeState
            Current market regime classification.
        bar : Bar
            Current bar data.
        atr : float
            Current ATR value.

        Returns
        -------
        SetupSignal
            Signal with trade parameters if valid, otherwise no_signal.

        """
        pass

    @abstractmethod
    def is_eligible(self, regime_state: RegimeState) -> bool:
        """
        Check if setup is eligible given current regime.

        Parameters
        ----------
        regime_state : RegimeState
            Current market regime classification.

        Returns
        -------
        bool
            True if setup is eligible in current regime.

        """
        pass

    def reset(self) -> None:
        """Reset any internal state. Override in subclass if needed."""
        pass
