// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Actor plug point.
//!
//! Plug-in authors implement [`PluginActor`] on their struct; the generated
//! [`ActorVTable`] adapts that trait to the C-ABI boundary so the host's
//! `DataActor`-shaped engine can dispatch callbacks into the cdylib.
//!
//! # Boundary shape
//!
//! Data-bearing callbacks cross the boundary as `*const T` borrowed
//! pointers into the host's already-`#[repr(C)]` model types. The host
//! keeps the value alive for the duration of the call; the plug-in's
//! thunk dereferences once and hands an `&T` to the trait method. No
//! serialisation, no allocation per event.
//!
//! Lifecycle callbacks (`on_start`, `on_stop`, ...) carry no payload.
//!
//! # Scope (v1)
//!
//! Phase 1 covers the lifecycle callbacks plus the data callbacks whose
//! payload types are `#[repr(C)]`-clean end-to-end:
//!
//! - Lifecycle: `start`, `stop`, `resume`, `reset`, `dispose`, `degrade`, `fault`
//! - Market data: quotes, trades, bars, mark/index/funding prices,
//!   instrument status, instrument close
//! - Order events: filled, canceled
//! - Other: signal, time event
//!
//! Deferred: `on_book_deltas` (non-`#[repr(C)]` envelope, see README),
//! `on_book` (stateful), `on_instrument` (non-`#[repr(C)]` enum),
//! `on_data` (CustomData routing through actors), DeFi pool/block events,
//! historical-data callbacks.

#![allow(unsafe_code)]

use std::marker::PhantomData;

use nautilus_common::{signal::Signal, timer::TimeEvent};
use nautilus_model::{
    data::{
        Bar, FundingRateUpdate, IndexPriceUpdate, InstrumentClose, InstrumentStatus,
        MarkPriceUpdate, QuoteTick, TradeTick,
    },
    events::{OrderCanceled, OrderFilled},
};

use crate::{
    boundary::{BorrowedStr, PluginError, PluginErrorCode, PluginResult},
    host::{HostContext, HostVTable},
    panic::{guard, guard_infallible},
};

/// Opaque handle to a plug-in actor instance owned by the cdylib.
///
/// The host never deref's this pointer; it only passes it back to the vtable
/// through the lifecycle and data callbacks until releasing it via `drop`.
#[repr(C)]
pub struct PluginActorHandle {
    _opaque: [u8; 0],
}

/// Function table for a single plug-in actor type.
///
/// One static vtable per concrete type, generated by
/// [`nautilus_plugin!`](crate::nautilus_plugin) via the `Tag<T>` pattern that
/// also powers [`custom_data_vtable`](crate::surfaces::custom_data::custom_data_vtable).
///
/// Every callback that returns [`PluginResult<()>`] runs inside
/// [`crate::panic::guard`]. The infallible `create`/`drop` callbacks run
/// inside [`crate::panic::guard_infallible`], which aborts the host on
/// panic since their signatures cannot carry an error.
#[repr(C)]
pub struct ActorVTable {
    /// Constructs a fresh actor instance bound to the supplied host vtable
    /// and instance context, and returns a non-null handle.
    pub create: unsafe extern "C" fn(
        host: *const HostVTable,
        ctx: *const HostContext,
    ) -> *mut PluginActorHandle,

    /// Drops the actor instance and releases all of its resources.
    pub drop_handle: unsafe extern "C" fn(handle: *mut PluginActorHandle),

    /// Returns the canonical type name for this actor.
    pub type_name: unsafe extern "C" fn() -> BorrowedStr<'static>,

    pub on_start: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_stop: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_resume: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_reset: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_dispose: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_degrade: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,
    pub on_fault: unsafe extern "C" fn(handle: *mut PluginActorHandle) -> PluginResult<()>,

    pub on_time_event: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        event: *const TimeEvent,
    ) -> PluginResult<()>,

    pub on_quote: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        quote: *const QuoteTick,
    ) -> PluginResult<()>,
    pub on_trade: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        trade: *const TradeTick,
    ) -> PluginResult<()>,
    pub on_bar:
        unsafe extern "C" fn(handle: *mut PluginActorHandle, bar: *const Bar) -> PluginResult<()>,
    pub on_mark_price: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        mark_price: *const MarkPriceUpdate,
    ) -> PluginResult<()>,
    pub on_index_price: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        index_price: *const IndexPriceUpdate,
    ) -> PluginResult<()>,
    pub on_funding_rate: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        funding_rate: *const FundingRateUpdate,
    ) -> PluginResult<()>,
    pub on_instrument_status: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        status: *const InstrumentStatus,
    ) -> PluginResult<()>,
    pub on_instrument_close: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        close: *const InstrumentClose,
    ) -> PluginResult<()>,

    pub on_order_filled: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        event: *const OrderFilled,
    ) -> PluginResult<()>,
    pub on_order_canceled: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        event: *const OrderCanceled,
    ) -> PluginResult<()>,

    pub on_signal: unsafe extern "C" fn(
        handle: *mut PluginActorHandle,
        signal: *const Signal,
    ) -> PluginResult<()>,
}

/// Author-facing trait for a plug-in actor.
///
/// Every callback has a no-op default; authors override the ones they care
/// about. Callbacks receive borrowed references to host-owned values; the
/// references are only valid for the duration of the call.
pub trait PluginActor: 'static + Send + Sized {
    /// Canonical type name. Must be unique across a Nautilus deployment.
    const TYPE_NAME: &'static str;

    /// Constructs a fresh actor instance bound to the supplied host vtable
    /// and instance context.
    fn new(host: *const HostVTable, ctx: *const HostContext) -> Self;

    #[allow(unused_variables)]
    fn on_start(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_stop(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_resume(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_reset(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_dispose(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_degrade(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_fault(&mut self) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_time_event(&mut self, event: &TimeEvent) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_quote(&mut self, quote: &QuoteTick) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_trade(&mut self, trade: &TradeTick) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_bar(&mut self, bar: &Bar) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_mark_price(&mut self, mark_price: &MarkPriceUpdate) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_index_price(&mut self, index_price: &IndexPriceUpdate) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_funding_rate(&mut self, funding_rate: &FundingRateUpdate) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_instrument_status(&mut self, status: &InstrumentStatus) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_instrument_close(&mut self, close: &InstrumentClose) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_order_filled(&mut self, event: &OrderFilled) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_order_canceled(&mut self, event: &OrderCanceled) -> anyhow::Result<()> {
        Ok(())
    }

    #[allow(unused_variables)]
    fn on_signal(&mut self, signal: &Signal) -> anyhow::Result<()> {
        Ok(())
    }
}

/// Returns a `*const ActorVTable` for the given [`PluginActor`] type.
///
/// One static vtable per monomorphisation via the `Tag<T>`-shaped pattern
/// proven by [`custom_data_vtable`](crate::surfaces::custom_data::custom_data_vtable).
#[must_use]
pub fn actor_vtable<T>() -> *const ActorVTable
where
    T: PluginActor,
{
    &VTableTag::<T>::VTABLE
}

struct VTableTag<T>(PhantomData<T>);

impl<T> VTableTag<T>
where
    T: PluginActor,
{
    const VTABLE: ActorVTable = ActorVTable {
        create: create_thunk::<T>,
        drop_handle: drop_handle_thunk::<T>,
        type_name: type_name_thunk::<T>,
        on_start: on_start_thunk::<T>,
        on_stop: on_stop_thunk::<T>,
        on_resume: on_resume_thunk::<T>,
        on_reset: on_reset_thunk::<T>,
        on_dispose: on_dispose_thunk::<T>,
        on_degrade: on_degrade_thunk::<T>,
        on_fault: on_fault_thunk::<T>,
        on_time_event: on_time_event_thunk::<T>,
        on_quote: on_quote_thunk::<T>,
        on_trade: on_trade_thunk::<T>,
        on_bar: on_bar_thunk::<T>,
        on_mark_price: on_mark_price_thunk::<T>,
        on_index_price: on_index_price_thunk::<T>,
        on_funding_rate: on_funding_rate_thunk::<T>,
        on_instrument_status: on_instrument_status_thunk::<T>,
        on_instrument_close: on_instrument_close_thunk::<T>,
        on_order_filled: on_order_filled_thunk::<T>,
        on_order_canceled: on_order_canceled_thunk::<T>,
        on_signal: on_signal_thunk::<T>,
    };
}

unsafe extern "C" fn create_thunk<T: PluginActor>(
    host: *const HostVTable,
    ctx: *const HostContext,
) -> *mut PluginActorHandle {
    guard_infallible("actor::create", || {
        Box::into_raw(Box::new(T::new(host, ctx))).cast::<PluginActorHandle>()
    })
}

unsafe extern "C" fn drop_handle_thunk<T: PluginActor>(handle: *mut PluginActorHandle) {
    if handle.is_null() {
        return;
    }
    guard_infallible("actor::drop", || {
        // SAFETY: handle was allocated via `Box::into_raw(Box::new(T))`.
        unsafe {
            drop(Box::from_raw(handle.cast::<T>()));
        }
    });
}

unsafe extern "C" fn type_name_thunk<T: PluginActor>() -> BorrowedStr<'static> {
    BorrowedStr::from_str(T::TYPE_NAME)
}

fn handle_as_mut<'a, T: PluginActor>(handle: *mut PluginActorHandle) -> &'a mut T {
    // SAFETY: handle is non-null and originates from a `Box::into_raw` of a
    // `T`. The host promises exclusive access while a callback is running.
    unsafe { &mut *handle.cast::<T>() }
}

fn ok_or_err<E: ::core::fmt::Display>(r: Result<(), E>) -> Result<(), PluginError> {
    r.map_err(|e| PluginError::new(PluginErrorCode::Generic, e.to_string()))
}

macro_rules! lifecycle_thunk {
    ($name:ident, $method:ident) => {
        unsafe extern "C" fn $name<T: PluginActor>(
            handle: *mut PluginActorHandle,
        ) -> PluginResult<()> {
            guard(|| {
                let actor = handle_as_mut::<T>(handle);
                ok_or_err(actor.$method())
            })
        }
    };
}

lifecycle_thunk!(on_start_thunk, on_start);
lifecycle_thunk!(on_stop_thunk, on_stop);
lifecycle_thunk!(on_resume_thunk, on_resume);
lifecycle_thunk!(on_reset_thunk, on_reset);
lifecycle_thunk!(on_dispose_thunk, on_dispose);
lifecycle_thunk!(on_degrade_thunk, on_degrade);
lifecycle_thunk!(on_fault_thunk, on_fault);

macro_rules! event_thunk {
    ($name:ident, $method:ident, $ty:ty) => {
        unsafe extern "C" fn $name<T: PluginActor>(
            handle: *mut PluginActorHandle,
            value: *const $ty,
        ) -> PluginResult<()> {
            guard(|| {
                // SAFETY: host keeps `value` live for the duration of the call;
                // the plug-in only borrows it for the trait-method invocation.
                let v = unsafe { &*value };
                let actor = handle_as_mut::<T>(handle);
                ok_or_err(actor.$method(v))
            })
        }
    };
}

event_thunk!(on_time_event_thunk, on_time_event, TimeEvent);
event_thunk!(on_quote_thunk, on_quote, QuoteTick);
event_thunk!(on_trade_thunk, on_trade, TradeTick);
event_thunk!(on_bar_thunk, on_bar, Bar);
event_thunk!(on_mark_price_thunk, on_mark_price, MarkPriceUpdate);
event_thunk!(on_index_price_thunk, on_index_price, IndexPriceUpdate);
event_thunk!(on_funding_rate_thunk, on_funding_rate, FundingRateUpdate);
event_thunk!(
    on_instrument_status_thunk,
    on_instrument_status,
    InstrumentStatus
);
event_thunk!(
    on_instrument_close_thunk,
    on_instrument_close,
    InstrumentClose
);
event_thunk!(on_order_filled_thunk, on_order_filled, OrderFilled);
event_thunk!(on_order_canceled_thunk, on_order_canceled, OrderCanceled);
event_thunk!(on_signal_thunk, on_signal, Signal);
