// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

use std::collections::BTreeSet;

use rstest::rstest;

const DATA_ACTOR_SOURCE: &str = include_str!("../../common/src/actor/data_actor.rs");
const DATA_ACTOR_CORE_SOURCE: &str = include_str!("../../common/src/actor/data_actor.rs");
const STRATEGY_CORE_SOURCE: &str = include_str!("../../trading/src/strategy/core.rs");
const STRATEGY_SOURCE: &str = include_str!("../../trading/src/strategy/mod.rs");
const HOST_SOURCE: &str = include_str!("../src/host.rs");
const PLUGIN_ACTOR_SOURCE: &str = include_str!("../src/surfaces/actor.rs");
const PLUGIN_STRATEGY_SOURCE: &str = include_str!("../src/surfaces/strategy.rs");

const PLUGIN_ACTOR_DEFERRED_CALLBACKS: &[&str] = &[
    // State snapshots have no cdylib persistence contract in v1
    "on_save",
    "on_load",
    // DeFi callbacks are outside the v1 actor surface
    "on_block",
    "on_pool",
    "on_pool_swap",
    "on_pool_liquidity_update",
    "on_pool_fee_collect",
    "on_pool_flash",
    // Generic historical data stays out of the vtable; registered plug-in
    // custom data reaches `on_data`.
    "on_historical_data",
];

const PLUGIN_STRATEGY_DEFERRED_CALLBACKS: &[&str] = &[
    // State snapshots have no cdylib persistence contract in v1
    "on_save",
    "on_load",
    // DeFi callbacks are outside the v1 strategy surface
    "on_block",
    "on_pool",
    "on_pool_swap",
    "on_pool_liquidity_update",
    "on_pool_fee_collect",
    "on_pool_flash",
    // Generic historical data stays out of the vtable; registered plug-in
    // custom data reaches `on_data`.
    "on_historical_data",
    // Aggregate order and position callbacks need plug-in-safe event handles;
    // typed lifecycle callbacks already cross the boundary.
    "on_order_event",
    "on_position_event",
];

const PLUGIN_STRATEGY_DEFERRED_EXECUTION_METHODS: &[&str] = &[
    // Core strategy/execution paths support this command; the v1 plug-in ABI
    // slot stays deferred while the plug-in surface is in flux.
    "modify_orders",
    // Local state methods mutate host cache state before commands leave the
    // strategy; the host adapter, not the plug-in, is the authority for
    // staging these transitions in v1.
    "mark_order_pending_update",
    "mark_order_pending_cancel",
    "generate_order_pending_update",
    "generate_order_pending_cancel",
];

const PLUGIN_STRATEGY_HOST_OWNED_METHODS: &[&str] = &[
    // StrategyCore access is generated by nautilus_strategy! for in-process strategies
    "core",
    "core_mut",
    // External order claims are reconciliation policy, not a v1 plug-in command
    "external_order_claims",
    // Facade accessors wrap host-owned order factory and portfolio state
    "order",
    "portfolio",
    // The host owns event routing into plug-in callback slots
    "handle_order_event",
    "handle_position_event",
    // Market-exit and GTD workflows stay inside the host strategy runtime in v1
    "post_market_exit",
    "is_exiting",
    "market_exit",
    "check_market_exit",
    "finalize_market_exit",
    "cancel_market_exit",
    "stop",
    "deny_order",
    "deny_order_list",
    "set_gtd_expiry",
    "cancel_gtd_expiry",
    "has_gtd_expiry_timer",
    "expire_gtd_order",
    "reactivate_gtd_timers",
];

const PLUGIN_DATA_ACTOR_CORE_BRIDGED_METHODS: &[(&str, &str)] = &[
    ("state", "component_state"),
    ("trader_id", "trader_id"),
    ("timestamp_ns", "clock_now_ns"),
    ("subscribe_quotes", "subscribe_quotes"),
    ("unsubscribe_quotes", "unsubscribe_quotes"),
    ("subscribe_trades", "subscribe_trades"),
    ("unsubscribe_trades", "unsubscribe_trades"),
    ("subscribe_bars", "subscribe_bars"),
    ("unsubscribe_bars", "unsubscribe_bars"),
    ("subscribe_book_deltas", "subscribe_book_deltas"),
    ("unsubscribe_book_deltas", "unsubscribe_book_deltas"),
    ("subscribe_book_at_interval", "subscribe_book_at_interval"),
    (
        "unsubscribe_book_at_interval",
        "unsubscribe_book_at_interval",
    ),
];

const PLUGIN_DATA_ACTOR_CORE_DEFERRED_METHODS: &[&str] = &[
    // Actor identity needs an actor_id slot; session 1 exposes strategy_id only
    "actor_id",
    // Lifecycle and publishing slots are scheduled for a later workstream
    "register_warning_event",
    "deregister_warning_event",
    "shutdown_system",
    "publish_data",
    "publish_signal",
    "add_synthetic",
    "update_synthetic",
    // Subscription completion lands after the initial identity and factory-id slots
    "subscribe_data",
    "subscribe_signal",
    "subscribe_instruments",
    "subscribe_instrument",
    "subscribe_mark_prices",
    "subscribe_index_prices",
    "subscribe_funding_rates",
    "subscribe_option_greeks",
    "subscribe_instrument_status",
    "subscribe_instrument_close",
    "subscribe_option_chain",
    "subscribe_order_fills",
    "subscribe_order_cancels",
    "unsubscribe_data",
    "unsubscribe_signal",
    "unsubscribe_instruments",
    "unsubscribe_instrument",
    "unsubscribe_mark_prices",
    "unsubscribe_index_prices",
    "unsubscribe_funding_rates",
    "unsubscribe_option_greeks",
    "unsubscribe_instrument_status",
    "unsubscribe_instrument_close",
    "unsubscribe_option_chain",
    "unsubscribe_order_fills",
    "unsubscribe_order_cancels",
    // Historical request slots are scheduled for a later workstream
    "request_data",
    "request_instrument",
    "request_instruments",
    "request_book_snapshot",
    "request_book_deltas",
    "request_book_depth",
    "request_quotes",
    "request_trades",
    "request_bars",
    "request_funding_rates",
    // Indicator handles need a plug-in-safe registration ABI
    "registered_indicators",
    "indicators_initialized",
    "register_indicator_for_quote_ticks",
    "register_indicator_for_trade_ticks",
    "register_indicator_for_bars",
];

const PLUGIN_DATA_ACTOR_CORE_HOST_OWNED_METHODS: &[&str] = &[
    // Construction and registration stay host-owned
    "new",
    "mem_address",
    "register",
    "is_registered",
];

const PLUGIN_STRATEGY_CORE_BRIDGED_METHODS: &[(&str, &str)] = &[("strategy_id", "strategy_id")];

const PLUGIN_STRATEGY_CORE_DEFERRED_METHODS: &[&str] = &[];

const PLUGIN_STRATEGY_CORE_HOST_OWNED_METHODS: &[&str] = &[
    // Construction, config reads, and registration stay host-owned
    "new",
    "config",
    "change_id",
    "change_order_id_tag",
    "order_id_tag",
    "register",
    // Direct access to host-owned runtime state does not cross the boundary
    "order",
    // Market-exit state remains inside the host runtime
    "reset_market_exit_state",
];

#[rstest]
fn plugin_actor_surface_accounts_for_every_data_actor_callback() {
    let data_actor_callbacks = data_actor_callback_names();
    let plugin_actor_callbacks = plugin_actor_callback_names();
    let deferred_callbacks = PLUGIN_ACTOR_DEFERRED_CALLBACKS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();

    let accounted_callbacks = plugin_actor_callbacks
        .union(&deferred_callbacks)
        .cloned()
        .collect::<BTreeSet<_>>();
    let missing_callbacks = data_actor_callbacks
        .difference(&accounted_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_callbacks.is_empty(),
        "DataActor callbacks must be added to PluginActor or explicitly deferred: {missing_callbacks:?}",
    );

    let stale_deferred_callbacks = deferred_callbacks
        .difference(&data_actor_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_deferred_callbacks.is_empty(),
        "Deferred plug-in actor callbacks are no longer DataActor callbacks: {stale_deferred_callbacks:?}",
    );

    let implemented_deferred_callbacks = deferred_callbacks
        .intersection(&plugin_actor_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        implemented_deferred_callbacks.is_empty(),
        "PluginActor now supports callbacks still listed as deferred: {implemented_deferred_callbacks:?}",
    );
}

#[rstest]
fn plugin_actor_trait_callbacks_match_vtable_slots() {
    let plugin_actor_callbacks = plugin_actor_callback_names();
    let vtable_callbacks = actor_vtable_callback_names();

    let missing_vtable_slots = plugin_actor_callbacks
        .difference(&vtable_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_vtable_slots.is_empty(),
        "PluginActor callbacks must have ActorVTable slots: {missing_vtable_slots:?}",
    );

    let missing_trait_callbacks = vtable_callbacks
        .difference(&plugin_actor_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_trait_callbacks.is_empty(),
        "ActorVTable callback slots must have PluginActor methods: {missing_trait_callbacks:?}",
    );
}

#[rstest]
fn plugin_strategy_surface_accounts_for_every_upstream_callback() {
    let mut upstream_callbacks = data_actor_callback_names();
    upstream_callbacks.extend(strategy_callback_names());
    let plugin_strategy_callbacks = plugin_strategy_callback_names();
    let deferred_callbacks = PLUGIN_STRATEGY_DEFERRED_CALLBACKS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();

    let accounted_callbacks = plugin_strategy_callbacks
        .union(&deferred_callbacks)
        .cloned()
        .collect::<BTreeSet<_>>();
    let missing_callbacks = upstream_callbacks
        .difference(&accounted_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_callbacks.is_empty(),
        "DataActor or Strategy callbacks must be added to PluginStrategy or explicitly deferred: {missing_callbacks:?}",
    );

    let stale_deferred_callbacks = deferred_callbacks
        .difference(&upstream_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_deferred_callbacks.is_empty(),
        "Deferred plug-in strategy callbacks are no longer DataActor or Strategy callbacks: {stale_deferred_callbacks:?}",
    );

    let implemented_deferred_callbacks = deferred_callbacks
        .intersection(&plugin_strategy_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        implemented_deferred_callbacks.is_empty(),
        "PluginStrategy now supports callbacks still listed as deferred: {implemented_deferred_callbacks:?}",
    );
}

#[rstest]
fn plugin_strategy_trait_callbacks_match_vtable_slots() {
    let plugin_strategy_callbacks = plugin_strategy_callback_names();
    let vtable_callbacks = strategy_vtable_callback_names();

    let missing_vtable_slots = plugin_strategy_callbacks
        .difference(&vtable_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_vtable_slots.is_empty(),
        "PluginStrategy callbacks must have StrategyVTable slots: {missing_vtable_slots:?}",
    );

    let missing_trait_callbacks = vtable_callbacks
        .difference(&plugin_strategy_callbacks)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_trait_callbacks.is_empty(),
        "StrategyVTable callback slots must have PluginStrategy methods: {missing_trait_callbacks:?}",
    );
}

#[rstest]
fn plugin_strategy_execution_surface_accounts_for_every_strategy_method() {
    let strategy_execution_methods = strategy_execution_method_names();
    let host_vtable_methods = host_vtable_field_names();
    let deferred_methods = PLUGIN_STRATEGY_DEFERRED_EXECUTION_METHODS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();

    let accounted_methods = host_vtable_methods
        .union(&deferred_methods)
        .cloned()
        .collect::<BTreeSet<_>>();
    let missing_methods = strategy_execution_methods
        .difference(&accounted_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        missing_methods.is_empty(),
        "Strategy execution methods must be added to HostVTable or explicitly deferred: {missing_methods:?}",
    );

    let stale_deferred_methods = deferred_methods
        .difference(&strategy_execution_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_deferred_methods.is_empty(),
        "Deferred plug-in strategy execution methods are no longer Strategy methods: {stale_deferred_methods:?}",
    );

    let implemented_deferred_methods = deferred_methods
        .intersection(&host_vtable_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        implemented_deferred_methods.is_empty(),
        "HostVTable now supports strategy execution methods still listed as deferred: {implemented_deferred_methods:?}",
    );
}

#[rstest]
fn plugin_strategy_surface_classifies_every_strategy_method() {
    let strategy_methods = strategy_method_names();
    let host_vtable_methods = host_vtable_field_names();
    let plugin_strategy_callbacks = plugin_strategy_callback_names();
    let deferred_callbacks = PLUGIN_STRATEGY_DEFERRED_CALLBACKS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let deferred_execution_methods = PLUGIN_STRATEGY_DEFERRED_EXECUTION_METHODS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();
    let host_owned_methods = PLUGIN_STRATEGY_HOST_OWNED_METHODS
        .iter()
        .map(|name| (*name).to_string())
        .collect::<BTreeSet<_>>();

    let mut classified_methods = host_vtable_methods
        .union(&plugin_strategy_callbacks)
        .cloned()
        .collect::<BTreeSet<_>>();
    classified_methods.extend(deferred_callbacks);
    classified_methods.extend(deferred_execution_methods);
    classified_methods.extend(host_owned_methods.iter().cloned());

    let unclassified_methods = strategy_methods
        .difference(&classified_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        unclassified_methods.is_empty(),
        "Strategy methods must be backed by the plug-in surface or explicitly classified: {unclassified_methods:?}",
    );

    let stale_host_owned_methods = host_owned_methods
        .difference(&strategy_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_host_owned_methods.is_empty(),
        "Host-owned plug-in strategy methods are no longer Strategy methods: {stale_host_owned_methods:?}",
    );
}

#[rstest]
fn plugin_data_actor_core_surface_classifies_every_public_method() {
    let data_actor_core_methods = data_actor_core_public_method_names();
    assert_core_surface_classification(
        "DataActorCore",
        &data_actor_core_methods,
        PLUGIN_DATA_ACTOR_CORE_BRIDGED_METHODS,
        PLUGIN_DATA_ACTOR_CORE_DEFERRED_METHODS,
        PLUGIN_DATA_ACTOR_CORE_HOST_OWNED_METHODS,
    );
}

#[rstest]
fn plugin_strategy_core_surface_classifies_every_public_method() {
    let strategy_core_methods = strategy_core_public_method_names();
    assert_core_surface_classification(
        "StrategyCore",
        &strategy_core_methods,
        PLUGIN_STRATEGY_CORE_BRIDGED_METHODS,
        PLUGIN_STRATEGY_CORE_DEFERRED_METHODS,
        PLUGIN_STRATEGY_CORE_HOST_OWNED_METHODS,
    );
}

fn assert_core_surface_classification(
    surface: &str,
    upstream_methods: &BTreeSet<String>,
    bridged_methods: &[(&str, &str)],
    deferred_methods: &[&str],
    host_owned_methods: &[&str],
) {
    let host_vtable_methods = host_vtable_field_names();
    let bridged_method_names = bridged_methods
        .iter()
        .map(|(method, _)| (*method).to_string())
        .collect::<BTreeSet<_>>();
    let deferred_method_names = deferred_methods
        .iter()
        .map(|method| (*method).to_string())
        .collect::<BTreeSet<_>>();
    let host_owned_method_names = host_owned_methods
        .iter()
        .map(|method| (*method).to_string())
        .collect::<BTreeSet<_>>();

    let mut classified_methods = bridged_method_names.clone();
    classified_methods.extend(deferred_method_names.iter().cloned());
    classified_methods.extend(host_owned_method_names.iter().cloned());

    let unclassified_methods = upstream_methods
        .difference(&classified_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        unclassified_methods.is_empty(),
        "{surface} public methods must be bridged, deferred, or host-owned: {unclassified_methods:?}",
    );

    let stale_bridged_methods = bridged_method_names
        .difference(upstream_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_bridged_methods.is_empty(),
        "Bridged {surface} methods are no longer public methods: {stale_bridged_methods:?}",
    );

    let stale_deferred_methods = deferred_method_names
        .difference(upstream_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_deferred_methods.is_empty(),
        "Deferred {surface} methods are no longer public methods: {stale_deferred_methods:?}",
    );

    let stale_host_owned_methods = host_owned_method_names
        .difference(upstream_methods)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        stale_host_owned_methods.is_empty(),
        "Host-owned {surface} methods are no longer public methods: {stale_host_owned_methods:?}",
    );

    let deferred_but_bridged = deferred_method_names
        .intersection(&bridged_method_names)
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        deferred_but_bridged.is_empty(),
        "{surface} methods cannot be both deferred and bridged: {deferred_but_bridged:?}",
    );

    let missing_host_fields = bridged_methods
        .iter()
        .filter(|(_, field)| !host_vtable_methods.contains(*field))
        .map(|(method, field)| format!("{method} -> {field}"))
        .collect::<Vec<_>>();
    assert!(
        missing_host_fields.is_empty(),
        "Bridged {surface} methods must point at HostVTable fields: {missing_host_fields:?}",
    );
}

fn data_actor_callback_names() -> BTreeSet<String> {
    callback_names_between(
        DATA_ACTOR_SOURCE,
        "pub trait DataActor:",
        "    /// Handles a received time event.",
    )
}

fn strategy_callback_names() -> BTreeSet<String> {
    callback_names_between(
        STRATEGY_SOURCE,
        "pub trait Strategy: DataActor",
        "#[cfg(test)]",
    )
}

fn strategy_method_names() -> BTreeSet<String> {
    method_names_between(
        STRATEGY_SOURCE,
        "pub trait Strategy: DataActor",
        "\nfn publish_order_initialized",
    )
}

fn strategy_execution_method_names() -> BTreeSet<String> {
    method_names_between(
        STRATEGY_SOURCE,
        "    /// Submits an order.",
        "    /// Handles an order event",
    )
}

fn data_actor_core_public_method_names() -> BTreeSet<String> {
    public_method_names_between(
        DATA_ACTOR_CORE_SOURCE,
        "impl DataActorCore {",
        "\nfn check_timestamps",
    )
}

fn strategy_core_public_method_names() -> BTreeSet<String> {
    public_method_names_between(
        STRATEGY_CORE_SOURCE,
        "impl StrategyCore {",
        "\nfn strategy_id_with_order_id_tag",
    )
}

fn plugin_actor_callback_names() -> BTreeSet<String> {
    callback_names_between(
        PLUGIN_ACTOR_SOURCE,
        "pub trait PluginActor:",
        "/// Returns a `*const ActorVTable`",
    )
}

fn plugin_strategy_callback_names() -> BTreeSet<String> {
    callback_names_between(
        PLUGIN_STRATEGY_SOURCE,
        "pub trait PluginStrategy:",
        "/// Returns a `*const StrategyVTable`",
    )
}

fn actor_vtable_callback_names() -> BTreeSet<String> {
    vtable_callback_names(PLUGIN_ACTOR_SOURCE)
}

fn strategy_vtable_callback_names() -> BTreeSet<String> {
    vtable_callback_names(PLUGIN_STRATEGY_SOURCE)
}

fn host_vtable_field_names() -> BTreeSet<String> {
    field_names_between(HOST_SOURCE, "pub struct HostVTable {", "impl HostVTable {")
}

fn vtable_callback_names(source: &str) -> BTreeSet<String> {
    source
        .lines()
        .filter_map(|line| {
            let line = line.trim_start().strip_prefix("pub on_")?;
            let (name, _) = line.split_once(':')?;
            Some(format!("on_{name}"))
        })
        .collect()
}

fn method_names_between(source: &str, start_marker: &str, stop_marker: &str) -> BTreeSet<String> {
    let section = source_between(source, start_marker, stop_marker);

    section.lines().filter_map(method_name).collect()
}

fn public_method_names_between(
    source: &str,
    start_marker: &str,
    stop_marker: &str,
) -> BTreeSet<String> {
    let section = source_between(source, start_marker, stop_marker);
    let mut skip_next_public_method = false;
    let mut names = BTreeSet::new();

    for line in section.lines() {
        let line = line.trim_start();
        if line == "#[cfg(test)]" {
            skip_next_public_method = true;
            continue;
        }

        if let Some(name) = public_method_name(line) {
            if skip_next_public_method {
                skip_next_public_method = false;
            } else {
                names.insert(name);
            }
            continue;
        }

        if !line.is_empty()
            && !line.starts_with("#[")
            && !line.starts_with("///")
            && !line.starts_with("//")
        {
            skip_next_public_method = false;
        }
    }

    names
}

fn callback_names_between(source: &str, start_marker: &str, stop_marker: &str) -> BTreeSet<String> {
    let section = source_between(source, start_marker, stop_marker);

    section.lines().filter_map(callback_name).collect()
}

fn field_names_between(source: &str, start_marker: &str, stop_marker: &str) -> BTreeSet<String> {
    let section = source_between(source, start_marker, stop_marker);

    section
        .lines()
        .filter_map(|line| {
            let line = line.trim_start().strip_prefix("pub ")?;
            let (name, _) = line.split_once(':')?;
            Some(name.to_string())
        })
        .collect()
}

fn source_between<'a>(source: &'a str, start_marker: &str, stop_marker: &str) -> &'a str {
    let (_, after_start) = source
        .split_once(start_marker)
        .expect("surface start marker must exist");
    let (section, _) = after_start
        .split_once(stop_marker)
        .expect("surface stop marker must exist");

    section
}

fn method_name(line: &str) -> Option<String> {
    let line = line.trim_start().strip_prefix("fn ")?;
    let (name, _) = line.split_once('(')?;
    Some(name.to_string())
}

fn public_method_name(line: &str) -> Option<String> {
    let line = line.trim_start().strip_prefix("pub fn ")?;
    let (name, _) = line.split_once('(')?;
    Some(name.to_string())
}

fn callback_name(line: &str) -> Option<String> {
    method_name(line).filter(|name| name.starts_with("on_"))
}
