from stubs.model.book import OrderBook
from stubs.model.identifiers import InstrumentId
from stubs.model.objects import Price
from stubs.model.objects import Quantity

def create_betfair_order_book(instrument_id: InstrumentId) -> OrderBook: ...
def betfair_float_to_price(value: float) -> Price: ...
def betfair_float_to_quantity(value: float) -> Quantity: ...
