from nautilus_trader.core.nautilus_pyo3 import AccountType
from nautilus_trader.core.nautilus_pyo3 import AggregationSource
from nautilus_trader.core.nautilus_pyo3 import AggressorSide
from nautilus_trader.core.nautilus_pyo3 import AssetClass
from nautilus_trader.core.nautilus_pyo3 import BarAggregation
from nautilus_trader.core.nautilus_pyo3 import BookAction
from nautilus_trader.core.nautilus_pyo3 import BookType
from nautilus_trader.core.nautilus_pyo3 import ContingencyType
from nautilus_trader.core.nautilus_pyo3 import CurrencyType
from nautilus_trader.core.nautilus_pyo3 import InstrumentClass
from nautilus_trader.core.nautilus_pyo3 import InstrumentCloseType
from nautilus_trader.core.nautilus_pyo3 import LiquiditySide
from nautilus_trader.core.nautilus_pyo3 import MarketStatus
from nautilus_trader.core.nautilus_pyo3 import MarketStatusAction
from nautilus_trader.core.nautilus_pyo3 import OmsType
from nautilus_trader.core.nautilus_pyo3 import OptionKind
from nautilus_trader.core.nautilus_pyo3 import OrderSide
from nautilus_trader.core.nautilus_pyo3 import OrderStatus
from nautilus_trader.core.nautilus_pyo3 import OrderType
from nautilus_trader.core.nautilus_pyo3 import PositionSide
from nautilus_trader.core.nautilus_pyo3 import PriceType
from nautilus_trader.core.nautilus_pyo3 import RecordFlag
from nautilus_trader.core.nautilus_pyo3 import TimeInForce
from nautilus_trader.core.nautilus_pyo3 import TradingState
from nautilus_trader.core.nautilus_pyo3 import TrailingOffsetType
from nautilus_trader.core.nautilus_pyo3 import TriggerType
from nautilus_trader.core import nautilus_pyo3

def account_type_from_str(value: str) -> AccountType: ...
def account_type_to_str(value: AccountType) -> str: ...
def aggregation_source_from_str(value: str) -> AggregationSource: ...
def aggregation_source_to_str(value: AggregationSource) -> str: ...
def aggressor_side_from_str(value: str) -> AggressorSide: ...
def aggressor_side_to_str(value: AggressorSide) -> str: ...
def asset_class_from_str(value: str) -> AssetClass: ...
def asset_class_to_str(value: AssetClass) -> str: ...
def instrument_class_from_str(value: str) -> InstrumentClass: ...
def instrument_class_to_str(value: InstrumentClass) -> str: ...
def bar_aggregation_from_str(value: str) -> BarAggregation: ...
def bar_aggregation_to_str(value: BarAggregation) -> str: ...
def book_action_from_str(value: str) -> BookAction: ...
def book_action_to_str(value: BookAction) -> str: ...
def book_type_from_str(value: str) -> BookType: ...
def book_type_to_str(value: BookType) -> str: ...
def contingency_type_from_str(value: str) -> ContingencyType: ...
def contingency_type_to_str(value: ContingencyType) -> str: ...
def currency_type_from_str(value: str) -> CurrencyType: ...
def currency_type_to_str(value: CurrencyType) -> str: ...
def instrument_close_type_from_str(value: str) -> InstrumentCloseType: ...
def instrument_close_type_to_str(value: InstrumentCloseType) -> str: ...
def liquidity_side_from_str(value: str) -> LiquiditySide: ...
def liquidity_side_to_str(value: LiquiditySide) -> str: ...
def market_status_from_str(value: str) -> MarketStatus: ...
def market_status_to_str(value: MarketStatus) -> str: ...
def market_status_action_from_str(value: str) -> MarketStatusAction: ...
def market_status_action_to_str(value: MarketStatusAction) -> str: ...
def oms_type_from_str(value: str) -> OmsType: ...
def oms_type_to_str(value: OmsType) -> str: ...
def option_kind_from_str(value: str) -> OptionKind: ...
def option_kind_to_str(value: OptionKind) -> str: ...
def order_side_from_str(value: str) -> OrderSide: ...
def order_side_to_str(value: OrderSide) -> str: ...
def order_status_from_str(value: str) -> OrderStatus: ...
def order_status_to_str(value: OrderStatus) -> str: ...
def order_type_from_str(value: str) -> OrderType: ...
def order_type_to_str(value: OrderType) -> str: ...
def record_flag_from_str(value: str) -> RecordFlag: ...
def record_flag_to_str(value: RecordFlag) -> str: ...
def position_side_from_str(value: str) -> PositionSide: ...
def position_side_to_str(value: PositionSide) -> str: ...
def price_type_from_str(value: str) -> PriceType: ...
def price_type_to_str(value: PriceType) -> str: ...
def time_in_force_from_str(value: str) -> TimeInForce: ...
def time_in_force_to_str(value: TimeInForce) -> str: ...
def trading_state_from_str(value: str) -> TradingState: ...
def trading_state_to_str(value: TradingState) -> str: ...
def trailing_offset_type_from_str(value: str) -> TrailingOffsetType: ...
def trailing_offset_type_to_str(value: TrailingOffsetType) -> str: ...
def trigger_type_from_str(value: str) -> TriggerType: ...
def trigger_type_to_str(value: TriggerType) -> str: ...
def order_side_to_pyo3(value: OrderSide) -> nautilus_pyo3.OrderSide: ...
def order_type_to_pyo3(value: OrderType) -> nautilus_pyo3.OrderType: ...
def order_status_to_pyo3(value: OrderStatus) -> nautilus_pyo3.OrderStatus: ...
def time_in_force_to_pyo3(value: TimeInForce) -> nautilus_pyo3.TimeInForce: ...
def order_side_from_pyo3(value: nautilus_pyo3.OrderSide) -> OrderSide: ...
def order_type_from_pyo3(value: nautilus_pyo3.OrderType) -> OrderType: ...
def order_status_from_pyo3(value: nautilus_pyo3.OrderStatus) -> OrderStatus: ...
def time_in_force_from_pyo3(value: nautilus_pyo3.TimeInForce) -> TimeInForce: ...
def liquidity_side_from_pyo3(value: nautilus_pyo3.LiquiditySide) -> LiquiditySide: ...
def contingency_type_from_pyo3(value: nautilus_pyo3.ContingencyType) -> ContingencyType: ...
def position_side_from_pyo3(value: nautilus_pyo3.PositionSide) -> PositionSide: ...