class Identifier:

    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __lt__(self, other: Identifier) -> bool: ...
    def __le__(self, other: Identifier) -> bool: ...
    def __gt__(self, other: Identifier) -> bool: ...
    def __ge__(self, other: Identifier) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def value(self) -> str: ...


class Symbol(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: Symbol) -> bool: ...
    def __hash__(self) -> int: ...
    def is_composite(self) -> bool: ...
    def root(self) -> str: ...
    def topic(self) -> str: ...


class Venue(Identifier):

    def __init__(self, name: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: Venue) -> bool: ...
    def __hash__(self) -> int: ...
    def is_synthetic(self) -> bool: ...
    @staticmethod
    def from_code(code: str) -> Venue | None: ...


class InstrumentId(Identifier):

    def __init__(self, symbol: Symbol, venue: Venue) -> None: ...
    @property
    def symbol(self) -> Symbol: ...
    @property
    def venue(self) -> Venue: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: InstrumentId) -> bool: ...
    def __hash__(self) -> int: ...
    @staticmethod
    def from_str(value: str) -> InstrumentId: ...
    def is_synthetic(self) -> bool: ...
    @staticmethod
    def from_pyo3(pyo3_instrument_id: InstrumentId) -> InstrumentId: ...
    def to_pyo3(self) -> InstrumentId: ...


class ComponentId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: ComponentId) -> bool: ...
    def __hash__(self) -> int: ...


class ClientId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: ClientId) -> bool: ...
    def __hash__(self) -> int: ...


class TraderId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: TraderId) -> bool: ...
    def __hash__(self) -> int: ...
    def get_tag(self) -> str: ...


class StrategyId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: StrategyId) -> bool: ...
    def __hash__(self) -> int: ...
    def get_tag(self) -> str: ...
    def is_external(self) -> bool: ...


class ExecAlgorithmId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: ExecAlgorithmId) -> bool: ...
    def __hash__(self) -> int: ...


class AccountId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: AccountId) -> bool: ...
    def __hash__(self) -> int: ...
    def get_issuer(self) -> str: ...
    def get_id(self) -> str: ...


class ClientOrderId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: ClientOrderId) -> bool: ...
    def __hash__(self) -> int: ...


class VenueOrderId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: VenueOrderId) -> bool: ...
    def __hash__(self) -> int: ...


class OrderListId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: OrderListId) -> bool: ...
    def __hash__(self) -> int: ...


class PositionId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: PositionId) -> bool: ...
    def __hash__(self) -> int: ...


class TradeId(Identifier):

    def __init__(self, value: str) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state) -> None: ...
    def __eq__(self, other: TradeId) -> bool: ...
    def __hash__(self) -> int: ...
