# This file is automatically generated by pyo3_stub_gen

__all__ = [
    "ensure_file_exists_or_download_http",
]

def ensure_file_exists_or_download_http(
    filepath: str, url: str, checksums: str | None = None, timeout_secs: int | None = 30
) -> None: ...
