# This file is automatically generated by pyo3_stub_gen

import decimal
import typing

from nautilus_trader import model

__all__ = [
    "DataTesterConfig",
    "ExecTesterConfig",
    "ensure_file_exists_or_download_http",
]

@typing.final
class DataTesterConfig:
    def __init__(
        self,
        actor_id: model.ActorId | None = None,
        client_id: model.ClientId | None = None,
        instrument_ids: typing.Sequence[model.InstrumentId] | None = None,
        bar_types: typing.Sequence[model.BarType] | None = None,
        subscribe_book_deltas: bool | None = None,
        subscribe_book_depth: bool | None = None,
        subscribe_book_at_interval: bool | None = None,
        subscribe_quotes: bool | None = None,
        subscribe_trades: bool | None = None,
        subscribe_mark_prices: bool | None = None,
        subscribe_index_prices: bool | None = None,
        subscribe_funding_rates: bool | None = None,
        subscribe_bars: bool | None = None,
        subscribe_instrument: bool | None = None,
        subscribe_instrument_status: bool | None = None,
        subscribe_instrument_close: bool | None = None,
        subscribe_option_greeks: bool | None = None,
        can_unsubscribe: bool | None = None,
        request_instruments: bool | None = None,
        request_quotes: bool | None = None,
        request_trades: bool | None = None,
        request_bars: bool | None = None,
        request_book_snapshot: bool | None = None,
        request_book_deltas: bool | None = None,
        request_funding_rates: bool | None = None,
        book_depth: int | None = None,
        book_interval_ms: int | None = None,
        book_levels_to_print: int | None = None,
        manage_book: bool | None = None,
        log_data: bool | None = None,
        stats_interval_secs: int | None = None,
        log_events: bool | None = None,
        log_commands: bool | None = None,
    ) -> None: ...

@typing.final
class ExecTesterConfig:
    def __init__(
        self,
        strategy_id: model.StrategyId | None = None,
        order_id_tag: str | None = None,
        use_hyphens_in_client_order_ids: bool | None = None,
        external_order_claims: typing.Sequence[model.InstrumentId] | None = None,
        instrument_id: model.InstrumentId | None = None,
        client_id: model.ClientId | None = None,
        order_qty: model.Quantity | None = None,
        subscribe_book: bool | None = None,
        subscribe_quotes: bool | None = None,
        subscribe_trades: bool | None = None,
        open_position_on_start_qty: decimal.Decimal | None = None,
        open_position_on_first_quote: bool | None = None,
        open_position_time_in_force: model.TimeInForce | None = None,
        enable_limit_buys: bool | None = None,
        enable_limit_sells: bool | None = None,
        enable_stop_buys: bool | None = None,
        enable_stop_sells: bool | None = None,
        tob_offset_ticks: int | None = None,
        limit_time_in_force: model.TimeInForce | None = None,
        use_post_only: bool | None = None,
        limit_aggressive: bool | None = None,
        cancel_orders_on_stop: bool | None = None,
        close_positions_on_stop: bool | None = None,
        close_positions_time_in_force: model.TimeInForce | None = None,
        reduce_only_on_stop: bool | None = None,
        dry_run: bool | None = None,
        log_data: bool | None = None,
        can_unsubscribe: bool | None = None,
        clamp_to_instrument_price_range: bool | None = None,
        log_events: bool | None = None,
        log_commands: bool | None = None,
    ) -> None: ...

def ensure_file_exists_or_download_http(
    filepath: str, url: str, checksums: str | None = None, timeout_secs: int | None = 30
) -> None: ...
