# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: D401

import builtins
import typing

from nautilus_trader import infrastructure
from nautilus_trader import model

__all__ = [
    "BlockchainDataClientConfig",
    "BlockchainDataClientFactory",
    "BlockchainExecutionClientConfig",
    "BlockchainExecutionClientFactory",
    "DexPoolFilters",
]

@typing.final
class BlockchainDataClientConfig:
    r"""
    Configuration for blockchain data clients.
    """

    def __init__(
        self,
        chain: model.Chain,
        dex_ids: typing.Sequence[model.DexType],
        http_rpc_url: builtins.str,
        rpc_requests_per_second: builtins.int | None,
        multicall_calls_per_rpc_request: builtins.int | None,
        wss_rpc_url: builtins.str | None,
        use_hypersync_for_live_data: builtins.bool,
        from_block: builtins.int | None,
        pool_filters: DexPoolFilters | None,
        postgres_cache_database_config: infrastructure.PostgresConnectOptions | None,
    ) -> None:
        r"""
        Creates a new `BlockchainDataClientConfig` instance.
        """
    def chain(self) -> model.Chain:
        r"""
        Returns the chain configuration.
        """
    def http_rpc_url(self) -> builtins.str:
        r"""
        Returns the HTTP RPC URL.
        """
    def wss_rpc_url(self) -> builtins.str | None:
        r"""
        Returns the WebSocket RPC URL.
        """
    def rpc_requests_per_second(self) -> builtins.int | None:
        r"""
        Returns the RPC requests per second limit.
        """
    def use_hypersync_for_live_data(self) -> builtins.bool:
        r"""
        Returns whether to use HyperSync for live data.
        """
    def from_block(self) -> builtins.int | None:
        r"""
        Returns the starting block for sync.
        """

@typing.final
class BlockchainDataClientFactory:
    r"""
    Factory for creating blockchain data clients.

    This factory creates `BlockchainDataClient` instances configured for different blockchain networks
    (Ethereum, Arbitrum, Base, Polygon) with appropriate RPC and HyperSync configurations.
    """

@typing.final
class BlockchainExecutionClientConfig:
    r"""
    Configuration for blockchain execution clients.
    """

    def __init__(
        self,
        trader_id: model.TraderId,
        client_id: model.AccountId,
        venue: model.Venue,
        chain: model.Chain,
        wallet_address: builtins.str,
        http_rpc_url: builtins.str,
        tokens: typing.Sequence[builtins.str] | None = None,
        rpc_requests_per_second: builtins.int | None = None,
    ) -> None:
        r"""
        Creates a new `BlockchainExecutionClientConfig` instance.
        """
    def trader_id(self) -> model.TraderId:
        r"""
        Returns the trader ID.
        """
    def client_id(self) -> model.AccountId:
        r"""
        Returns the account ID.
        """
    def venue(self) -> model.Venue:
        r"""
        Returns the execution venue.
        """
    def chain(self) -> model.Chain:
        r"""
        Returns the chain configuration.
        """
    def wallet_address(self) -> builtins.str:
        r"""
        Returns the wallet address.
        """
    def tokens(self) -> typing.Sequence[builtins.str] | None:
        r"""
        Returns the token addresses to monitor.
        """
    def http_rpc_url(self) -> builtins.str:
        r"""
        Returns the HTTP RPC URL.
        """
    def rpc_requests_per_second(self) -> builtins.int | None:
        r"""
        Returns the RPC requests per second limit.
        """

@typing.final
class BlockchainExecutionClientFactory:
    r"""
    Factory for creating blockchain execution clients.
    """

@typing.final
class DexPoolFilters:
    r"""
    Defines filtering criteria for the DEX pool universe that the data client will operate on.
    """

    def __init__(self, remove_pools_with_empty_erc20_fields: builtins.bool | None) -> None:
        r"""
        Creates a new `DexPoolFilters` instance.
        """
