# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: D401

import typing

from nautilus_trader import infrastructure
from nautilus_trader import model

__all__ = [
    "BlockchainDataClientConfig",
    "BlockchainDataClientFactory",
    "BlockchainExecutionClientFactory",
    "DexPoolFilters",
]

@typing.final
class BlockchainDataClientConfig:
    r"""
    Configuration for blockchain data clients.
    """

    def __init__(
        self,
        chain: model.Chain,
        dex_ids: typing.Sequence[model.DexType],
        http_rpc_url: str,
        rpc_requests_per_second: int | None,
        multicall_calls_per_rpc_request: int | None,
        wss_rpc_url: str | None,
        use_hypersync_for_live_data: bool,
        from_block: int | None,
        pool_filters: DexPoolFilters | None,
        postgres_cache_database_config: infrastructure.PostgresConnectOptions | None,
    ) -> None:
        r"""
        Creates a new `BlockchainDataClientConfig` instance.
        """
    @property
    def chain(self) -> model.Chain:
        r"""
        Returns the chain configuration.
        """
    @property
    def http_rpc_url(self) -> str:
        r"""
        Returns the HTTP RPC URL.
        """
    @property
    def wss_rpc_url(self) -> str | None:
        r"""
        Returns the WebSocket RPC URL.
        """
    @property
    def rpc_requests_per_second(self) -> int | None:
        r"""
        Returns the RPC requests per second limit.
        """
    @property
    def use_hypersync_for_live_data(self) -> bool:
        r"""
        Returns whether to use HyperSync for live data.
        """
    @property
    def from_block(self) -> int | None:
        r"""
        Returns the starting block for sync.
        """

@typing.final
class BlockchainDataClientFactory:
    r"""
    Factory for creating blockchain data clients.

    This factory creates `BlockchainDataClient` instances configured for different blockchain networks
    (Ethereum, Arbitrum, Base, Polygon) with appropriate RPC and HyperSync configurations.
    """

@typing.final
class BlockchainExecutionClientFactory:
    r"""
    Factory for creating blockchain execution clients.
    """

@typing.final
class DexPoolFilters:
    r"""
    Defines filtering criteria for the DEX pool universe that the data client will operate on.
    """

    def __init__(self, remove_pools_with_empty_erc20_fields: bool | None) -> None:
        r"""
        Creates a new `DexPoolFilters` instance.
        """
