name: common-wheel-build
description: Common wheel build and install

inputs:
  python-version:
    description: The Python version to setup
    required: true

runs:
  using: "composite"
  steps:
    - name: Update version in pyproject.toml
      shell: bash
      run: |
        bash ./scripts/ci/update-pyproject-version.sh

    - name: Generate updated lock file
      shell: bash
      run: uv lock --no-upgrade

    - name: Build Python wheel
      shell: bash
      run: |
        uv build --wheel
        ls -lh dist/

    - name: Install Python wheel
      shell: bash
      run: uv pip install dist/*.whl
