# This file is automatically generated by pyo3_stub_gen

import enum
import typing

__all__ = [
    "COINBASE",
    "CoinbaseDataClientConfig",
    "CoinbaseDataClientFactory",
    "CoinbaseEnvironment",
    "CoinbaseExecClientConfig",
    "CoinbaseExecutionClientFactory",
    "CoinbaseHttpClient",
    "CoinbaseWebSocketClient",
]

COINBASE: str

@typing.final
class CoinbaseDataClientConfig:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_rest: str | None = None,
        base_url_ws: str | None = None,
        http_proxy_url: str | None = None,
        ws_proxy_url: str | None = None,
        environment: CoinbaseEnvironment | None = None,
        http_timeout_secs: int | None = None,
        ws_timeout_secs: int | None = None,
        update_instruments_interval_mins: int | None = None,
    ) -> None: ...

@typing.final
class CoinbaseDataClientFactory: ...

@typing.final
class CoinbaseExecClientConfig:
    def __init__(
        self,
        api_key: str | None = None,
        api_secret: str | None = None,
        base_url_rest: str | None = None,
        base_url_ws: str | None = None,
        http_proxy_url: str | None = None,
        ws_proxy_url: str | None = None,
        environment: CoinbaseEnvironment | None = None,
        http_timeout_secs: int | None = None,
        max_retries: int | None = None,
        retry_delay_initial_ms: int | None = None,
        retry_delay_max_ms: int | None = None,
    ) -> None: ...

@typing.final
class CoinbaseExecutionClientFactory: ...

@typing.final
class CoinbaseHttpClient: ...

@typing.final
class CoinbaseWebSocketClient: ...

@typing.final
class CoinbaseEnvironment(enum.Enum):
    LIVE = ...
    SANDBOX = ...

    def __init__(self) -> None: ...
    def __hash__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...
