// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Derive self-custodial action signing.
//!
//! Derive signs every state-changing request with an EIP-712 typed-data
//! signature over secp256k1. V3 domains use Ethereum chain 1 or Sepolia chain
//! 11155111, with the same Trade module on both networks. The pipeline is:
//!
//! ```text
//! action_hash = keccak256(abi.encode(
//!     [bytes32, uint, uint, address, bytes32, uint, address, address],
//!     [ACTION_TYPEHASH, subaccount_id, nonce, module_address,
//!      keccak256(module_data_abi_encoded), signature_expiry_sec, owner, signer],
//! ))
//! typed_data_hash = keccak256(0x1901 || DOMAIN_SEPARATOR || action_hash)
//! signature = secp256k1_sign(typed_data_hash, signer_key)
//! ```
//!
//! Per-action `module_data` ABI encodings live under [`modules`]. REST and
//! WebSocket session authentication use the simpler `eth_sign(timestamp_ms)`
//! pattern in [`auth`]. Per-`(wallet, subaccount)` nonce allocation lives in
//! [`nonce`].
//!
//! The byte-equivalence oracle is
//! `test_data/common/signing_trade_action_vectors.json`, generated by
//! `scripts/oracle-py/derive/generate_oracle.py` from the upstream Python SDK at a
//! revision and source hashes pinned in the fixture metadata, replayed against
//! this implementation in [`eip712`] tests. The generator uses derive-py 0.1.4
//! and independently checks the domain and Action typehash formulas. Attribution is
//! recorded in `licenses/THIRD_PARTY_LICENSES.md`.
//!
//! Protocol constants (`DOMAIN_SEPARATOR`, `ACTION_TYPEHASH`, Trade module address)
//! are sourced from <https://docs.derive.xyz/authentication/action-signing>.
//! Financial inputs allow at most 12 fractional digits, but the canonical trade
//! ABI still scales them by 1e18. Nonces are nanoseconds encoded as strings;
//! login timestamps are milliseconds and signature expiry is seconds.

pub mod auth;
pub mod context;
pub mod eip712;
pub mod encoding;
pub mod modules;
pub mod nonce;
