#!/usr/bin/env bun
/**
 * Parses `model.h` (cbindgen-generated C header) and generates TypeScript enum
 * definitions as `const` objects with type unions.
 *
 * Usage: bun run scripts/generate-enums.ts
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";

// Resolve paths relative to this script
const scriptDir = dirname(new URL(import.meta.url).pathname);
const headerPath = resolve(
  scriptDir,
  "../../../nautilus_trader/core/includes/model.h",
);
const outputPath = resolve(scriptDir, "../src/model/enums/generated.ts");

// Skip tagged union discriminants — these are internal Rust representation details
const SKIP_ENUMS = new Set(["BarType_t_Tag", "Data_t_Tag"]);

interface EnumVariant {
  name: string;
  value: number;
  comment?: string;
}

interface ParsedEnum {
  name: string;
  variants: EnumVariant[];
  comment?: string;
}

function parseHeader(content: string): ParsedEnum[] {
  const enums: ParsedEnum[] = [];
  const lines = content.split("\n");
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    // Match: typedef enum EnumName {
    const enumMatch = line.match(/^typedef enum (\w+)\s*\{/);
    if (enumMatch) {
      const enumName = enumMatch[1];

      if (SKIP_ENUMS.has(enumName)) {
        // Skip to closing brace
        while (i < lines.length && !lines[i].match(/^\}\s*\w+;/)) {
          i++;
        }
        i++;
        continue;
      }

      // Collect doc comment above typedef (look backwards)
      let enumComment: string | undefined;
      let j = i - 1;
      const commentLines: string[] = [];
      while (j >= 0 && lines[j].match(/^\s*\*|^\s*\/\*\*/)) {
        commentLines.unshift(lines[j]);
        if (lines[j].match(/^\s*\/\*\*/)) break;
        j--;
      }
      if (commentLines.length > 0) {
        enumComment = commentLines
          .map((l) =>
            l
              .replace(/^\s*\/\*\*\s*/, "")
              .replace(/^\s*\*\/\s*$/, "")
              .replace(/^\s*\*\s?/, "")
              .trim(),
          )
          .filter((l) => l.length > 0)
          .join(" ");
      }

      const variants: EnumVariant[] = [];
      i++; // Move past opening brace

      let variantComment: string | undefined;

      while (i < lines.length) {
        const closingMatch = lines[i].match(/^\}\s*(\w+);/);
        if (closingMatch) {
          break;
        }

        // Collect variant doc comments
        const commentLineMatch = lines[i].match(/^\s*\/\*\*$/);
        if (commentLineMatch) {
          const cLines: string[] = [];
          while (i < lines.length && !lines[i].match(/\*\//)) {
            cLines.push(lines[i]);
            i++;
          }
          if (i < lines.length) {
            cLines.push(lines[i]);
          }
          variantComment = cLines
            .map((l) =>
              l
                .replace(/^\s*\/\*\*\s*/, "")
                .replace(/^\s*\*\/\s*$/, "")
                .replace(/^\s*\*\s?/, "")
                .trim(),
            )
            .filter((l) => l.length > 0)
            .join(" ");
          i++;
          continue;
        }

        // Match variant: NAME = VALUE, or NAME = (1 << N),
        const variantMatch = lines[i].match(
          /^\s*(\w+)\s*=\s*(.+?)\s*,?\s*$/,
        );
        if (variantMatch && !variantMatch[2].startsWith("/*")) {
          const rawValue = variantMatch[2].trim();
          let value: number;

          // Handle bit-shift expressions like (1 << 7)
          const shiftMatch = rawValue.match(/^\((\d+)\s*<<\s*(\d+)\)$/);
          if (shiftMatch) {
            value =
              parseInt(shiftMatch[1], 10) << parseInt(shiftMatch[2], 10);
          } else {
            value = parseInt(rawValue, 10);
          }

          if (!isNaN(value)) {
            variants.push({
              name: variantMatch[1],
              value,
              comment: variantComment,
            });
            variantComment = undefined;
          }
        }

        i++;
      }

      enums.push({
        name: enumName,
        variants,
        comment: enumComment,
      });
    }

    i++;
  }

  return enums;
}

function toSnakeCase(name: string): string {
  return name
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

function generateTypeScript(enums: ParsedEnum[]): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/generate-enums.ts — DO NOT EDIT",
    "//",
    "// Source: nautilus_trader/core/includes/model.h (cbindgen)",
    "",
  ];

  for (const e of enums) {
    // Doc comment
    if (e.comment) {
      lines.push(`/** ${e.comment} */`);
    }

    // Const object
    lines.push(`export const ${e.name} = {`);
    for (const v of e.variants) {
      if (v.comment) {
        lines.push(`  /** ${v.comment} */`);
      }
      lines.push(`  ${v.name}: ${v.value},`);
    }
    lines.push("} as const;");

    // Type union
    lines.push(
      `export type ${e.name} = (typeof ${e.name})[keyof typeof ${e.name}];`,
    );
    lines.push("");
  }

  return lines.join("\n");
}

// Main
const content = readFileSync(headerPath, "utf-8");
const enums = parseHeader(content);
const output = generateTypeScript(enums);
writeFileSync(outputPath, output, "utf-8");

console.log(`Generated ${enums.length} enums -> ${outputPath}`);
for (const e of enums) {
  console.log(
    `  ${e.name}: ${e.variants.length} variants [${e.variants.map((v) => `${v.name}=${v.value}`).join(", ")}]`,
  );
}
