class Data:

    @property
    def ts_event(self) -> int: ...
    @property
    def ts_init(self) -> int: ...
    @classmethod
    def fully_qualified_name(cls) -> str: ...
    @classmethod
    def is_signal(cls, name: str = "") -> bool: ...
