from datetime import datetime

import pandas as pd

def unix_nanos_to_dt(nanos: int):
    ...
def dt_to_unix_nanos(dt: pd.Timestamp):
    ...
def unix_nanos_to_iso8601(unix_nanos: int,  nanos_precision: bool = True) -> str:
    ...
def format_iso8601(dt: datetime, nanos_precision: bool = True) -> str:
    ...
def  format_optional_iso8601(dt: datetime, nanos_precision: bool = True) -> str:
    ...
def maybe_unix_nanos_to_dt(nanos):
    ...
def maybe_dt_to_unix_nanos(dt: pd.Timestamp):
    ...
def is_datetime_utc(dt: datetime) -> bool:
    ...
def is_tz_aware(time_object) -> bool:
    ...
def is_tz_naive(time_object) -> bool:
    ...
def as_utc_timestamp(dt: datetime) -> datetime:
    ...
def as_utc_index(data: pd.DataFrame) -> pd.DataFrame | None:
    ...
def time_object_to_dt(time_object) -> datetime | None:
    ...
def max_date(date1: pd.Timestamp | str | int | None = None, date2: str | int | None = None) -> pd.Timestamp | None:
    ...
def min_date(date1: pd.Timestamp | str | int | None = None, date2: str | int | None = None) -> pd.Timestamp | None:
    ...

