import numpy as np
from typing import overload

def fast_mean(values: np.ndarray) -> float: ...
def fast_mean_iterated(values: np.ndarray, next_value: float, current_value: float, expected_length: int, drop_left: bool = True) -> float: ...
def fast_std(values: np.ndarray) -> float: ...
def fast_std_with_mean(values: np.ndarray, mean: float) -> float: ...
def fast_mad(values: np.ndarray) -> float: ...
def fast_mad_with_mean(values: np.ndarray, mean: float) -> float: ...
def basis_points_as_percentage(basis_points: float) -> float: ...