# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: D401

import typing

__all__ = [
    "UUID4",
    "convert_to_snake_case",
    "is_pycapsule",
    "is_within_last_24_hours",
    "last_weekday_nanos",
    "mask_api_key",
    "micros_to_nanos",
    "millis_to_nanos",
    "nanos_to_micros",
    "nanos_to_millis",
    "nanos_to_secs",
    "secs_to_millis",
    "secs_to_nanos",
    "unix_nanos_to_iso8601",
]

@typing.final
class UUID4:
    r"""
    Represents a Universally Unique Identifier (UUID)
    version 4 based on a 128-bit label as specified in RFC 4122.
    """

    def __init__(self) -> None:
        r"""
        Creates a new [`UUID4`] instance.

        If a string value is provided, it attempts to parse it into a UUID.
        If no value is provided, a new random UUID is generated.
        """
    def __setstate__(self, state: typing.Any) -> None:
        r"""
        Sets the state of the `UUID4` instance during unpickling.
        """
    def __getstate__(self) -> typing.Any:
        r"""
        Gets the state of the `UUID4` instance for pickling.
        """
    def __reduce__(self) -> typing.Any:
        r"""
        Reduces the `UUID4` instance for pickling.
        """
    def __hash__(self) -> int:
        r"""
        Returns a hash value for the `UUID4` instance.
        """
    @property
    def value(self) -> str:
        r"""
        Gets the `UUID4` value as a string.
        """
    @staticmethod
    def from_str(value: str) -> UUID4:
        r"""
        Creates a new [`UUID4`] from a string representation.
        """

def convert_to_snake_case(input: str) -> str:
    r"""
    Convert the given string from any common case (PascalCase, camelCase, kebab-case, etc.)
    to *lower* `snake_case`.

    This function uses the `heck` Rust crate under the hood.

    Parameters
    ----------
    input : str
        The input string to convert.

    Returns
    -------
    str
    """

def is_pycapsule(obj: typing.Any) -> bool:
    r"""
    Return a value indicating whether the `obj` is a `PyCapsule`.

    Parameters
    ----------
    obj : Any
        The object to check.

    Returns
    -------
    bool
    """

def is_within_last_24_hours(timestamp_ns: int) -> bool:
    r"""
    Return whether the given UNIX nanoseconds timestamp is within the last 24 hours.

    Parameters
    ----------
    timestamp_ns : int
        The UNIX nanoseconds timestamp datum.

    Returns
    -------
    bool

    Raises
    ------
    ValueError
        If `timestamp` is invalid.

    # Errors

    Returns a `PyErr` if the provided timestamp is invalid.
    """

def last_weekday_nanos(year: int, month: int, day: int) -> int:
    r"""
    Return UNIX nanoseconds at midnight (UTC) of the last weekday (Mon-Fri).

    Parameters
    ----------
    year : int
        The year from the datum date.
    month : int
        The month from the datum date.
    day : int
        The day from the datum date.

    Returns
    -------
    int

    Raises
    ------
    `ValueError`
        If given an invalid date.

    # Errors

    Returns a `PyErr` if the provided date is invalid.
    """

def mask_api_key(api_key: str) -> str:
    r"""
    Masks an API key by showing only the first and last 4 characters.

    For keys 8 characters or shorter, returns asterisks only.

    Parameters
    ----------
    api_key : str
        The API key to mask.

    Returns
    -------
    str

    Examples
    --------
    >>> mask_api_key("abcdefghijklmnop")
    'abcd...mnop'
    >>> mask_api_key("short")
    '*****'
    """

def micros_to_nanos(micros: float) -> int:
    r"""
    Return round nanoseconds (ns) converted from the given microseconds (μs).

    Parameters
    ----------
    micros : float
        The microseconds to convert.

    Returns
    -------
    int
    """

def millis_to_nanos(millis: float) -> int:
    r"""
    Return round nanoseconds (ns) converted from the given milliseconds (ms).

    Parameters
    ----------
    millis : float
        The milliseconds to convert.

    Returns
    -------
    int
    """

def nanos_to_micros(nanos: int) -> int:
    r"""
    Return round microseconds (μs) converted from the given nanoseconds (ns).

    Parameters
    ----------
    nanos : int
        The nanoseconds to convert.

    Returns
    -------
    int
    """

def nanos_to_millis(nanos: int) -> int:
    r"""
    Return round milliseconds (ms) converted from the given nanoseconds (ns).

    Parameters
    ----------
    nanos : int
        The nanoseconds to convert.

    Returns
    -------
    int
    """

def nanos_to_secs(nanos: int) -> float:
    r"""
    Return seconds converted from the given nanoseconds (ns).

    Parameters
    ----------
    nanos : int
        The nanoseconds to convert.

    Returns
    -------
    float
    """

def secs_to_millis(secs: float) -> int:
    r"""
    Return round milliseconds (ms) converted from the given seconds.

    Parameters
    ----------
    secs : float
        The seconds to convert.

    Returns
    -------
    int
    """

def secs_to_nanos(secs: float) -> int:
    r"""
    Return round nanoseconds (ns) converted from the given seconds.

    Parameters
    ----------
    secs : float
        The seconds to convert.

    Returns
    -------
    int
    """

def unix_nanos_to_iso8601(timestamp_ns: int, nanos_precision: bool | None = True) -> str:
    r"""
    Return UNIX nanoseconds as an ISO 8601 (RFC 3339) format string.

    Parameters
    ----------
    timestamp_ns : int
        The UNIX timestamp (nanoseconds).
    nanos_precision : bool, default True
        If True, use nanosecond precision. If False, use millisecond precision.

    Returns
    -------
    str

    Raises
    ------
    ValueError
        If `timestamp_ns` is invalid.
    """
