from nautilus_trader.model.data import Bar
from nautilus_trader.model.data import QuoteTick
from nautilus_trader.model.data import TradeTick

class Indicator:
    name: str
    has_inputs: bool
    initialized: bool

    def __init__(self, params: list) -> None: ...
    def handle_quote_tick(self, tick: QuoteTick) -> None: ...
    def handle_trade_tick(self, tick: TradeTick) -> None: ...
    def handle_bar(self, bar: Bar) -> None: ...
    def reset(self) -> None: ...
    def _set_has_inputs(self, setting: bool) -> None: ...
    def _set_initialized(self, setting: bool) -> None: ...
    def _reset(self) -> None: ...
