import pytz

from nautilus_trader.backtest.config import FXRolloverInterestConfig
from nautilus_trader.backtest.config import SimulationModuleConfig
from stubs.backtest.exchange import SimulatedExchange
from stubs.common.actor import Actor
from stubs.common.component import Logger
from stubs.core.data import Data

_TZ_US_EAST: pytz.tzinfo.DstTzInfo


class SimulationModule(Actor):

    def __init__(self, config: SimulationModuleConfig): ...
    def __repr__(self) -> str: ...
    def register_venue(self, exchange: SimulatedExchange) -> None: ...
    def pre_process(self, data: Data) -> None: ...
    def process(self, ts_now: int) -> None: ...
    def log_diagnostics(self, logger: Logger) -> None: ...
    def reset(self) -> None: ...


class FXRolloverInterestModule(SimulationModule):

    def __init__(self, config: FXRolloverInterestConfig): ...
    def process(self, ts_now: int) -> None: ...
    def log_diagnostics(self, logger: Logger) -> None: ...
    def reset(self) -> None: ...

