# Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

from cpython.object cimport PyObject
from libc.stdint cimport uintptr_t, uint8_t, int64_t

cdef extern from "../includes/core.h":
    pass