#!/usr/bin/env python3
# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------
"""
Custom build script for nautilus-trader v2 with automatic stub generation.

This script can be used as:
1. A standalone stub generator: python generate_stubs.py
2. A custom build script: python generate_stubs.py build
3. Integrated with uv/pip build systems via pyproject.toml

"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import subprocess
import sys
import tomllib
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from collections.abc import Sequence

# Renames applied to method definitions
METHOD_RENAMES: dict[str, str] = {
    "py_new": "__init__",
}

# Standard stub file header with ruff ignores
STUB_HEADER = """\
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: D401, E501, F401
"""


@dataclass(frozen=True)
class StubFixup:
    """
    Configuration for relocating and patching stub content for a module.
    """

    classes: tuple[str, ...] = ()
    imports: tuple[str, ...] = ()
    all_exports: tuple[str, ...] = ()


# Classes to relocate from _libnautilus to their target modules
MODULE_FIXUPS: dict[str, StubFixup] = {
    "adapters.blockchain": StubFixup(
        classes=(
            "BlockchainDataClientConfig",
            "BlockchainDataClientFactory",
            "DexPoolFilters",
        ),
        imports=(
            "import builtins",
            "import typing",
            "import nautilus_trader",
            "import nautilus_trader.infrastructure",
            "import nautilus_trader.model",
        ),
    ),
    "model": StubFixup(
        classes=(
            "AmmType",
            "DexType",
            "Dex",
            "Blockchain",
            "Chain",
        ),
        imports=("from enum import Enum",),
        all_exports=("AmmType", "Blockchain", "Chain", "DataType", "Dex", "DexType"),
    ),
}


def run_command(
    cmd: Sequence[str],
    cwd: Path | None = None,
    check: bool = True,
) -> subprocess.CompletedProcess[str]:
    """
    Run a command and return the result.
    """
    print(f"Running: {' '.join(cmd)}")
    if cwd:
        print(f"  in: {cwd}")

    result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)

    if check and result.returncode != 0:
        print(f"Error: {result.stderr}")
        raise subprocess.CalledProcessError(result.returncode, cmd)

    return result


def load_pyproject() -> dict:
    """
    Load the pyproject.toml located next to this script.
    """
    pyproject_path = Path(__file__).parent / "pyproject.toml"
    with pyproject_path.open("rb") as fp:
        return tomllib.load(fp)


def resolve_python_stub_root(pyproject: dict) -> Path:
    """
    Return the directory where pyo3-stub-gen writes .pyi files.
    """
    python_source = pyproject.get("tool", {}).get("maturin", {}).get("python-source", ".")

    dest_dir = (Path(__file__).parent / python_source).resolve()
    python_dir = Path(__file__).parent.resolve()
    try:
        dest_dir.relative_to(python_dir)
    except ValueError as e:
        raise RuntimeError(
            "python-source must stay within the python/ package directory",
        ) from e

    dest_dir.mkdir(parents=True, exist_ok=True)
    return dest_dir


def generate_stubs() -> bool:
    """
    Generate type stubs using pyo3-stub-gen.
    """
    print("Generating type stubs with pyo3-stub-gen...")

    crates_dir = Path(__file__).parent.parent / "crates" / "pyo3"
    pyproject = load_pyproject()
    dest_dir = resolve_python_stub_root(pyproject)
    module_name = pyproject.get("tool", {}).get("maturin", {}).get("module-name") or pyproject.get(
        "project",
        {},
    ).get("name", "nautilus_trader")
    module_root = module_name.split(".")[0]

    maturin_features = pyproject.get("tool", {}).get("maturin", {}).get("features", [])
    cargo_features = [f for f in maturin_features if f != "extension-module"]

    cmd = ["cargo", "run", "--bin", "python-stub-gen"]
    if cargo_features:
        cmd.extend(["--features", ",".join(cargo_features)])

    result = run_command(cmd, cwd=crates_dir)

    print("Stubs generated successfully")
    if result.stdout:
        print(f"Output: {result.stdout}")

    stub_files = sorted(dest_dir.rglob("*.pyi"))

    if not stub_files:
        print("Stub generation completed but no .pyi files were produced")
        return False

    # Post-process all stub files
    root = dest_dir / "nautilus_trader"
    if root.exists():
        post_process_stubs(root)
        relocate_classes_from_libnautilus(root)

    relative_root = dest_dir.relative_to(Path(__file__).parent)
    print(f"Type stubs written to {relative_root or Path('.')} ")

    # Refresh file list after processing
    stub_files = sorted(dest_dir.rglob("*.pyi"))
    preview_limit = 20
    filtered = [
        stub_file
        for stub_file in stub_files
        if stub_file.relative_to(dest_dir).parts
        and stub_file.relative_to(dest_dir).parts[0] == module_root
    ]

    targets = filtered if filtered else stub_files

    for stub_file in targets[:preview_limit]:
        print(f"Generated: {stub_file.relative_to(dest_dir)}")

    remaining = len(targets) - preview_limit
    if remaining > 0:
        print(f"...and {remaining} more stub files")

    return True


def post_process_stubs(root: Path) -> None:
    """Post-process all stub files: fix headers, rename methods, fix return types."""
    for stub_file in root.rglob("*.pyi"):
        content = stub_file.read_text()
        original = content

        # Ensure proper header with D401 ignore
        content = fix_stub_header(content)

        # Rename methods (py_new -> __init__, etc.)
        content = rename_methods(content)

        # Normalize formatting
        content = normalize_stub_content(content)

        if content != original:
            stub_file.write_text(content)


def fix_stub_header(content: str) -> str:
    """
    Ensure stub file has proper header with ruff ignores.
    """
    lines = content.split("\n")

    # Find where the header ends (first non-comment, non-empty line)
    header_end = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            header_end = i
            break

    # Check if D401 is already in the header
    header = "\n".join(lines[:header_end])
    if "D401" in header:
        return content

    # Replace or prepend header
    body = "\n".join(lines[header_end:])
    return STUB_HEADER + "\n" + body


def relocate_classes_from_libnautilus(root: Path) -> None:
    """
    Extract specific classes from _libnautilus and merge into target modules.
    """
    lib_stub = find_libnautilus_stub(root)
    if lib_stub is None:
        return

    source = lib_stub.read_text()
    remaining = source

    for module_suffix, fixup in MODULE_FIXUPS.items():
        if not fixup.classes:
            continue

        remaining, blocks = extract_class_blocks(remaining, fixup.classes)

        if not blocks:
            continue

        module_parts = module_suffix.split(".")
        module_path = root.joinpath(*module_parts)
        module_path.mkdir(parents=True, exist_ok=True)
        target_file = module_path / "__init__.pyi"

        # Read existing content if file exists
        if target_file.exists():
            existing = target_file.read_text()
        else:
            existing = ""

        # Merge the new class blocks into existing content
        merged = merge_stub_content(existing, blocks, fixup)
        target_file.write_text(merged)

    # Clean up the remaining _libnautilus content
    remaining = clean_orphaned_decorators(remaining)

    # Remove extracted class names from __all__
    all_extracted_classes: set[str] = set()
    for fixup in MODULE_FIXUPS.values():
        all_extracted_classes.update(fixup.classes)
    remaining = remove_from_all_list(remaining, all_extracted_classes)

    lib_stub.write_text(remaining.strip() + "\n")


def find_libnautilus_stub(root: Path) -> Path | None:
    """
    Find the _libnautilus stub file (handles both old and new formats).
    """
    # New format: _libnautilus/__init__.pyi (pyo3-stub-gen >= 0.18.0)
    new_path = root / "_libnautilus" / "__init__.pyi"
    if new_path.exists():
        return new_path

    # Old format: _libnautilus.pyi
    old_path = root / "_libnautilus.pyi"
    if old_path.exists():
        return old_path

    return None


def merge_stub_content(existing: str, new_blocks: list[str], fixup: StubFixup) -> str:
    """
    Merge new class blocks into existing stub content.
    """
    lines = existing.split("\n") if existing else []

    # Collect existing imports and find body start
    existing_imports: set[str] = set()
    body_lines: list[str] = []
    in_all_block = False

    for line in lines:
        stripped = line.strip()

        # Skip comments and empty lines at the start
        if stripped.startswith("#"):
            continue

        # Handle __all__ block (may span multiple lines)
        if stripped.startswith("__all__") or in_all_block:
            in_all_block = "]" not in line
            continue

        # Collect imports
        if stripped.startswith(("import ", "from ")):
            existing_imports.add(stripped)
            continue

        # Everything else is body content
        body_lines.append(line)

    existing_body = "\n".join(body_lines).strip()

    # Build new imports
    all_imports = existing_imports | set(fixup.imports)
    # Standard imports that are always needed
    all_imports.add("import builtins")
    all_imports.add("import typing")

    # Sort imports
    sorted_imports = sorted(all_imports, key=lambda x: (not x.startswith("import "), x))

    # Build __all__ if specified
    all_section = ""
    if fixup.all_exports:
        all_list = ", ".join(f'"{name}"' for name in sorted(fixup.all_exports))
        all_section = f"__all__ = [{all_list}]\n"

    # Combine everything
    parts = [STUB_HEADER, "", "\n".join(sorted_imports), ""]
    if all_section:
        parts.append(all_section)
    if existing_body:
        parts.append(existing_body)
    if new_blocks:
        parts.append("\n\n".join(new_blocks))
    parts.append("")

    content = "\n".join(parts)
    content = normalize_stub_content(content)
    return content


def extract_class_blocks(
    source: str,
    class_names: tuple[str, ...],
) -> tuple[str, list[str]]:
    """
    Extract class definitions from source, including any preceding decorators.
    """
    lines = source.split("\n")
    blocks: list[str] = []
    lines_to_remove: set[int] = set()

    for class_name in class_names:
        class_pattern = re.compile(rf"^class {class_name}(?:\([^)]*\))?:")

        for i, line in enumerate(lines):
            if not class_pattern.match(line):
                continue

            # Found the class, now find decorators above it
            start = i
            while start > 0 and lines[start - 1].strip().startswith("@"):
                start -= 1

            # Find the end of the class body
            end = i + 1
            while end < len(lines):
                next_line = lines[end]

                # Empty lines are part of the class
                if not next_line.strip():
                    end += 1
                    continue

                # Indented lines are part of the class body
                if next_line.startswith((" ", "\t")):
                    end += 1
                    continue

                # Non-indented, non-empty line marks the end
                break

            # Extract the block
            block_lines = lines[start:end]
            block = "\n".join(block_lines).rstrip()
            block = rename_methods(block)
            blocks.append(block)

            # Mark lines for removal
            for j in range(start, end):
                lines_to_remove.add(j)

            break

    # Build remaining source excluding extracted lines
    remaining_lines = [line for i, line in enumerate(lines) if i not in lines_to_remove]
    remaining = "\n".join(remaining_lines)

    return remaining, blocks


def rename_methods(content: str) -> str:
    """
    Apply method renames and fix return type annotations.
    """
    for old_name, new_name in METHOD_RENAMES.items():
        content = re.sub(rf"\bdef\s+{old_name}\s*\(", rf"def {new_name}(", content)

    # Fix __init__ return type to be None
    content = re.sub(r"(def __init__\([^)]*\))\s*->\s*[^:]+:", r"\1 -> None:", content)

    return content


def _line_contains_name_to_remove(line: str, names_to_remove: set[str]) -> bool:
    """
    Check if line contains any of the names to remove.
    """
    return any(f'"{name}"' in line for name in names_to_remove)


def _strip_empty_all_block(lines: list[str]) -> list[str]:
    """
    Remove empty __all__ block and trailing blank line.
    """
    result: list[str] = []
    skip_next_empty = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("__all__") or stripped in ("__all__ = []", "]", "["):
            skip_next_empty = True
            continue
        if skip_next_empty and not stripped:
            skip_next_empty = False
            continue
        result.append(line)

    return result


def remove_from_all_list(source: str, names_to_remove: set[str]) -> str:
    """
    Remove specified names from __all__ list in source.
    """
    if not names_to_remove:
        return source

    lines = source.split("\n")
    result: list[str] = []
    in_all_block = False
    all_empty = True

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("__all__"):
            in_all_block = True

        if not in_all_block:
            result.append(line)
            continue

        should_skip = _line_contains_name_to_remove(line, names_to_remove)

        if "]" in line:
            in_all_block = False

        if not should_skip:
            result.append(line)
            # Track if __all__ has any remaining entries
            if stripped and stripped not in ("__all__ = [", "__all__ = []", "[", "]"):
                all_empty = False

    if all_empty:
        return "\n".join(_strip_empty_all_block(result))

    return "\n".join(result)


def clean_orphaned_decorators(source: str) -> str:
    """
    Remove orphaned decorator lines that aren't followed by a definition.
    """
    lines = source.split("\n")
    result: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]

        if line.strip().startswith("@"):
            # Look ahead for class/def or more decorators
            j = i + 1
            while j < len(lines) and lines[j].strip().startswith("@"):
                j += 1

            if j < len(lines) and (
                lines[j].strip().startswith("class ") or lines[j].strip().startswith("def ")
            ):
                result.append(line)
            else:
                # Orphaned decorator, skip it
                i += 1
                continue
        else:
            result.append(line)

        i += 1

    return "\n".join(result)


def normalize_stub_content(content: str) -> str:
    """
    Normalize type hints and formatting in stub content.
    """
    # Replace enum.Enum with Enum when "from enum import Enum" is present
    if "from enum import Enum" in content:
        content = re.sub(r"\benum\.Enum\b", "Enum", content)

    # Fix module references when using "from X import Y" style imports
    # e.g. nautilus_trader.model.X -> model.X
    if "from nautilus_trader import model" in content:
        content = re.sub(r"\bnautilus_trader\.model\.", "model.", content)
    if "from nautilus_trader import infrastructure" in content:
        content = re.sub(r"\bnautilus_trader\.infrastructure\.", "infrastructure.", content)

    # Normalize multiple blank lines to maximum of two
    content = re.sub(r"\n{4,}", "\n\n\n", content)

    # Ensure single newline at end
    content = content.rstrip() + "\n"

    return content


def build_extension() -> bool:
    """
    Build the extension using maturin.
    """
    print("Building extension with maturin...")

    run_command(["maturin", "develop", "--release"])

    print("Extension built successfully")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="NautilusTrader v2 build script")
    parser.add_argument(
        "action",
        nargs="?",
        default="stubs",
        choices=["stubs", "build", "all"],
        help="Action to perform: stubs (default), build, or all",
    )

    args = parser.parse_args()

    print(f"Starting nautilus-trader v2 {args.action}...")

    try:
        if args.action in ["stubs", "all"] and not generate_stubs():
            return 1

        if args.action in ["build", "all"] and not build_extension():
            return 1

        action_name = "Build" if args.action != "stubs" else "Stub generation"
        print(f"{action_name} completed successfully")
        return 0

    except subprocess.CalledProcessError as e:
        print(f"Build failed: {e}")
        return 1
    except Exception as e:
        print(f"Unexpected error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
