#!/usr/bin/env python3
# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2026 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------
"""
Custom build script for nautilus-trader v2 with automatic stub generation.

This script can be used as:
1. A standalone stub generator: python generate_stubs.py
2. A custom build script: python generate_stubs.py build
3. Integrated with uv/pip build systems via pyproject.toml

"""

from __future__ import annotations

import argparse
import keyword
import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from dataclasses import field
from pathlib import Path
from typing import TYPE_CHECKING


if TYPE_CHECKING:
    from collections.abc import Sequence

# Renames applied to method definitions
METHOD_RENAMES: dict[str, str] = {
    "py_new": "__init__",
}

# Standard stub file header with ruff ignores
STUB_HEADER = """\
# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: D401, E501, F401, RUF002
"""


def to_screaming_snake_case(name: str) -> str:
    """
    Convert a PascalCase or camelCase name to SCREAMING_SNAKE_CASE.

    Uses the same word-splitting algorithm as the ``heck`` crate (which PyO3
    uses for ``rename_all``). Digits are treated as lowercase, so ``Level1``
    becomes ``LEVEL1`` (no underscore before the digit).

    """
    if not name:
        return name

    words: list[str] = []
    current: list[str] = []

    for i, ch in enumerate(name):
        if ch == "_":
            if current:
                words.append("".join(current))
                current = []
            continue

        if ch.isupper() and current:
            prev = name[i - 1]

            if (
                prev.islower()
                or prev.isdigit()
                or (
                    prev.isupper()
                    and i + 1 < len(name)
                    and (name[i + 1].islower() or name[i + 1].isdigit())
                )
            ):
                words.append("".join(current))
                current = [ch]
            else:
                current.append(ch)
        else:
            current.append(ch)

    if current:
        words.append("".join(current))

    return "_".join(word.upper() for word in words)


@dataclass(frozen=True)
class StubFixup:
    """
    Configuration for relocating and patching stub content for a module.
    """

    classes: tuple[str, ...] = ()
    imports: tuple[str, ...] = ()
    all_exports: tuple[str, ...] = ()


@dataclass
class ClassMethodFixup:
    """
    Metadata-driven fixups for a generated stub class.
    """

    python_name: str | None = None
    getters: set[str] = field(default_factory=set)
    staticmethods: set[str] = field(default_factory=set)
    classmethods: set[str] = field(default_factory=set)
    renames: dict[str, str] = field(default_factory=dict)
    injected_staticmethods: dict[str, str] = field(default_factory=dict)
    signature_defaults: dict[str, dict[str, str]] = field(default_factory=dict)


# Classes to relocate from _libnautilus to their target modules
MODULE_FIXUPS: dict[str, StubFixup] = {
    "blockchain": StubFixup(
        classes=(
            "BlockchainDataClientConfig",
            "BlockchainDataClientFactory",
            "DexPoolFilters",
        ),
        imports=(
            "import builtins",
            "import typing",
            "import nautilus_trader",
            "import nautilus_trader.infrastructure",
            "import nautilus_trader.model",
        ),
    ),
    "model": StubFixup(
        classes=(
            "AmmType",
            "DexType",
            "Dex",
            "Blockchain",
            "Chain",
        ),
        imports=("from enum import Enum",),
        all_exports=("AmmType", "Blockchain", "Chain", "DataType", "Dex", "DexType"),
    ),
}

MODEL_EXPORTS = frozenset(MODULE_FIXUPS["model"].all_exports)


def run_command(
    cmd: Sequence[str],
    cwd: Path | None = None,
    check: bool = True,
    stream_output: bool = False,
) -> subprocess.CompletedProcess[str]:
    """
    Run a command and return the result.
    """
    print(f"Running: {' '.join(cmd)}")

    if cwd:
        print(f"  in: {cwd}")

    if stream_output:
        result = subprocess.run(cmd, cwd=cwd, text=True, check=False)
    else:
        result = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False)

    if check and result.returncode != 0:
        if not stream_output:
            print(f"Error: {result.stderr}")
        raise subprocess.CalledProcessError(result.returncode, cmd)

    return result


def load_pyproject() -> dict:
    """
    Load the pyproject.toml located next to this script.
    """
    pyproject_path = Path(__file__).parent / "pyproject.toml"
    with pyproject_path.open("rb") as fp:
        return tomllib.load(fp)


def resolve_python_stub_root(pyproject: dict) -> Path:
    """
    Return the directory where pyo3-stub-gen writes .pyi files.
    """
    python_source = pyproject.get("tool", {}).get("maturin", {}).get("python-source", ".")

    dest_dir = (Path(__file__).parent / python_source).resolve()
    python_dir = Path(__file__).parent.resolve()
    try:
        dest_dir.relative_to(python_dir)
    except ValueError as e:
        raise RuntimeError(
            "python-source must stay within the python/ package directory",
        ) from e

    dest_dir.mkdir(parents=True, exist_ok=True)
    return dest_dir


def generate_stubs() -> bool:
    """
    Generate type stubs using pyo3-stub-gen.
    """
    print("Generating type stubs with pyo3-stub-gen...")

    crates_dir = Path(__file__).parent.parent / "crates" / "pyo3"
    pyproject = load_pyproject()
    dest_dir = resolve_python_stub_root(pyproject)
    module_name = pyproject.get("tool", {}).get("maturin", {}).get("module-name") or pyproject.get(
        "project",
        {},
    ).get("name", "nautilus_trader")
    module_root = module_name.split(".")[0]

    maturin_features = pyproject.get("tool", {}).get("maturin", {}).get("features", [])
    cargo_features = [f for f in maturin_features if f != "extension-module"]

    cmd = ["cargo", "run", "--bin", "python-stub-gen"]

    if cargo_features:
        cmd.extend(["--features", ",".join(cargo_features)])

    result = run_command(cmd, cwd=crates_dir, stream_output=True)

    print("Stubs generated successfully")

    if result.stdout:
        print(f"Output: {result.stdout}")

    stub_files = sorted(dest_dir.rglob("*.pyi"))

    if not stub_files:
        print("Stub generation completed but no .pyi files were produced")
        return False

    # Post-process all stub files
    workspace_root = Path(__file__).parent.parent
    root = dest_dir / "nautilus_trader"
    if root.exists():
        post_process_stubs(root)
        relocate_classes_from_libnautilus(root)
        inject_module_constants(root, workspace_root)
        format_stub_files(root)

    relative_root = dest_dir.relative_to(Path(__file__).parent)
    print(f"Type stubs written to {relative_root or Path('.')} ")

    # Refresh file list after processing
    stub_files = sorted(dest_dir.rglob("*.pyi"))
    preview_limit = 20
    filtered = [
        stub_file
        for stub_file in stub_files
        if stub_file.relative_to(dest_dir).parts
        and stub_file.relative_to(dest_dir).parts[0] == module_root
    ]

    targets = filtered if filtered else stub_files

    for stub_file in targets[:preview_limit]:
        print(f"Generated: {stub_file.relative_to(dest_dir)}")

    remaining = len(targets) - preview_limit
    if remaining > 0:
        print(f"...and {remaining} more stub files")

    return True


def post_process_stubs(root: Path) -> None:
    """Post-process all stub files: fix headers, rename methods, fix return types."""
    workspace_root = Path(__file__).parent.parent
    rust_fixups = collect_rust_class_fixups(workspace_root)
    renamed_enums = collect_renamed_enums(workspace_root)

    for stub_file in root.rglob("*.pyi"):
        content = stub_file.read_text()
        original = content

        # Ensure proper header with D401 ignore
        content = fix_stub_header(content)

        # Rename enum variants to match PyO3 rename_all = "SCREAMING_SNAKE_CASE"
        content = rename_enum_variants(content, renamed_enums)

        # Rename methods (py_new -> __init__, etc.)
        content = rename_methods(content)

        # Restore getter/staticmethod semantics from Rust bindings metadata
        content = apply_rust_class_fixups(content, rust_fixups)

        # Rename wrapper classes to their public Python names
        content = rename_stub_classes(content, rust_fixups)

        # Escape keywords introduced by fixup renames (e.g. py_from -> from)
        content = _escape_keyword_methods(content)

        # Strip docstrings (runtime __doc__ from PyO3 is the single source)
        content = strip_docstrings(content)

        # Remove imports extracted from doc comment examples
        content = remove_docstring_imports(content)

        # Add = None default to Optional parameters that lack one
        content = add_optional_defaults(content)

        # Restore actual default values from #[pyo3(signature)] attributes
        content = apply_signature_defaults(content, rust_fixups)

        # Fix enum variant names in default values (signature defaults use Rust names)
        content = fix_enum_defaults_in_signatures(content, renamed_enums)

        # Replace forward local class defaults that are invalid inside class bodies
        content = elide_forward_class_defaults_in_signatures(content)

        # Import model symbols used without a module qualifier
        content = add_missing_model_imports(content)

        # Normalize formatting
        content = normalize_stub_content(content)

        if content != original:
            stub_file.write_text(content)


IDENTIFIER_MACRO_METHOD_FIXUPS = ClassMethodFixup(
    getters={"value"},
    staticmethods={"_safe_constructor", "from_str"},
)

INJECTABLE_STATICMETHODS = frozenset({"from_json", "from_msgpack"})

# Methods to suppress from public stubs (implementation details, not user-facing API)
SUPPRESSED_METHODS = frozenset({"__richcmp__", "_safe_constructor"})
PYMETHODS_ATTRS = frozenset({"#[pymethods]", "#[pyo3::pymethods]"})
PYCLASS_ATTR_PREFIXES = ("#[pyclass", "#[pyo3::pyclass")
PYO3_NAME_RE = re.compile(r'#\[pyo3\(\s*name\s*=\s*"([^"]+)"')
ATTR_NAME_RE = re.compile(r'\bname\s*=\s*"([^"]+)"')
RUST_IMPL_RE = re.compile(r"^\s*impl(?:\s*<[^>]+>)?\s+([A-Za-z_][A-Za-z0-9_:<>]*)\s*\{")
RUST_STRUCT_RE = re.compile(r"^\s*(?:pub\s+)?struct\s+([A-Za-z_][A-Za-z0-9_]*)\b")
RUST_FN_RE = re.compile(
    r"fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*(?:->\s*(.*?))?\s*\{",
    flags=re.DOTALL,
)
IDENTIFIER_INVOKE_RE = re.compile(
    r"identifier_for_python!\(\s*(?:crate::)?[A-Za-z_][A-Za-z0-9_:<>]*::([A-Za-z_][A-Za-z0-9_]*)\s*\);",
)
STUB_CLASS_RE = re.compile(r"^class ([A-Za-z_][A-Za-z0-9_]*)(?:\([^)]*\))?:$")
STUB_DEF_RE = re.compile(r"^\s*def ([A-Za-z_][A-Za-z0-9_]*)\(")
PYO3_SIGNATURE_RE = re.compile(r"#\[(?:pyo3|pyfunction)\(.*\bsignature\s*=\s*\(")


def _extract_pyo3_signature_defaults(attr: str) -> dict[str, str] | None:
    """
    Parse a ``#[pyo3(signature = (...))]`` attribute and return a mapping of parameter
    names to their Python-syntax default values.

    Only includes defaults that are safe to emit: a default is excluded when a
    subsequent positional parameter has no translatable default, because adding
    it would create an invalid "required after default" signature.

    """
    match = PYO3_SIGNATURE_RE.search(attr)
    if match is None:
        return None

    params_str = _extract_signature_params_str(attr, match.end() - 1)
    params_with_defaults = _resolve_signature_params(params_str)
    return _filter_safe_defaults(params_with_defaults)


def _extract_signature_params_str(attr: str, open_paren: int) -> str:
    """
    Return the content between the matching parens starting at *open_paren*.
    """
    depth = 0
    end = open_paren
    for i in range(open_paren, len(attr)):
        if attr[i] == "(":
            depth += 1
        elif attr[i] == ")":
            depth -= 1
            if depth == 0:
                end = i
                break
    return attr[open_paren + 1 : end]


def _resolve_signature_params(
    params_str: str,
) -> list[tuple[str, str | None]]:
    """
    Parse each parameter in a pyo3 signature string and translate its default to Python
    syntax.

    The ``*`` separator is dropped because pyo3-stub-gen
    does not emit it in stubs.

    """
    params: list[tuple[str, str | None]] = []

    for raw_param in _split_signature_params(params_str):
        param = raw_param.strip()
        if not param or param == "*":
            continue
        if "=" not in param:
            params.append((param, None))
            continue
        eq_pos = param.index("=")
        name = param[:eq_pos].strip()
        rust_default = param[eq_pos + 1 :].strip()
        params.append((name, _rust_default_to_python(rust_default)))
    return params


def _filter_safe_defaults(
    params: list[tuple[str, str | None]],
) -> dict[str, str] | None:
    """
    Walk right-to-left and suppress defaults that would precede a required parameter
    (one with no translatable default).
    """
    safe: dict[str, str] = {}
    saw_required = False
    for name, py_default in reversed(params):
        if py_default is not None and not saw_required:
            safe[name] = py_default
        elif py_default is None:
            saw_required = True
    return safe if safe else None


def _split_signature_params(params_str: str) -> list[str]:
    """
    Split a pyo3 signature parameter list, respecting nested parens and angle
    brackets so that defaults like ``HashMap::new()`` are kept intact.
    """
    params: list[str] = []
    depth = 0
    current: list[str] = []

    for ch in params_str:
        if ch in "(<[":
            depth += 1
            current.append(ch)
        elif ch in ")>]":
            depth -= 1
            current.append(ch)
        elif ch == "," and depth == 0:
            params.append("".join(current))
            current = []
        else:
            current.append(ch)
    if current:
        params.append("".join(current))
    return params


def _rust_default_to_python(rust_default: str) -> str | None:
    """
    Translate a Rust default value from ``#[pyo3(signature)]`` to Python syntax.

    Returns ``None`` for values that cannot be meaningfully translated (e.g.
    ``Vec::new()``), which should remain as ``...`` in the stub.

    """
    if rust_default == "None":
        return "None"
    if rust_default == "true":
        return "True"
    if rust_default == "false":
        return "False"

    # Unwrap Some(...) and recursively translate the inner value
    if rust_default.startswith("Some(") and rust_default.endswith(")"):
        inner = rust_default[5:-1].strip()
        return _rust_default_to_python(inner)

    # String literals
    if rust_default.startswith('"') and rust_default.endswith('"'):
        return rust_default

    # Numeric literals, may have underscores
    cleaned = rust_default.replace("_", "")
    try:
        int(cleaned)
        return cleaned
    except ValueError:
        pass
    try:
        float(cleaned)
        return cleaned
    except ValueError:
        pass

    # Enum variants: Type::Variant -> Type.Variant
    if "::" in rust_default and "(" not in rust_default:
        return rust_default.replace("::", ".")

    # Skip constructor calls like Vec::new(), HashMap::new(), Some(...)
    return None


BUILTIN_TYPE_NAMES = ("bool", "dict", "float", "int", "list", "set", "str")

# Sentinel class name for module-level (free) function signature defaults
_FREE_FUNCTIONS_KEY = "__module__"


def collect_rust_class_fixups(workspace_root: Path) -> dict[str, ClassMethodFixup]:
    """
    Collect getter, staticmethod, and signature default metadata from Rust PyO3
    bindings.
    """
    fixups: dict[str, ClassMethodFixup] = {}

    for rust_file in sorted(workspace_root.glob("crates/**/src/python/**/*.rs")):
        source = rust_file.read_text()
        _collect_pyclass_name_fixups(source, fixups)
        _collect_identifier_macro_fixups(source, fixups)
        _collect_pymethod_fixups(source, fixups)
        _collect_pyfunction_signature_defaults(source, fixups)

    return fixups


PYCLASS_RENAME_ALL_RE = re.compile(r'pyclass\b.*rename_all\s*=\s*"SCREAMING_SNAKE_CASE"')
RUST_ENUM_DECL_RE = re.compile(r"^\s*(?:pub\s+)?enum\s+([A-Za-z_][A-Za-z0-9_]*)\b")


def collect_renamed_enums(workspace_root: Path) -> set[str]:
    """
    Collect enum names whose pyclass attribute includes ``rename_all =
    "SCREAMING_SNAKE_CASE"``.
    """
    renamed: set[str] = set()

    for rust_file in sorted(workspace_root.glob("crates/**/src/**/*.rs")):
        source = rust_file.read_text()
        lines = source.splitlines()
        pending_attrs: list[str] = []
        i = 0

        while i < len(lines):
            stripped = lines[i].strip()

            if not stripped:
                pending_attrs.clear()
                i += 1
                continue

            if stripped.startswith(("///", "//!")):
                i += 1
                continue

            if stripped.startswith("#["):
                attribute, i = consume_rust_attribute(lines, i)
                pending_attrs.append(attribute)
                continue

            enum_match = RUST_ENUM_DECL_RE.match(lines[i])
            if enum_match is not None:
                for attr in pending_attrs:
                    if PYCLASS_RENAME_ALL_RE.search(attr):
                        renamed.add(enum_match.group(1))
                        break

            pending_attrs.clear()
            i += 1

    return renamed


def rename_enum_variants(content: str, renamed_enums: set[str]) -> str:
    """
    Rename enum variants from PascalCase to SCREAMING_SNAKE_CASE for enums whose pyclass
    has ``rename_all = "SCREAMING_SNAKE_CASE"``.
    """
    if not renamed_enums:
        return content

    lines = content.split("\n")
    result: list[str] = []
    in_renamed_enum = False

    for line in lines:
        class_match = re.match(r"^class\s+(\w+)\s*\(", line)
        if class_match:
            class_name = class_match.group(1)
            in_renamed_enum = (
                class_name in renamed_enums
                and re.search(r"\(\s*(?:enum\.)?Enum\s*\)", line) is not None
            )

        if in_renamed_enum:
            variant_match = re.match(r"^(\s+)([A-Za-z_]\w*)(\s*=\s*\.\.\.\s*)$", line)
            if variant_match:
                indent = variant_match.group(1)
                name = variant_match.group(2)
                rest = variant_match.group(3)
                new_name = to_screaming_snake_case(name)
                line = f"{indent}{new_name}{rest}"  # noqa: PLW2901

        result.append(line)

    return "\n".join(result)


def fix_enum_defaults_in_signatures(content: str, renamed_enums: set[str]) -> str:
    """
    Fix enum variant references in default values injected by
    ``apply_signature_defaults``.

    The defaults come from Rust source and use PascalCase variant names, but the stubs
    have already been renamed to SCREAMING_SNAKE_CASE.

    """
    if not renamed_enums:
        return content

    for enum_name in sorted(renamed_enums, key=len, reverse=True):
        pattern = rf"({re.escape(enum_name)}\.)([A-Z][A-Za-z0-9_]*)\b"

        def _replace(m: re.Match[str]) -> str:
            return f"{m.group(1)}{to_screaming_snake_case(m.group(2))}"

        content = re.sub(pattern, _replace, content)

    return content


FORWARD_LOCAL_CLASS_DEFAULT_RE = re.compile(
    r"=\s*(?P<class_name>[A-Za-z_][A-Za-z0-9_]*)\.[A-Za-z_][A-Za-z0-9_]*\b",
)


def _replace_forward_local_class_default(
    match: re.Match[str],
    class_positions: dict[str, int],
    current_index: int,
) -> str:
    class_name = match.group("class_name")
    class_pos = class_positions.get(class_name)
    if class_pos is None or class_pos < current_index:
        return match.group(0)
    return "= ..."


def elide_forward_class_defaults_in_signatures(content: str) -> str:
    """
    Replace local class defaults with ``...`` when the class is declared later in the
    same stub file.

    This keeps the signature shape while avoiding invalid runtime expressions
    like ``BitmexEnvironment.MAINNET`` inside a class body before
    ``BitmexEnvironment`` is defined.

    """
    lines = content.split("\n")
    class_positions = {
        match.group(1): index
        for index, line in enumerate(lines)
        if (match := STUB_CLASS_RE.match(line.strip())) is not None
    }

    if not class_positions:
        return content

    result: list[str] = []
    in_signature = False

    for index, line in enumerate(lines):
        stripped = line.strip()

        if STUB_DEF_RE.match(line):
            in_signature = True

        if in_signature:
            updated_line = FORWARD_LOCAL_CLASS_DEFAULT_RE.sub(
                lambda match, current_index=index: _replace_forward_local_class_default(
                    match,
                    class_positions,
                    current_index,
                ),
                line,
            )
        else:
            updated_line = line

        if in_signature and stripped.endswith((":", "...")):
            in_signature = False

        result.append(updated_line)

    return "\n".join(result)


def _collect_pyclass_name_fixups(source: str, fixups: dict[str, ClassMethodFixup]) -> None:
    lines = source.splitlines()
    pending_attrs: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            pending_attrs.clear()
            i += 1
            continue

        if stripped.startswith("#["):
            attribute, i = consume_rust_attribute(lines, i)
            pending_attrs.append(attribute)
            continue

        struct_match = RUST_STRUCT_RE.match(line)
        if struct_match is None:
            pending_attrs.clear()
            i += 1
            continue

        pyclass_attr = next(
            (attr for attr in pending_attrs if attr.startswith(PYCLASS_ATTR_PREFIXES)),
            None,
        )

        if pyclass_attr is not None:
            name_match = ATTR_NAME_RE.search(pyclass_attr)
            if name_match is not None:
                rust_name = struct_match.group(1)
                python_name = name_match.group(1)
                if python_name != rust_name:
                    fixups.setdefault(rust_name, ClassMethodFixup()).python_name = python_name

        pending_attrs.clear()
        i += 1


def _collect_identifier_macro_fixups(source: str, fixups: dict[str, ClassMethodFixup]) -> None:
    for class_name in IDENTIFIER_INVOKE_RE.findall(source):
        fixup = fixups.setdefault(class_name, ClassMethodFixup())
        fixup.getters.update(IDENTIFIER_MACRO_METHOD_FIXUPS.getters)
        fixup.staticmethods.update(IDENTIFIER_MACRO_METHOD_FIXUPS.staticmethods)


def _collect_pymethod_fixups(source: str, fixups: dict[str, ClassMethodFixup]) -> None:
    lines = source.splitlines()
    i = 0

    while i < len(lines):
        if lines[i].strip() not in PYMETHODS_ATTRS:
            i += 1
            continue

        j = i + 1
        while j < len(lines) and lines[j].strip().startswith("#["):
            j += 1

        if j >= len(lines):
            break

        impl_match = RUST_IMPL_RE.match(lines[j])
        if impl_match is None:
            i = j + 1
            continue

        class_name = impl_match.group(1).split("::")[-1].split("<", maxsplit=1)[0]
        brace_depth = lines[j].count("{") - lines[j].count("}")
        block_lines = [lines[j]]
        j += 1

        while j < len(lines):
            block_lines.append(lines[j])
            brace_depth += lines[j].count("{") - lines[j].count("}")
            if brace_depth <= 0:
                break
            j += 1

        fixups.setdefault(class_name, ClassMethodFixup())
        _collect_block_method_fixups(class_name, block_lines, fixups)
        i = j + 1


def _collect_pyfunction_signature_defaults(
    source: str,
    fixups: dict[str, ClassMethodFixup],
) -> None:
    """
    Collect signature defaults from ``#[pyfunction]`` free functions.

    Stores defaults under the ``_FREE_FUNCTIONS_KEY`` sentinel so they can be
    applied to module-level function stubs.

    """
    lines = source.splitlines()
    i = 0

    while i < len(lines):
        stripped = lines[i].strip()
        if not stripped.startswith("#[pyfunction"):
            i += 1
            continue

        pending_attrs, j = _collect_attrs_until_fn(lines, i)
        if j >= len(lines):
            break

        method_match, j = consume_rust_method_signature(lines, j)
        if method_match is not None:
            _register_free_function_defaults(method_match, pending_attrs, fixups)

        i = j


def _collect_attrs_until_fn(
    lines: list[str],
    start: int,
) -> tuple[list[str], int]:
    """
    Collect all attributes between a marker line and the next ``fn`` keyword.
    """
    pending_attrs: list[str] = []
    j = start
    while j < len(lines):
        attr_stripped = lines[j].strip()
        if attr_stripped.startswith("#["):
            attribute, j = consume_rust_attribute(lines, j)
            pending_attrs.append(attribute)
        elif attr_stripped.startswith(("///", "//!")):
            j += 1
        elif "fn " in attr_stripped:
            break
        else:
            j += 1
    return pending_attrs, j


def _register_free_function_defaults(
    method_match: re.Match[str],
    attrs: list[str],
    fixups: dict[str, ClassMethodFixup],
) -> None:
    """
    Register signature defaults for a free function.
    """
    rust_name = method_match.group(1)
    python_name = _python_exposed_name(rust_name, attrs, False)
    if not python_name:
        return
    for attr in attrs:
        sig_defaults = _extract_pyo3_signature_defaults(attr)
        if sig_defaults:
            fixup = fixups.setdefault(_FREE_FUNCTIONS_KEY, ClassMethodFixup())
            fixup.signature_defaults[python_name] = sig_defaults
            break


def _collect_block_method_fixups(
    class_name: str,
    block_lines: list[str],
    fixups: dict[str, ClassMethodFixup],
) -> None:
    pending_attrs: list[str] = []
    i = 1  # Skip `impl X {`

    while i < len(block_lines):
        line = block_lines[i]
        stripped = line.strip()

        if not stripped:
            pending_attrs.clear()
            i += 1
            continue

        if stripped.startswith("#["):
            attribute, i = consume_rust_attribute(block_lines, i)
            pending_attrs.append(attribute)
            continue

        if stripped.startswith(("///", "//!")):
            i += 1
            continue

        if "fn " not in stripped:
            pending_attrs.clear()
            i += 1
            continue

        method_match, i = consume_rust_method_signature(block_lines, i)
        if method_match is not None:
            register_rust_method_fixup(class_name, pending_attrs, method_match, fixups)
        pending_attrs.clear()


def consume_rust_attribute(lines: list[str], start: int) -> tuple[str, int]:
    """
    Consume a Rust attribute, including multi-line forms such as `#[allow(...)]`.
    """
    attribute_lines = [lines[start].strip()]
    bracket_depth = _bracket_depth(attribute_lines[0])
    i = start + 1

    while i < len(lines) and bracket_depth > 0:
        attribute_lines.append(lines[i].strip())
        bracket_depth += _bracket_depth(lines[i])
        i += 1

    return " ".join(attribute_lines), i


def _bracket_depth(line: str) -> int:
    """
    Count net bracket depth, skipping brackets inside double-quoted strings.
    """
    depth = 0
    in_string = False
    escaped = False

    for ch in line:
        if escaped:
            escaped = False
            continue
        if ch == "\\" and in_string:
            escaped = True
            continue
        if ch == '"':
            in_string = not in_string
        elif not in_string:
            if ch == "[":
                depth += 1
            elif ch == "]":
                depth -= 1

    return depth


def consume_rust_method_signature(
    lines: list[str],
    start: int,
) -> tuple[re.Match[str] | None, int]:
    """
    Consume a Rust method signature and return the regex match.
    """
    signature_lines = [lines[start].strip()]
    i = start + 1

    while i < len(lines) and "{" not in signature_lines[-1]:
        signature_lines.append(lines[i].strip())
        i += 1

    signature = " ".join(signature_lines)
    return RUST_FN_RE.search(signature), i


def register_rust_method_fixup(
    class_name: str,
    attrs: list[str],
    method_match: re.Match[str],
    fixups: dict[str, ClassMethodFixup],
) -> None:
    """
    Register getter, staticmethod, classmethod, and signature default metadata from a
    Rust method.
    """
    rust_name = method_match.group(1)
    params = method_match.group(2)

    is_getter = any(attr.startswith("#[getter") for attr in attrs)
    is_staticmethod = any(attr.startswith("#[staticmethod") for attr in attrs)
    is_classmethod = any(attr.startswith("#[classmethod") for attr in attrs)
    python_name = _python_exposed_name(rust_name, attrs, is_getter)
    if not python_name:
        return

    fallback_name = _python_exposed_name(rust_name, [], is_getter)
    method_names = {python_name}
    if fallback_name and fallback_name != python_name:
        method_names.add(fallback_name)

    fixup = fixups.setdefault(class_name, ClassMethodFixup())

    if fallback_name and fallback_name != python_name:
        fixup.renames[fallback_name] = python_name

    if is_getter:
        fixup.getters.update(method_names)

    _extract_method_signature_defaults(attrs, python_name, fixup)

    if is_classmethod:
        fixup.classmethods.update(method_names)
        return

    if not is_staticmethod:
        return

    fixup.staticmethods.update(method_names)

    if python_name not in INJECTABLE_STATICMETHODS:
        return

    rendered = render_missing_staticmethod_stub(class_name, python_name, params)
    if rendered is not None:
        fixup.injected_staticmethods[python_name] = rendered


def _extract_method_signature_defaults(
    attrs: list[str],
    python_name: str,
    fixup: ClassMethodFixup,
) -> None:
    """
    Extract parameter defaults from the first ``#[pyo3(signature)]`` attribute.
    """
    for attr in attrs:
        sig_defaults = _extract_pyo3_signature_defaults(attr)
        if sig_defaults:
            fixup.signature_defaults[python_name] = sig_defaults
            return


def _python_exposed_name(rust_name: str, attrs: list[str], is_getter: bool) -> str | None:
    for attr in attrs:
        name_match = PYO3_NAME_RE.search(attr)
        if name_match:
            return name_match.group(1)

    if rust_name == "py_new":
        return "__init__"

    if rust_name.startswith("py_") and not keyword.iskeyword(rust_name[3:]):
        return rust_name[3:]

    if is_getter and rust_name.startswith("get_"):
        return rust_name[4:]

    return rust_name


def render_missing_staticmethod_stub(
    class_name: str,
    method_name: str,
    params: str,
) -> str | None:
    """
    Render a conservative stub for missing deserializer helpers.
    """
    params = params.strip()

    if method_name not in INJECTABLE_STATICMETHODS:
        return None

    if params.count(":") != 1 or not params.startswith("data:"):
        return None

    return f"    @staticmethod\n    def {method_name}(data: typing.Any) -> {class_name}: ..."


def apply_rust_class_fixups(
    content: str,
    class_fixups: dict[str, ClassMethodFixup],
) -> str:
    """
    Rewrite generated class methods using Rust source metadata.
    """
    lines = content.split("\n")
    result: list[str] = []
    i = 0

    while i < len(lines):
        class_match = STUB_CLASS_RE.match(lines[i].strip())
        if class_match is None:
            result.append(lines[i])
            i += 1
            continue

        class_name = class_match.group(1)
        j = i + 1
        while j < len(lines):
            stripped = lines[j].strip()
            if stripped and not lines[j].startswith((" ", "\t")):
                break
            j += 1

        fixup = class_fixups.get(class_name)
        if fixup is None:
            result.extend(lines[i:j])
        else:
            result.extend(apply_class_block_fixups(lines[i:j], class_name, fixup))
        i = j

    return "\n".join(result)


def rename_stub_classes(content: str, class_fixups: dict[str, ClassMethodFixup]) -> str:
    """
    Rename generated class names to match public Python names from `#[pyclass(name =
    ...)]`.
    """
    class_renames = {
        rust_name: fixup.python_name
        for rust_name, fixup in class_fixups.items()
        if fixup.python_name and fixup.python_name != rust_name
    }

    if not class_renames:
        return content

    for rust_name in sorted(class_renames, key=len, reverse=True):
        content = re.sub(rf"\b{re.escape(rust_name)}\b", class_renames[rust_name], content)

    return content


def apply_class_block_fixups(
    class_block: list[str],
    class_name: str,
    fixup: ClassMethodFixup,
) -> list[str]:
    header = class_block[0]
    body_lines = class_block[1:]
    result = [header]
    seen_methods: set[str] = set()
    i = 0

    while i < len(body_lines):
        parsed = parse_stub_method_block(body_lines, i)
        if parsed is None:
            result.append(body_lines[i])
            i += 1
            continue

        method_name, method_block, next_index = parsed
        resolved_name = fixup.renames.get(method_name, method_name)
        is_duplicate = method_name in seen_methods or resolved_name in seen_methods
        seen_methods.add(method_name)
        seen_methods.add(resolved_name)
        is_suppressed = method_name in SUPPRESSED_METHODS or resolved_name in SUPPRESSED_METHODS
        if not is_duplicate and not is_suppressed:
            result.extend(rewrite_stub_method_block(method_name, method_block, fixup))
        i = next_index

    missing = [
        fixup.injected_staticmethods[name]
        for name in sorted(fixup.injected_staticmethods)
        if name not in seen_methods
    ]

    if missing:
        trailing_blank_lines: list[str] = []
        while result and not result[-1].strip():
            trailing_blank_lines.append(result.pop())

        if result and result[-1].strip():
            result.append("")
        for index, method in enumerate(missing):
            result.extend(method.split("\n"))

            if index != len(missing) - 1:
                result.append("")
        result.extend(reversed(trailing_blank_lines))

    return result


def parse_stub_method_block(
    lines: list[str],
    start: int,
) -> tuple[str, list[str], int] | None:
    """
    Parse a method block from a stub class body.
    """
    if start >= len(lines) or not lines[start].strip():
        return None

    method_start, def_index = find_stub_method_start(lines, start)
    if method_start is None or def_index is None:
        return None

    signature_lines, signature_end = consume_stub_signature(lines, def_index)
    method_end = find_stub_method_end(lines, signature_lines, signature_end)
    method_block = lines[method_start:method_end]
    def_line = next(line for line in method_block if line.lstrip().startswith("def "))
    method_match = STUB_DEF_RE.match(def_line)
    if method_match is None:
        return None

    return method_match.group(1), method_block, method_end


def find_stub_method_start(lines: list[str], start: int) -> tuple[int | None, int | None]:
    """
    Find the start and definition line for a stub method block.
    """
    i = start
    while i < len(lines) and lines[i].startswith("    @"):
        i += 1

    if i >= len(lines) or not lines[i].startswith("    def "):
        return None, None

    return start, i


def consume_stub_signature(lines: list[str], start: int) -> tuple[list[str], int]:
    """
    Consume a stub method signature, including multi-line forms.
    """
    signature_lines = [lines[start]]
    i = start + 1

    while i < len(lines):
        if signature_lines[-1].rstrip().endswith(":") or signature_lines[-1].rstrip().endswith(
            "...",
        ):
            break
        signature_lines.append(lines[i])
        i += 1

    return signature_lines, i


def find_stub_method_end(
    lines: list[str],
    signature_lines: list[str],
    signature_end: int,
) -> int:
    """
    Find the end index for a stub method block.
    """
    if signature_lines[-1].rstrip().endswith("..."):
        return signature_end

    method_indent = 4
    method_end = signature_end
    while method_end < len(lines):
        stripped = lines[method_end].strip()
        if not stripped:
            method_end += 1
            continue
        indent = len(lines[method_end]) - len(lines[method_end].lstrip())
        if indent <= method_indent:
            break
        method_end += 1

    return method_end


def split_method_block(
    method_block: list[str],
) -> tuple[list[str], str, list[str]]:
    """
    Split a stub method block into decorators, signature text, and remainder.
    """
    decorators: list[str] = []
    body_start = 0
    while body_start < len(method_block) and method_block[body_start].startswith("    @"):
        decorators.append(method_block[body_start])
        body_start += 1

    signature_lines: list[str] = []
    signature_end = body_start
    while signature_end < len(method_block):
        signature_lines.append(method_block[signature_end])
        if signature_lines[-1].rstrip().endswith(":") or signature_lines[-1].rstrip().endswith(
            "...",
        ):
            signature_end += 1
            break
        signature_end += 1

    return decorators, "\n".join(signature_lines), method_block[signature_end:]


def _has_decorator(decorators: list[str], name: str) -> bool:
    return any(line.strip() == name for line in decorators)


def rewrite_stub_method_block(
    method_name: str,
    method_block: list[str],
    fixup: ClassMethodFixup,
) -> list[str]:
    """
    Apply decorator, receiver, and rename fixes to a stub method block.
    """
    needs_fixup = (
        method_name in fixup.getters
        or method_name in fixup.staticmethods
        or method_name in fixup.classmethods
        or method_name in fixup.renames
    )

    if not needs_fixup:
        return method_block

    decorators, signature_text, remainder = split_method_block(method_block)

    if method_name in fixup.renames:
        new_name = fixup.renames[method_name]
        signature_text = re.sub(
            rf"\bdef {re.escape(method_name)}\(",
            f"def {new_name}(",
            signature_text,
            count=1,
        )

    if method_name in fixup.staticmethods:
        signature_text = drop_stub_method_receiver(signature_text)

        if not _has_decorator(decorators, "@staticmethod"):
            decorators.append("    @staticmethod")
    elif method_name in fixup.classmethods:
        signature_text = replace_self_with_cls(signature_text)

        if not _has_decorator(decorators, "@classmethod"):
            decorators.append("    @classmethod")

    if method_name in fixup.getters and not _has_decorator(decorators, "@property"):
        decorators.append("    @property")

    return decorators + signature_text.split("\n") + remainder


def drop_stub_method_receiver(signature_text: str) -> str:
    """
    Remove an inserted instance receiver from a stub signature.
    """
    signature_text = re.sub(
        r"(\bdef\s+\w+\(\n)([ \t]*)(?:self|cls)\s*,\s*",
        r"\1\2",
        signature_text,
        count=1,
    )
    signature_text = re.sub(
        r"(\bdef\s+\w+\(\n)([ \t]*)(?:self|cls)\s*(?=\n)",
        r"\1",
        signature_text,
        count=1,
    )
    signature_text = re.sub(
        r"(\bdef\s+\w+\()\s*(?:self|cls)\s*,\s*",
        r"\1",
        signature_text,
        count=1,
        flags=re.DOTALL,
    )
    signature_text = re.sub(
        r"(\bdef\s+\w+\()\s*(?:self|cls)\s*(?=\))",
        r"\1",
        signature_text,
        count=1,
        flags=re.DOTALL,
    )
    return signature_text


def replace_self_with_cls(signature_text: str) -> str:
    """
    Replace self receiver with cls for classmethod signatures.
    """
    return re.sub(r"\bself\b", "cls", signature_text, count=1)


def fix_stub_header(content: str) -> str:
    """
    Ensure stub file has proper header with ruff ignores.
    """
    lines = content.split("\n")

    # Find where the header ends (first non-comment, non-empty line)
    header_end = 0

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            header_end = i
            break

    # Check if D401 is already in the header
    header = "\n".join(lines[:header_end])
    if "D401" in header:
        return content

    # Replace or prepend header
    body = "\n".join(lines[header_end:])
    return STUB_HEADER + "\n" + body


def relocate_classes_from_libnautilus(root: Path) -> None:
    """
    Extract specific classes from _libnautilus and merge into target modules.
    """
    lib_stub = find_libnautilus_stub(root)
    if lib_stub is None:
        return

    source = lib_stub.read_text()
    remaining = source

    for module_suffix, fixup in MODULE_FIXUPS.items():
        if not fixup.classes:
            continue

        remaining, blocks = extract_class_blocks(remaining, fixup.classes)

        if not blocks:
            continue

        # Strip self-references: when relocating into "model", replace
        # "model.X" with "X" since X is defined in the same module.
        blocks = [re.sub(rf"\b{module_suffix}\.", "", block) for block in blocks]

        module_parts = module_suffix.split(".")
        module_path = root.joinpath(*module_parts)
        module_path.mkdir(parents=True, exist_ok=True)
        target_file = module_path / "__init__.pyi"

        # Read existing content if file exists
        if target_file.exists():
            existing = target_file.read_text()
        else:
            existing = ""

        # Merge the new class blocks into existing content
        merged = merge_stub_content(existing, blocks, fixup)
        target_file.write_text(merged)

    # Clean up the remaining _libnautilus content
    remaining = clean_orphaned_decorators(remaining)

    # Remove extracted class names from __all__
    all_extracted_classes: set[str] = set()
    for fixup in MODULE_FIXUPS.values():
        all_extracted_classes.update(fixup.classes)
    remaining = remove_from_all_list(remaining, all_extracted_classes)

    lib_stub.write_text(remaining.strip() + "\n")


def find_libnautilus_stub(root: Path) -> Path | None:
    """
    Find the _libnautilus stub file (handles both old and new formats).
    """
    # New format: _libnautilus/__init__.pyi (pyo3-stub-gen >= 0.18.0)
    new_path = root / "_libnautilus" / "__init__.pyi"
    if new_path.exists():
        return new_path

    # Old format: _libnautilus.pyi
    old_path = root / "_libnautilus.pyi"
    if old_path.exists():
        return old_path

    return None


def merge_stub_content(existing: str, new_blocks: list[str], fixup: StubFixup) -> str:
    """
    Merge new class blocks into existing stub content.
    """
    lines = existing.split("\n") if existing else []

    # Collect existing imports and find body start
    existing_imports: set[str] = set()
    body_lines: list[str] = []
    in_all_block = False

    for line in lines:
        stripped = line.strip()

        # Skip comments and empty lines at the start
        if stripped.startswith("#"):
            continue

        # Handle __all__ block (may span multiple lines)
        if stripped.startswith("__all__") or in_all_block:
            in_all_block = "]" not in line
            continue

        # Collect imports
        if stripped.startswith(("import ", "from ")):
            existing_imports.add(stripped)
            continue

        # Everything else is body content
        body_lines.append(line)

    existing_body = "\n".join(body_lines).strip()

    # Build new imports
    all_imports = existing_imports | set(fixup.imports)
    # Standard imports that are always needed
    all_imports.add("import builtins")
    all_imports.add("import typing")

    # Sort imports
    sorted_imports = sorted(all_imports, key=lambda x: (not x.startswith("import "), x))

    # Build __all__ if specified
    all_section = ""

    if fixup.all_exports:
        all_list = ", ".join(f'"{name}"' for name in sorted(fixup.all_exports))
        all_section = f"__all__ = [{all_list}]\n"

    # Combine everything
    parts = [STUB_HEADER, "", "\n".join(sorted_imports), ""]

    if all_section:
        parts.append(all_section)
    if existing_body:
        parts.append(existing_body)
    if new_blocks:
        parts.append("\n\n".join(new_blocks))
    parts.append("")

    content = "\n".join(parts)
    content = normalize_stub_content(content)
    return content


def extract_class_blocks(
    source: str,
    class_names: tuple[str, ...],
) -> tuple[str, list[str]]:
    """
    Extract class definitions from source, including any preceding decorators.
    """
    lines = source.split("\n")
    blocks: list[str] = []
    lines_to_remove: set[int] = set()

    for class_name in class_names:
        class_pattern = re.compile(rf"^class {class_name}(?:\([^)]*\))?:")

        for i, line in enumerate(lines):
            if not class_pattern.match(line):
                continue

            # Found the class, now find decorators above it
            start = i
            while start > 0 and lines[start - 1].strip().startswith("@"):
                start -= 1

            # Find the end of the class body
            end = i + 1
            while end < len(lines):
                next_line = lines[end]

                # Empty lines are part of the class
                if not next_line.strip():
                    end += 1
                    continue

                # Indented lines are part of the class body
                if next_line.startswith((" ", "\t")):
                    end += 1
                    continue

                # Non-indented, non-empty line marks the end
                break

            # Extract the block
            block_lines = lines[start:end]
            block = "\n".join(block_lines).rstrip()
            block = rename_methods(block)
            blocks.append(block)

            # Mark lines for removal
            for j in range(start, end):
                lines_to_remove.add(j)

            break

    # Build remaining source excluding extracted lines
    remaining_lines = [line for i, line in enumerate(lines) if i not in lines_to_remove]
    remaining = "\n".join(remaining_lines)

    return remaining, blocks


def rename_methods(content: str) -> str:
    """
    Apply method renames and fix return type annotations.
    """
    for old_name, new_name in METHOD_RENAMES.items():
        content = re.sub(rf"\bdef\s+{old_name}\s*\(", rf"def {new_name}(", content)

    # Fix __init__ return type to be None
    content = re.sub(r"(def __init__\([^)]*\))\s*->\s*[^:]+:", r"\1 -> None:", content)

    # Strip py_ prefix from function definitions and __all__ entries (project convention:
    # Rust uses py_ prefix with #[pyo3(name = "...")] to expose without the prefix).
    # pyo3-stub-gen picks up the rename for def lines but uses the Rust name in __all__.
    # Skip stripping when the result would be a Python keyword.
    content = re.sub(
        r"\bdef py_(\w+)\s*\(",
        lambda m: f"def {m.group(1)}(" if not keyword.iskeyword(m.group(1)) else m.group(0),
        content,
    )
    content = re.sub(
        r'"py_(\w+)"',
        lambda m: f'"{m.group(1)}"' if not keyword.iskeyword(m.group(1)) else m.group(0),
        content,
    )

    # Escape Python keywords used as method names (e.g. def from(self) -> def from_(self))
    content = _escape_keyword_methods(content)

    # Escape Python keywords used as parameter names (e.g. from -> from_)
    content = _escape_keyword_params(content)

    # Escape Python keywords used as enum variant names (e.g. None = ... -> None_ = ...)
    content = _escape_keyword_variants(content)

    return content


def _escape_keyword_methods(content: str) -> str:
    """
    Append underscore to Python keywords used as method or property names.
    """

    def _escape_match(m: re.Match[str]) -> str:
        name = m.group(1)
        if keyword.iskeyword(name):
            return f"def {name}_("
        return m.group(0)

    return re.sub(r"\bdef ([a-z]\w*)\(", _escape_match, content)


def _escape_keyword_params(content: str) -> str:
    """
    Append underscore to Python keywords used as parameter names in signatures.

    Targets parameters in function/method signatures: matches a keyword preceded by a
    comma-space or opening paren, followed by a colon (the type annotation separator).

    """

    def _escape_match(m: re.Match[str]) -> str:
        name = m.group(2)
        if keyword.iskeyword(name):
            return f"{m.group(1)}{name}_:"
        return m.group(0)

    # Match parameter names preceded by (, or ", " and followed by ":"
    return re.sub(r"([(,]\s*)(\w+):", _escape_match, content)


def _escape_keyword_variants(content: str) -> str:
    """
    Escape Python keywords used as enum variant names (e.g. ``None = ...``).
    """

    def _escape_match(m: re.Match[str]) -> str:
        name = m.group(2)
        if keyword.iskeyword(name):
            return f"{m.group(1)}{name}_"
        return m.group(0)

    # Match indented enum variants: leading whitespace + identifier + " = ..."
    return re.sub(r"^(\s+)(\w+)(?= = \.\.\.)", _escape_match, content, flags=re.MULTILINE)


_TRIPLE_QUOTE_RE = re.compile(r'^(\s*)r?"""')


def strip_docstrings(content: str) -> str:
    """
    Strip all docstring blocks from stub content.

    Runtime ``__doc__`` set by PyO3 from Rust ``///`` comments is the single
    source. Stubs provide type information only.

    Handles three cases:
    - Class-level docstrings (removed entirely).
    - Method/function body docstrings (replaced with ``...``).
    - Standalone ``def`` lines already ending with ``...`` (left alone).

    """
    lines = content.split("\n")
    result: list[str] = []
    i = 0

    while i < len(lines):
        m = _TRIPLE_QUOTE_RE.match(lines[i])
        if m is None:
            result.append(lines[i])
            i += 1
            continue

        # Find closing triple-quote
        j = i
        if '"""' in lines[i][lines[i].index('"""') + 3 :]:
            j = i  # Single-line docstring
        else:
            j = i + 1
            while j < len(lines) and '"""' not in lines[j]:
                j += 1

        # Check context: is the previous non-blank line a def/class?
        prev_idx = len(result) - 1
        while prev_idx >= 0 and not result[prev_idx].strip():
            prev_idx -= 1

        if prev_idx >= 0 and result[prev_idx].strip().endswith(":"):
            prev_stripped = result[prev_idx].strip()
            if prev_stripped.startswith(("def ", "async def ")):
                # Method/function body docstring: replace with ...
                indent = m.group(1)
                result.append(f"{indent}...")
            # Class-level docstring: drop entirely
        # Else: standalone docstring, drop

        i = j + 1

    return "\n".join(result)


# Imports that pyo3-stub-gen extracts from doc comment code examples.
# These reference modules outside the v2 package and should not appear in stubs.
_DOCSTRING_IMPORTS: set[str] = {
    "from nautilus_trader.model.custom import customdataclass_pyo3",
    "from nautilus_trader.model import register_custom_data_class",
}


def remove_docstring_imports(content: str) -> str:
    """
    Remove module-level imports that pyo3-stub-gen extracted from doc comment examples.
    """
    lines = content.split("\n")
    lines = [line for line in lines if line.strip() not in _DOCSTRING_IMPORTS]
    return "\n".join(lines)


def _split_params(params_str: str) -> list[str]:
    """
    Split a parameter string on commas, respecting nested brackets.
    """
    parts: list[str] = []
    depth = 0
    start = 0

    for i, ch in enumerate(params_str):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "," and depth == 0:
            parts.append(params_str[start:i].strip())
            start = i + 1
    tail = params_str[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def _is_optional_param(param: str) -> bool:
    """
    Check if a parameter has an Optional type annotation at the top level.
    """
    colon = param.find(":")
    if colon < 0:
        return False
    type_part = param[colon + 1 :].split("=")[0].strip()
    if "Optional[" in type_part:
        return True
    # Check for `| None` only at bracket depth 0
    depth = 0

    for i, ch in enumerate(type_part):
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "|" and depth == 0 and "None" in type_part[i + 1 : i + 7].strip():
            return True
    return False


def _has_default(param: str) -> bool:
    """
    Check if a parameter has a default value (respecting brackets).
    """
    depth = 0

    for ch in param:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        elif ch == "=" and depth == 0 and ":" in param[: param.index(ch)]:
            return True
    return False


def _find_matching_paren(line: str, start: int) -> int:
    """
    Return the index of the closing paren matching the open paren at *start*.
    """
    depth = 0

    for i in range(start, len(line)):
        if line[i] == "(":
            depth += 1
        elif line[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    return -1


def _fix_optional_defaults_in_line(line: str) -> str:
    """
    Add ``= ...`` to trailing Optional params in a single def line.
    """
    paren_start = line.find("(")
    if paren_start < 0:
        return line

    paren_end = _find_matching_paren(line, paren_start)
    if paren_end < 0:
        return line

    params = _split_params(line[paren_start + 1 : paren_end])
    if not params:
        return line

    changed = False

    for i in range(len(params) - 1, -1, -1):
        p = params[i]
        if _has_default(p):
            continue
        if _is_optional_param(p):
            params[i] = p + " = ..."
            changed = True
        else:
            break

    if not changed:
        return line
    return line[: paren_start + 1] + ", ".join(params) + line[paren_end:]


def add_optional_defaults(content: str) -> str:
    """
    Add ``= ...`` to trailing Optional parameters that lack a default value.

    pyo3-stub-gen omits defaults for ``Option<T>`` parameters declared in
    ``#[pyo3(signature)]`` when the ``infer_signature`` feature is off.
    Using ``...`` (ellipsis) rather than ``None`` because the actual default
    may be a non-None value like ``Some(true)`` or ``Some(30)``.

    Only adds defaults to trailing Optional params (right-to-left from the end
    of the parameter list) to avoid placing a defaulted parameter before a
    required one.

    """
    lines = content.split("\n")
    result = []

    for line in lines:
        if "def " in line and ("Optional" in line or "| None" in line):
            result.append(_fix_optional_defaults_in_line(line))
        else:
            result.append(line)
    return "\n".join(result)


def apply_signature_defaults(
    content: str,
    class_fixups: dict[str, ClassMethodFixup],
) -> str:
    """
    Replace ``= ...`` placeholders and add missing defaults using values extracted from
    ``#[pyo3(signature)]`` attributes.
    """
    all_defaults = _build_defaults_lookup(class_fixups)
    if not all_defaults:
        return content

    lines = content.split("\n")
    result: list[str] = []
    current_class: str | None = None
    current_defaults: dict[str, str] | None = None
    in_signature = False

    for line in lines:
        stripped = line.strip()

        class_match = STUB_CLASS_RE.match(stripped)
        if class_match:
            current_class = class_match.group(1)
            current_defaults = None
            in_signature = False
            result.append(line)
            continue

        if stripped and not line.startswith((" ", "\t")):
            current_class = None
            current_defaults = None
            in_signature = False

        def_match = STUB_DEF_RE.match(line)
        if def_match:
            method_name = def_match.group(1)
            key = (
                (current_class, method_name)
                if current_class
                else (_FREE_FUNCTIONS_KEY, method_name)
            )
            current_defaults = all_defaults.get(key)
            in_signature = current_defaults is not None

        if in_signature and current_defaults is not None:
            result.append(_apply_defaults_to_line(line, current_defaults))

            if stripped.endswith((":", "...")):
                in_signature = False
        else:
            result.append(line)

    return "\n".join(result)


def _build_defaults_lookup(
    class_fixups: dict[str, ClassMethodFixup],
) -> dict[tuple[str | None, str], dict[str, str]]:
    """
    Build a flat lookup from ``(class_name, method_name)`` to parameter defaults,
    accounting for pyclass name renames.
    """
    all_defaults: dict[tuple[str | None, str], dict[str, str]] = {}

    for rust_class, fixup in class_fixups.items():
        python_class = fixup.python_name or rust_class
        for method_name, defaults in fixup.signature_defaults.items():
            all_defaults[(python_class, method_name)] = defaults
            if python_class != rust_class:
                all_defaults[(rust_class, method_name)] = defaults
    return all_defaults


def _apply_defaults_to_line(line: str, defaults: dict[str, str]) -> str:
    """
    Apply known defaults to parameter declarations on a single line.

    Handles both:
    - Replacing ``= ...`` with the actual default
    - Adding ``= <default>`` to parameters that have no default in the stub

    """
    for param_name, py_default in defaults.items():
        param_pattern = re.compile(rf"\b{re.escape(param_name)}\s*:")
        param_match = param_pattern.search(line)
        if param_match is None:
            continue

        colon_pos = param_match.end() - 1
        type_start = colon_pos + 1
        end_pos, eq_pos, has_ellipsis = _scan_param_type(line, type_start)

        type_text = line[type_start : eq_pos if eq_pos >= 0 else end_pos]
        qualified = _qualify_enum_default(py_default, type_text)

        if has_ellipsis:
            before_eq = line[:eq_pos].rstrip()
            after_dots = line[eq_pos:]
            after_dots = re.sub(r"=\s*(?:\w+\.)?\.\.\.", f"= {qualified}", after_dots, count=1)
            line = before_eq + " " + after_dots
        elif eq_pos < 0:
            line = line[:end_pos] + f" = {qualified}" + line[end_pos:]

    return line


def _scan_param_type(line: str, start: int) -> tuple[int, int, bool]:
    """
    Scan a parameter type annotation from *start*, respecting bracket depth.

    Returns ``(end_pos, eq_pos, has_ellipsis)`` where *end_pos* is the index
    of the first top-level comma or close-paren, *eq_pos* is the index of a
    top-level ``=`` (or -1 if none), and *has_ellipsis* is ``True`` when the
    existing default value is ``...``.

    """
    depth = 0
    end_pos = len(line)
    for i in range(start, len(line)):
        ch = line[i]
        if ch in "([":
            depth += 1
        elif ch in ")]":
            if depth > 0:
                depth -= 1
            else:
                return i, -1, False
        elif ch == "," and depth == 0:
            return i, -1, False
        elif ch == "=" and depth == 0:
            rest = line[i + 1 :].lstrip()

            # Match both plain `...` and pyo3-stub-gen's malformed `model....`
            is_ellipsis = rest.startswith("...") or re.match(r"\w+\.\.\.\.", rest)
            return end_pos, i, bool(is_ellipsis)
    return end_pos, -1, False


def _qualify_enum_default(py_default: str, type_text: str) -> str:
    """
    Qualify an enum default value with its module prefix when the type annotation uses a
    qualified form like ``model.BookType``.

    For example, if the default is ``BookType.L1_MBP`` and the type text
    contains ``model.BookType``, returns ``model.BookType.L1_MBP``.

    """
    if "." not in py_default:
        return py_default

    dot_pos = py_default.index(".")
    type_name = py_default[:dot_pos]

    qualified_pattern = re.compile(rf"(\w+)\.{re.escape(type_name)}\b")
    match = qualified_pattern.search(type_text)
    if match:
        module = match.group(1)
        return f"{module}.{py_default}"

    return py_default


def add_missing_model_imports(content: str) -> str:
    """
    Import exported model symbols when generated annotations use them unqualified.
    """
    model_import = "from nautilus_trader import model"
    if model_import not in content:
        return content

    defined_names = {
        match.group(1)
        for match in re.finditer(
            r"^class\s+([A-Za-z_][A-Za-z0-9_]*)\b",
            content,
            flags=re.MULTILINE,
        )
    }

    missing_imports = []

    for name in sorted(MODEL_EXPORTS):
        if name in defined_names:
            continue
        if f"from nautilus_trader.model import {name}" in content:
            continue
        if re.search(rf"(?<![.\w]){re.escape(name)}(?![\w])", content) is None:
            continue
        missing_imports.append(name)

    if not missing_imports:
        return content

    injected_imports = "\n".join(
        f"from nautilus_trader.model import {name}" for name in missing_imports
    )
    return content.replace(model_import, f"{model_import}\n{injected_imports}", 1)


def _line_contains_name_to_remove(line: str, names_to_remove: set[str]) -> bool:
    """
    Check if line contains any of the names to remove.
    """
    return any(f'"{name}"' in line for name in names_to_remove)


def _strip_empty_all_block(lines: list[str]) -> list[str]:
    """
    Remove empty __all__ block and trailing blank line.
    """
    result: list[str] = []
    skip_next_empty = False

    for line in lines:
        stripped = line.strip()
        if stripped.startswith("__all__") or stripped in ("__all__ = []", "]", "["):
            skip_next_empty = True
            continue
        if skip_next_empty and not stripped:
            skip_next_empty = False
            continue
        result.append(line)

    return result


def remove_from_all_list(source: str, names_to_remove: set[str]) -> str:
    """
    Remove specified names from __all__ list in source.
    """
    if not names_to_remove:
        return source

    lines = source.split("\n")
    result: list[str] = []
    in_all_block = False
    all_empty = True

    for line in lines:
        stripped = line.strip()

        if stripped.startswith("__all__"):
            in_all_block = True

        if not in_all_block:
            result.append(line)
            continue

        should_skip = _line_contains_name_to_remove(line, names_to_remove)

        if "]" in line:
            in_all_block = False

        if not should_skip:
            result.append(line)
            # Track if __all__ has any remaining entries
            if stripped and stripped not in ("__all__ = [", "__all__ = []", "[", "]"):
                all_empty = False

    if all_empty:
        return "\n".join(_strip_empty_all_block(result))

    return "\n".join(result)


def clean_orphaned_decorators(source: str) -> str:
    """
    Remove orphaned decorator lines that aren't followed by a definition.
    """
    lines = source.split("\n")
    result: list[str] = []
    i = 0

    while i < len(lines):
        line = lines[i]

        if line.strip().startswith("@"):
            # Look ahead for class/def or more decorators
            j = i + 1
            while j < len(lines) and lines[j].strip().startswith("@"):
                j += 1

            if j < len(lines) and (
                lines[j].strip().startswith("class ") or lines[j].strip().startswith("def ")
            ):
                result.append(line)
            else:
                # Orphaned decorator, skip it
                i += 1
                continue
        else:
            result.append(line)

        i += 1

    return "\n".join(result)


def normalize_builtin_type_names(content: str) -> str:
    """
    Replace noisy `builtins.X` spellings with bare builtin type names.
    """
    names = "|".join(BUILTIN_TYPE_NAMES)
    pattern = re.compile(rf"\bbuiltins\.({names})\b")
    content = pattern.sub(lambda match: match.group(1), content)

    if "builtins." not in content:
        content = re.sub(r"^import builtins\s*\n", "", content, flags=re.MULTILINE)

    return content


def normalize_stub_content(content: str) -> str:
    """
    Normalize type hints and formatting in stub content.
    """
    # Replace enum.Enum with Enum when "from enum import Enum" is present
    if "from enum import Enum" in content:
        content = re.sub(r"\benum\.Enum\b", "Enum", content)

    content = normalize_builtin_type_names(content)

    # Fix module references when using "from X import Y" style imports
    # e.g. nautilus_trader.model.X -> model.X
    if "from nautilus_trader import model" in content:
        content = re.sub(r"\bnautilus_trader\.model\.", "model.", content)
    if "from nautilus_trader import infrastructure" in content:
        content = re.sub(r"\bnautilus_trader\.infrastructure\.", "infrastructure.", content)

    # Fix malformed defaults where module prefix is prepended to ellipsis
    # e.g. "model...." -> "..." (pyo3-stub-gen adds prefix to "..." repr)
    content = re.sub(r"= \w+\.\.\.\.", "= ...", content)

    # Normalize multiple blank lines to maximum of two
    content = re.sub(r"\n{4,}", "\n\n\n", content)

    # Ensure single newline at end
    content = content.rstrip() + "\n"

    return content


RUST_TO_PYTHON_TYPE: dict[str, str] = {
    "&str": "str",
    "&'static str": "str",
    "u8": "int",
    "u16": "int",
    "u32": "int",
    "u64": "int",
    "i8": "int",
    "i16": "int",
    "i32": "int",
    "i64": "int",
    "f32": "float",
    "f64": "float",
    "bool": "bool",
}

M_ADD_CONST_RE = re.compile(
    r'm\.add\(\s*(?:stringify!\((\w+)\)|"(\w+)")\s*,\s*(.+?)\s*\)\s*\?',
)

RUST_CONST_DEF_RE = re.compile(
    r"pub\s+(?:const|static)\s+(\w+)\s*:\s*([^=;]+)",
)


@dataclass(frozen=True)
class ModuleConstant:
    """
    A constant exported to Python via ``m.add()``.
    """

    name: str
    python_type: str


def collect_module_constants(workspace_root: Path) -> dict[str, list[ModuleConstant]]:
    """
    Collect module-level constants exported via ``m.add()`` in pymodule definitions.

    Returns a mapping of stub module path (e.g. ``"core"``, ``"hyperliquid"``) to
    constant declarations.

    """
    constants: dict[str, list[ModuleConstant]] = {}

    for mod_rs in sorted(workspace_root.glob("crates/**/src/python/mod.rs")):
        crate_dir = mod_rs.parent.parent.parent
        module_path = _derive_module_path(crate_dir, workspace_root)
        source = mod_rs.read_text()

        for match in M_ADD_CONST_RE.finditer(source):
            name = match.group(1) or match.group(2)
            value_expr = match.group(3).strip()

            if "get_type" in value_expr:
                continue

            python_type = _infer_constant_python_type(name, value_expr, crate_dir)
            constants.setdefault(module_path, []).append(
                ModuleConstant(name, python_type),
            )

    return constants


def _derive_module_path(crate_dir: Path, workspace_root: Path) -> str:
    """
    Derive the stub module path from a crate directory.

    The ``adapters`` directory is organizational only and is not part of
    the module path, so ``crates/adapters/bybit`` maps to ``"bybit"``.

    """
    relative = crate_dir.relative_to(workspace_root / "crates")
    parts = [p for p in relative.parts if p != "adapters"]
    return ".".join(parts)


def _infer_constant_python_type(
    const_name: str,
    value_expr: str,
    crate_dir: Path,
) -> str:
    """
    Look up a Rust constant definition and return its Python type.
    """
    # The Rust identifier may differ from the Python name (e.g. HIGH_PRECISION
    # exports HIGH_PRECISION_MODE), so extract the last path segment from the
    # value expression as a fallback lookup name.
    rust_name = value_expr.rsplit("::", maxsplit=1)[-1].strip()
    candidates = [const_name]
    if rust_name != const_name and rust_name.isidentifier():
        candidates.append(rust_name)

    for rs_file in crate_dir.glob("src/**/*.rs"):
        source_lines = rs_file.read_text().splitlines()
        for name in candidates:
            for line in source_lines:
                match = re.match(
                    rf"pub\s+(?:const|static)\s+{re.escape(name)}\s*:\s*([^=;]+)",
                    line.strip(),
                )

                if match:
                    rust_type = match.group(1).strip()
                    return RUST_TO_PYTHON_TYPE.get(rust_type, "typing.Any")

    return "typing.Any"


def inject_module_constants(root: Path, workspace_root: Path) -> None:
    """
    Inject module-level constants into stub files and update ``__all__``.
    """
    constants = collect_module_constants(workspace_root)

    for module_path, const_list in constants.items():
        parts = module_path.split(".")
        stub_file = root.joinpath(*parts, "__init__.pyi")

        if not stub_file.exists():
            continue

        content = stub_file.read_text()
        original = content

        new_names = [c.name for c in const_list if f"\n{c.name}:" not in content]
        if not new_names:
            continue

        content = _add_names_to_all(content, new_names)

        const_block = "\n".join(f"{c.name}: {c.python_type}" for c in const_list)
        content = _insert_constants_after_all(content, const_block)

        if content != original:
            stub_file.write_text(content)


def _add_names_to_all(content: str, names: list[str]) -> str:
    """
    Add names to the ``__all__`` list, maintaining sorted order.
    """
    match = re.search(r"__all__\s*=\s*\[(.*?)]", content, re.DOTALL)
    if match is None:
        return content

    existing = re.findall(r'"(\w+)"', match.group(1))
    all_names = sorted(set(existing) | set(names))

    items = ",\n".join(f'    "{n}"' for n in all_names)
    new_all = f"__all__ = [\n{items},\n]"

    return content[: match.start()] + new_all + content[match.end() :]


def _insert_constants_after_all(content: str, const_block: str) -> str:
    """
    Insert constant declarations after the ``__all__`` block.
    """
    match = re.search(r"__all__\s*=\s*\[.*?]", content, re.DOTALL)
    if match is None:
        return content

    insert_pos = match.end()
    return content[:insert_pos] + "\n\n" + const_block + "\n" + content[insert_pos:]


def format_stub_files(root: Path) -> None:
    """
    Run ruff lint fixes and formatting on generated stub files.
    """
    stub_files = sorted(root.rglob("*.pyi"))
    if not stub_files:
        return

    file_args = [str(f) for f in stub_files]
    run_command(["ruff", "check", "--fix", *file_args], check=False)
    run_command(["ruff", "format", *file_args], check=False)


def build_extension() -> bool:
    """
    Build the extension using maturin.
    """
    print("Building extension with maturin...")

    run_command(["maturin", "develop", "--release"])

    print("Extension built successfully")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description="NautilusTrader v2 build script")
    parser.add_argument(
        "action",
        nargs="?",
        default="stubs",
        choices=["stubs", "build", "all"],
        help="Action to perform: stubs (default), build, or all",
    )

    args = parser.parse_args()

    print(f"Starting nautilus-trader v2 {args.action}...")

    try:
        if args.action in ["stubs", "all"]:
            print("Generating PyO3 docstrings...")
            subprocess.run(
                [sys.executable, str(Path(__file__).parent / "generate_docstrings.py")],
                check=True,
            )

            if not generate_stubs():
                return 1

        if args.action in ["build", "all"] and not build_extension():
            return 1

        action_name = "Build" if args.action != "stubs" else "Stub generation"
        print(f"{action_name} completed successfully")
        return 0

    except subprocess.CalledProcessError as e:
        print(f"Build failed: {e}")
        return 1
    except Exception as e:
        print(f"Unexpected error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
