#ifndef add_h
#define add_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>

typedef struct UUID4 {
  uint8_t value[36];
} UUID4;

/**
 * Returns the current seconds since the Unix epoch.
 */
double unix_timestamp(void);

/**
 * Returns the current milliseconds since the Unix epoch.
 */
int64_t unix_timestamp_ms(void);

/**
 * Returns the current microseconds since the Unix epoch.
 */
int64_t unix_timestamp_us(void);

/**
 * Returns the current nanoseconds since the Unix epoch.
 */
int64_t unix_timestamp_ns(void);

/**
 * Initializes a new instance of the UUID4 struct.
 */
struct UUID4 uuid4_new(void);

/**
 * Initializes a new instance of the UUID4 struct.
 */
struct UUID4 uuid4_free(struct UUID4 uuid);

/**
 * Returns a UTF-8 encoded bytes representation of the UUID value.
 */
const uint8_t (*uuid4_to_bytes(const struct UUID4 *self))[36];

/**
 * Initializes a new instance of the UUID4 struct.
 */
struct UUID4 uuid4_from_raw(const char *ptr);

#endif /* add_h */
