#!/usr/bin/env bash
# Runs a command with every adapter environment variable unset, so tests cannot
# silently depend on locally configured venue credentials. `make pre-flight`
# runs through this wrapper.
#
# When a new adapter environment variable is introduced (API key, secret,
# passphrase, private key, vault, account address or index, URL override, or
# token read from the process environment), add it to ADAPTER_ENV_VARS below.
# Do not add core variables such as NAUTILUS_PATH, internal process markers
# such as BLOCKCHAIN_PROXY_CHILD, names that tests set for themselves with
# std::env::set_var, or names that are not environment variables (for example
# POLY_API_KEY and POLY_PASSPHRASE, which are Polymarket HTTP header names).

set -euo pipefail

ADAPTER_ENV_VARS=(
  AX_API_KEY
  AX_API_SECRET
  BETFAIR_APP_KEY
  BETFAIR_PASSWORD
  BETFAIR_USERNAME
  BINANCE_API_KEY
  BINANCE_API_SECRET
  BINANCE_DEMO_API_KEY
  BINANCE_DEMO_API_SECRET
  BINANCE_ED25519_API_KEY
  BINANCE_ED25519_API_SECRET
  BINANCE_FUTURES_TESTNET_API_KEY
  BINANCE_FUTURES_TESTNET_API_SECRET
  BINANCE_FUTURES_TESTNET_ED25519_API_KEY
  BINANCE_FUTURES_TESTNET_ED25519_API_SECRET
  BINANCE_TESTNET_API_KEY
  BINANCE_TESTNET_API_SECRET
  BINANCE_TESTNET_ED25519_API_KEY
  BINANCE_TESTNET_ED25519_API_SECRET
  BITMEX_API_KEY
  BITMEX_API_SECRET
  BITMEX_TESTNET_API_KEY
  BITMEX_TESTNET_API_SECRET
  BITMEX_WS_URL
  BLOCKCHAIN_PRIVATE_KEY
  BYBIT_API_KEY
  BYBIT_API_SECRET
  BYBIT_DEMO_API_KEY
  BYBIT_DEMO_API_SECRET
  BYBIT_TESTNET_API_KEY
  BYBIT_TESTNET_API_SECRET
  COINBASE_API_KEY
  COINBASE_API_SECRET
  DATABENTO_API_KEY
  DERIBIT_API_KEY
  DERIBIT_API_SECRET
  DERIBIT_TESTNET_API_KEY
  DERIBIT_TESTNET_API_SECRET
  DERIVE_SESSION_PRIVATE_KEY
  DERIVE_SUBACCOUNT_ID
  DERIVE_TESTNET_SESSION_PRIVATE_KEY
  DERIVE_TESTNET_SUBACCOUNT_ID
  DERIVE_TESTNET_WALLET_ADDRESS
  DERIVE_WALLET_ADDRESS
  DYDX_PRIVATE_KEY
  DYDX_TESTNET_PRIVATE_KEY
  DYDX_TESTNET_WALLET_ADDRESS
  DYDX_WALLET_ADDRESS
  ENVIO_API_TOKEN
  HYPERLIQUID_ACCOUNT_ADDRESS
  HYPERLIQUID_PK
  HYPERLIQUID_TESTNET
  HYPERLIQUID_TESTNET_PK
  HYPERLIQUID_TESTNET_VAULT
  HYPERLIQUID_VAULT
  INFURA_API_KEY
  KRAKEN_FUTURES_API_KEY
  KRAKEN_FUTURES_API_SECRET
  KRAKEN_FUTURES_DEMO_API_KEY
  KRAKEN_FUTURES_DEMO_API_SECRET
  KRAKEN_SPOT_API_KEY
  KRAKEN_SPOT_API_SECRET
  LIGHTER_ACCOUNT_INDEX
  LIGHTER_API_KEY_INDEX
  LIGHTER_API_SECRET
  LIGHTER_ROBINHOOD_ACCOUNT_INDEX
  LIGHTER_ROBINHOOD_API_KEY_INDEX
  LIGHTER_ROBINHOOD_API_SECRET
  LIGHTER_ROBINHOOD_TESTNET_ACCOUNT_INDEX
  LIGHTER_ROBINHOOD_TESTNET_API_KEY_INDEX
  LIGHTER_ROBINHOOD_TESTNET_API_SECRET
  LIGHTER_TESTNET_ACCOUNT_INDEX
  LIGHTER_TESTNET_API_KEY_INDEX
  LIGHTER_TESTNET_API_SECRET
  OKX_API_KEY
  OKX_API_PASSPHRASE
  OKX_API_SECRET
  OKX_WS_URL
  POLYMARKET_API_KEY
  POLYMARKET_API_SECRET
  POLYMARKET_FUNDER
  POLYMARKET_PASSPHRASE
  POLYMARKET_PK
  RPC_HTTP_URL
  TARDIS_API_KEY
  TARDIS_MACHINE_WS_URL
  TWS_PASSWORD
  TWS_USERNAME
)

if (($# == 0)); then
  echo "Usage: bash scripts/strip-adapter-env.bash COMMAND [ARGS]..." >&2
  exit 2
fi

unset "${ADAPTER_ENV_VARS[@]}"
exec "$@"
