from __future__ import annotations

EQUITIES_MAKER_STRATEGY_ID = "equities_maker"
EQUITIES_MAKER_STRATEGY_FAMILY = "equities_maker"
EQUITIES_MAKER_STRATEGY_VERSION = "v1"
EQUITIES_MAKER_PARAM_SET = "equities_maker"
EQUITIES_MAKER_PROFILE_KEY = "equities_maker"


__all__ = [
    "EQUITIES_MAKER_PARAM_SET",
    "EQUITIES_MAKER_PROFILE_KEY",
    "EQUITIES_MAKER_STRATEGY_FAMILY",
    "EQUITIES_MAKER_STRATEGY_ID",
    "EQUITIES_MAKER_STRATEGY_VERSION",
]
