# -------------------------------------------------------------------------------------------------
#  Copyright (C) 2015-2025 Nautech Systems Pty Ltd. All rights reserved.
#  https://nautechsystems.io
#
#  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
#  You may not use this file except in compliance with the License.
#  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# -------------------------------------------------------------------------------------------------

from typing import Any

from nautilus_trader.model.instruments import Instrument

class LighterAccountType:
    def __init__(self, value: str) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterOrderType:
    @staticmethod
    def limit() -> LighterOrderType: ...
    @staticmethod
    def market() -> LighterOrderType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterTimeInForce:
    @staticmethod
    def gtc() -> LighterTimeInForce: ...
    @staticmethod
    def ioc() -> LighterTimeInForce: ...
    @staticmethod
    def fok() -> LighterTimeInForce: ...
    @staticmethod
    def post_only() -> LighterTimeInForce: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterOrderSide:
    @staticmethod
    def buy() -> LighterOrderSide: ...
    @staticmethod
    def sell() -> LighterOrderSide: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterOrderStatus:
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterInstrumentType:
    @staticmethod
    def spot() -> LighterInstrumentType: ...
    @staticmethod
    def perp() -> LighterInstrumentType: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

class LighterHttpClient:
    def __init__(
        self,
        base_http_url: str | None = None,
        base_ws_url: str | None = None,
        is_testnet: bool = False,
        api_key_private_key: str | None = None,
        eth_private_key: str | None = None,
        api_key_index: int | None = None,
        account_index: int | None = None,
    ) -> None: ...
    async def load_instruments(self) -> list[Instrument]: ...
    async def get_account(self, account_id: int | None = None) -> dict[str, Any]: ...
    async def get_next_nonce(self) -> int: ...
    def __repr__(self) -> str: ...

class LighterWebSocketClient:
    def __init__(
        self,
        base_http_url: str | None = None,
        base_ws_url: str | None = None,
        is_testnet: bool = False,
        api_key_private_key: str | None = None,
        eth_private_key: str | None = None,
        api_key_index: int | None = None,
        account_index: int | None = None,
    ) -> None: ...
    async def subscribe_order_book(self, market_id: int) -> None: ...
    async def subscribe_trades(self, market_id: int) -> None: ...
    async def subscribe_account(self, account_id: int) -> None: ...
    async def subscription_count(self) -> int: ...
    def __repr__(self) -> str: ...
