name: build-docs

permissions: # Principle of least privilege
  contents: read
  actions: read

on:
  push:
    branches: [master, nightly]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/step-security/harden-runner
      - uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: ${{ vars.STEP_SECURITY_EGRESS_POLICY || 'block' }}
          allowed-endpoints: >-
            ${{ vars.COMMON_ALLOWED_ENDPOINTS }}
            ${{ vars.CI_ALLOWED_ENDPOINTS }}

      - name: Fire event to nautilus_docs
        run: |
          curl -sS -L --retry 5 --retry-delay 2 --retry-all-errors --connect-timeout 5 --max-time 60 --fail-with-body \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/nautechsystems/nautilus_docs/dispatches \
            -d '{"event_type":"push"}'
